class AnkletsExecuter{
	public static void main(String[] args){

		Anklets anklet1 = new Anklets();
		anklet1.id = 1;
		anklet1.brand = "Giva";
		anklet1.price = 1200;
		anklet1.colour = "Silver";
		anklet1.material = "Silver";
		anklet1.design = "Plain";
		anklet1.size = "Free";
		anklet1.type = "Daily";
		System.out.println("anklet id is " + anklet1.id);
		System.out.println("brand is " + anklet1.brand);
		System.out.println("price is " + anklet1.price);
		System.out.println("colour is " + anklet1.colour);
		System.out.println("material is " + anklet1.material);
		System.out.println("design is " + anklet1.design);
		System.out.println("size is " + anklet1.size);
		System.out.println("type is " + anklet1.type);
		System.out.println("----------------------");

		Anklets anklet2 = new Anklets();
		anklet2.id = 2;
		anklet2.brand = "Priya";
		anklet2.price = 900;
		anklet2.colour = "Silver";
		anklet2.material = "Alloy";
		anklet2.design = "Beads";
		anklet2.size = "Free";
		anklet2.type = "Daily";
		System.out.println("anklet id is " + anklet2.id);
		System.out.println("brand is " + anklet2.brand);
		System.out.println("price is " + anklet2.price);
		System.out.println("colour is " + anklet2.colour);
		System.out.println("material is " + anklet2.material);
		System.out.println("design is " + anklet2.design);
		System.out.println("size is " + anklet2.size);
		System.out.println("type is " + anklet2.type);
		System.out.println("----------------------");

		Anklets anklet3 = new Anklets();
		anklet3.id = 3;
		anklet3.brand = "Zaveri";
		anklet3.price = 1500;
		anklet3.colour = "Silver";
		anklet3.material = "Silver";
		anklet3.design = "Chain";
		anklet3.size = "Free";
		anklet3.type = "Party";
		System.out.println("anklet id is " + anklet3.id);
		System.out.println("brand is " + anklet3.brand);
		System.out.println("price is " + anklet3.price);
		System.out.println("colour is " + anklet3.colour);
		System.out.println("material is " + anklet3.material);
		System.out.println("design is " + anklet3.design);
		System.out.println("size is " + anklet3.size);
		System.out.println("type is " + anklet3.type);
		System.out.println("----------------------");

		Anklets anklet4 = new Anklets();
		anklet4.id = 4;
		anklet4.brand = "Giva";
		anklet4.price = 1300;
		anklet4.colour = "Silver";
		anklet4.material = "Silver";
		anklet4.design = "Plain";
		anklet4.size = "Free";
		anklet4.type = "Daily";
		System.out.println("anklet id is " + anklet4.id);
		System.out.println("brand is " + anklet4.brand);
		System.out.println("price is " + anklet4.price);
		System.out.println("colour is " + anklet4.colour);
		System.out.println("material is " + anklet4.material);
		System.out.println("design is " + anklet4.design);
		System.out.println("size is " + anklet4.size);
		System.out.println("type is " + anklet4.type);
		System.out.println("----------------------");

		Anklets anklet5 = new Anklets();
		anklet5.id = 5;
		anklet5.brand = "Priya";
		anklet5.price = 950;
		anklet5.colour = "Silver";
		anklet5.material = "Alloy";
		anklet5.design = "Beads";
		anklet5.size = "Free";
		anklet5.type = "Daily";
		System.out.println("anklet id is " + anklet5.id);
		System.out.println("brand is " + anklet5.brand);
		System.out.println("price is " + anklet5.price);
		System.out.println("colour is " + anklet5.colour);
		System.out.println("material is " + anklet5.material);
		System.out.println("design is " + anklet5.design);
		System.out.println("size is " + anklet5.size);
		System.out.println("type is " + anklet5.type);
		System.out.println("----------------------");
		
		Anklets anklet6 = new Anklets();
		anklet6.id = 6;
		anklet6.brand = "Zaveri";
		anklet6.price = 1600;
		anklet6.colour = "Silver";
		anklet6.material = "Silver";
		anklet6.design = "Chain";
		anklet6.size = "Free";
		anklet6.type = "Party";
		System.out.println("anklet id is " + anklet6.id);
		System.out.println("brand is " + anklet6.brand);
		System.out.println("price is " + anklet6.price);
		System.out.println("colour is " + anklet6.colour);
		System.out.println("material is " + anklet6.material);
		System.out.println("design is " + anklet6.design);
		System.out.println("size is " + anklet6.size);
		System.out.println("type is " + anklet6.type);
		System.out.println("----------------------");

		Anklets anklet7 = new Anklets();
		anklet7.id = 7;
		anklet7.brand = "Giva";
		anklet7.price = 1250;
		anklet7.colour = "Silver";
		anklet7.material = "Silver";
		anklet7.design = "Plain";
		anklet7.size = "Free";
		anklet7.type = "Daily";
		System.out.println("anklet id is " + anklet7.id);
		System.out.println("brand is " + anklet7.brand);
		System.out.println("price is " + anklet7.price);
		System.out.println("colour is " + anklet7.colour);
		System.out.println("material is " + anklet7.material);
		System.out.println("design is " + anklet7.design);
		System.out.println("size is " + anklet7.size);
		System.out.println("type is " + anklet7.type);
		System.out.println("----------------------");

		Anklets anklet8 = new Anklets();
		anklet8.id = 8;
		anklet8.brand = "Priya";
		anklet8.price = 980;
		anklet8.colour = "Silver";
		anklet8.material = "Alloy";
		anklet8.design = "Beads";
		anklet8.size = "Free";
		anklet8.type = "Daily";
		System.out.println("anklet id is " + anklet8.id);
		System.out.println("brand is " + anklet8.brand);
		System.out.println("price is " + anklet8.price);
		System.out.println("colour is " + anklet8.colour);
		System.out.println("material is " + anklet8.material);
		System.out.println("design is " + anklet8.design);
		System.out.println("size is " + anklet8.size);
		System.out.println("type is " + anklet8.type);
		System.out.println("----------------------");

		Anklets anklet9 = new Anklets();
		anklet9.id = 9;
		anklet9.brand = "Zaveri";
		anklet9.price = 1700;
		anklet9.colour = "Silver";
		anklet9.material = "Silver";
		anklet9.design = "Chain";
		anklet9.size = "Free";
		anklet9.type = "Party";
		System.out.println("anklet id is " + anklet9.id);
		System.out.println("brand is " + anklet9.brand);
		System.out.println("price is " + anklet9.price);
		System.out.println("colour is " + anklet9.colour);
		System.out.println("material is " + anklet9.material);
		System.out.println("design is " + anklet9.design);
		System.out.println("size is " + anklet9.size);
		System.out.println("type is " + anklet9.type);
		System.out.println("----------------------");

		Anklets anklet10 = new Anklets();
		anklet10.id = 10;
		anklet10.brand = "Giva";
		anklet10.price = 1350;
		anklet10.colour = "Silver";
		anklet10.material = "Silver";
		anklet10.design = "Plain";
		anklet10.size = "Free";
		anklet10.type = "Daily";
		System.out.println("anklet id is " + anklet10.id);
		System.out.println("brand is " + anklet10.brand);
		System.out.println("price is " + anklet10.price);
		System.out.println("colour is " + anklet10.colour);
		System.out.println("material is " + anklet10.material);
		System.out.println("design is " + anklet10.design);
		System.out.println("size is " + anklet10.size);
		System.out.println("type is " + anklet10.type);
		System.out.println("----------------------");

		Anklets anklet11 = new Anklets();
		anklet11.id = 11;
		anklet11.brand = "Priya";
		anklet11.price = 1000;
		anklet11.colour = "Silver";
		anklet11.material = "Alloy";
		anklet11.design = "Beads";
		anklet11.size = "Free";
		anklet11.type = "Daily";
		System.out.println("anklet id is " + anklet11.id);
		System.out.println("brand is " + anklet11.brand);
		System.out.println("price is " + anklet11.price);
		System.out.println("colour is " + anklet11.colour);
		System.out.println("material is " + anklet11.material);
		System.out.println("design is " + anklet11.design);
		System.out.println("size is " + anklet11.size);
		System.out.println("type is " + anklet11.type);
		System.out.println("----------------------");

		Anklets anklet12 = new Anklets();
		anklet12.id = 12;
		anklet12.brand = "Zaveri";
		anklet12.price = 1800;
		anklet12.colour = "Silver";
		anklet12.material = "Silver";
		anklet12.design = "Chain";
		anklet12.size = "Free";
		anklet12.type = "Party";
		System.out.println("anklet id is " + anklet12.id);
		System.out.println("brand is " + anklet12.brand);
		System.out.println("price is " + anklet12.price);
		System.out.println("colour is " + anklet12.colour);
		System.out.println("material is " + anklet12.material);
		System.out.println("design is " + anklet12.design);
		System.out.println("size is " + anklet12.size);
		System.out.println("type is " + anklet12.type);
		System.out.println("----------------------");

		Anklets anklet13 = new Anklets();
		anklet13.id = 13;
		anklet13.brand = "Giva";
		anklet13.price = 1400;
		anklet13.colour = "Silver";
		anklet13.material = "Silver";
		anklet13.design = "Plain";
		anklet13.size = "Free";
		anklet13.type = "Daily";
		System.out.println("anklet id is " + anklet13.id);
		System.out.println("brand is " + anklet13.brand);
		System.out.println("price is " + anklet13.price);
		System.out.println("colour is " + anklet13.colour);
		System.out.println("material is " + anklet13.material);
		System.out.println("design is " + anklet13.design);
		System.out.println("size is " + anklet13.size);
		System.out.println("type is " + anklet13.type);
		System.out.println("----------------------");

		Anklets anklet14 = new Anklets();
		anklet14.id = 14;
		anklet14.brand = "Priya";
		anklet14.price = 1050;
		anklet14.colour = "Silver";
		anklet14.material = "Alloy";
		anklet14.design = "Beads";
		anklet14.size = "Free";
		anklet14.type = "Daily";
		System.out.println("anklet id is " + anklet14.id);
		System.out.println("brand is " + anklet14.brand);
		System.out.println("price is " + anklet14.price);
		System.out.println("colour is " + anklet14.colour);
		System.out.println("material is " + anklet14.material);
		System.out.println("design is " + anklet14.design);
		System.out.println("size is " + anklet14.size);
		System.out.println("type is " + anklet14.type);
		System.out.println("----------------------");

		Anklets anklet15 = new Anklets();
		anklet15.id = 15;
		anklet15.brand = "Zaveri";
		anklet15.price = 1900;
		anklet15.colour = "Silver";
		anklet15.material = "Silver";
		anklet15.design = "Chain";
		anklet15.size = "Free";
		anklet15.type = "Party";
		System.out.println("anklet id is " + anklet15.id);
		System.out.println("brand is " + anklet15.brand);
		System.out.println("price is " + anklet15.price);
		System.out.println("colour is " + anklet15.colour);
		System.out.println("material is " + anklet15.material);
		System.out.println("design is " + anklet15.design);
		System.out.println("size is " + anklet15.size);
		System.out.println("type is " + anklet15.type);
		System.out.println("----------------------");

		Anklets anklet16 = new Anklets();
		anklet16.id = 16;
		anklet16.brand = "Giva";
		anklet16.price = 1450;
		anklet16.colour = "Silver";
		anklet16.material = "Silver";
		anklet16.design = "Plain";
		anklet16.size = "Free";
		anklet16.type = "Daily";
		System.out.println("anklet id is " + anklet16.id);
		System.out.println("brand is " + anklet16.brand);
		System.out.println("price is " + anklet16.price);
		System.out.println("colour is " + anklet16.colour);
		System.out.println("material is " + anklet16.material);
		System.out.println("design is " + anklet16.design);
		System.out.println("size is " + anklet16.size);
		System.out.println("type is " + anklet16.type);
		System.out.println("----------------------");

		Anklets anklet17 = new Anklets();
		anklet17.id = 17;
		anklet17.brand = "Priya";
		anklet17.price = 1100;
		anklet17.colour = "Silver";
		anklet17.material = "Alloy";
		anklet17.design = "Beads";
		anklet17.size = "Free";
		anklet17.type = "Daily";
		System.out.println("anklet id is " + anklet17.id);
		System.out.println("brand is " + anklet17.brand);
		System.out.println("price is " + anklet17.price);
		System.out.println("colour is " + anklet17.colour);
		System.out.println("material is " + anklet17.material);
		System.out.println("design is " + anklet17.design);
		System.out.println("size is " + anklet17.size);
		System.out.println("type is " + anklet17.type);
		System.out.println("----------------------");

		Anklets anklet18 = new Anklets();
		anklet18.id = 18;
		anklet18.brand = "Zaveri";
		anklet18.price = 2000;
		anklet18.colour = "Silver";
		anklet18.material = "Silver";
		anklet18.design = "Chain";
		anklet18.size = "Free";
		anklet18.type = "Party";
		System.out.println("anklet id is " + anklet18.id);
		System.out.println("brand is " + anklet18.brand);
		System.out.println("price is " + anklet18.price);
		System.out.println("colour is " + anklet18.colour);
		System.out.println("material is " + anklet18.material);
		System.out.println("design is " + anklet18.design);
		System.out.println("size is " + anklet18.size);
		System.out.println("type is " + anklet18.type);
		System.out.println("----------------------");

		Anklets anklet19 = new Anklets();
		anklet19.id = 19;
		anklet19.brand = "Giva";
		anklet19.price = 1500;
		anklet19.colour = "Silver";
		anklet19.material = "Silver";
		anklet19.design = "Plain";
		anklet19.size = "Free";
		anklet19.type = "Daily";
		System.out.println("anklet id is " + anklet19.id);
		System.out.println("brand is " + anklet19.brand);
		System.out.println("price is " + anklet19.price);
		System.out.println("colour is " + anklet19.colour);
		System.out.println("material is " + anklet19.material);
		System.out.println("design is " + anklet19.design);
		System.out.println("size is " + anklet19.size);
		System.out.println("type is " + anklet19.type);
		System.out.println("----------------------");

		Anklets anklet20 = new Anklets();
		anklet20.id = 20;
		anklet20.brand = "Priya";
		anklet20.price = 1150;
		anklet20.colour = "Silver";
		anklet20.material = "Alloy";
		anklet20.design = "Beads";
		anklet20.size = "Free";
		anklet20.type = "Daily";
		System.out.println("anklet id is " + anklet20.id);
		System.out.println("brand is " + anklet20.brand);
		System.out.println("price is " + anklet20.price);
		System.out.println("colour is " + anklet20.colour);
		System.out.println("material is " + anklet20.material);
		System.out.println("design is " + anklet20.design);
		System.out.println("size is " + anklet20.size);
		System.out.println("type is " + anklet20.type);
		System.out.println("----------------------");

		Anklets anklet21 = new Anklets();
		anklet21.id = 21;
		anklet21.brand = "Zaveri";
		anklet21.price = 2100;
		anklet21.colour = "Silver";
		anklet21.material = "Silver";
		anklet21.design = "Chain";
		anklet21.size = "Free";
		anklet21.type = "Party";
		System.out.println("anklet id is " + anklet21.id);
		System.out.println("brand is " + anklet21.brand);
		System.out.println("price is " + anklet21.price);
		System.out.println("colour is " + anklet21.colour);
		System.out.println("material is " + anklet21.material);
		System.out.println("design is " + anklet21.design);
		System.out.println("size is " + anklet21.size);
		System.out.println("type is " + anklet21.type);
		System.out.println("----------------------");

		Anklets anklet22 = new Anklets();
		anklet22.id = 22;
		anklet22.brand = "Giva";
		anklet22.price = 1550;
		anklet22.colour = "Silver";
		anklet22.material = "Silver";
		anklet22.design = "Plain";
		anklet22.size = "Free";
		anklet22.type = "Daily";
		System.out.println("anklet id is " + anklet22.id);
		System.out.println("brand is " + anklet22.brand);
		System.out.println("price is " + anklet22.price);
		System.out.println("colour is " + anklet22.colour);
		System.out.println("material is " + anklet22.material);
		System.out.println("design is " + anklet22.design);
		System.out.println("size is " + anklet22.size);
		System.out.println("type is " + anklet22.type);
		System.out.println("----------------------");

		Anklets anklet23 = new Anklets();
		anklet23.id = 23;
		anklet23.brand = "Priya";
		anklet23.price = 1200;
		anklet23.colour = "Silver";
		anklet23.material = "Alloy";
		anklet23.design = "Beads";
		anklet23.size = "Free";
		anklet23.type = "Daily";
		System.out.println("anklet id is " + anklet23.id);
		System.out.println("brand is " + anklet23.brand);
		System.out.println("price is " + anklet23.price);
		System.out.println("colour is " + anklet23.colour);
		System.out.println("material is " + anklet23.material);
		System.out.println("design is " + anklet23.design);
		System.out.println("size is " + anklet23.size);
		System.out.println("type is " + anklet23.type);
		System.out.println("----------------------");

		Anklets anklet24 = new Anklets();
		anklet24.id = 24;
		anklet24.brand = "Zaveri";
		anklet24.price = 2200;
		anklet24.colour = "Silver";
		anklet24.material = "Silver";
		anklet24.design = "Designer";
		anklet24.size = "Free";
		anklet24.type = "Party";
		System.out.println("anklet id is " + anklet24.id);
		System.out.println("brand is " + anklet24.brand);
		System.out.println("price is " + anklet24.price);
		System.out.println("colour is " + anklet24.colour);
		System.out.println("material is " + anklet24.material);
		System.out.println("design is " + anklet24.design);
		System.out.println("size is " + anklet24.size);
		System.out.println("type is " + anklet24.type);
		System.out.println("----------------------");

		Anklets anklet25 = new Anklets();
		anklet25.id = 25;
		anklet25.brand = "Giva";
		anklet25.price = 1600;
		anklet25.colour = "Silver";
		anklet25.material = "Silver";
		anklet25.design = "Plain";
		anklet25.size = "Free";
		anklet25.type = "Daily";
		System.out.println("anklet id is " + anklet25.id);
		System.out.println("brand is " + anklet25.brand);
		System.out.println("price is " + anklet25.price);
		System.out.println("colour is " + anklet25.colour);
		System.out.println("material is " + anklet25.material);
		System.out.println("design is " + anklet25.design);
		System.out.println("size is " + anklet25.size);
		System.out.println("type is " + anklet25.type);
		System.out.println("----------------------");

		Anklets anklet26 = new Anklets();
		anklet26.id = 26;
		anklet26.brand = "Priya";
		anklet26.price = 1250;
		anklet26.colour = "Silver";
		anklet26.material = "Alloy";
		anklet26.design = "Beads";
		anklet26.size = "Free";
		anklet26.type = "Daily";
		System.out.println("anklet id is " + anklet26.id);
		System.out.println("brand is " + anklet26.brand);
		System.out.println("price is " + anklet26.price);
		System.out.println("colour is " + anklet26.colour);
		System.out.println("material is " + anklet26.material);
		System.out.println("design is " + anklet26.design);
		System.out.println("size is " + anklet26.size);
		System.out.println("type is " + anklet26.type);
		System.out.println("----------------------");

		Anklets anklet27 = new Anklets();
		anklet27.id = 27;
		anklet27.brand = "Zaveri";
		anklet27.price = 2300;
		anklet27.colour = "Silver";
		anklet27.material = "Silver";
		anklet27.design = "Designer";
		anklet27.size = "Free";
		anklet27.type = "Party";
		System.out.println("anklet id is " + anklet27.id);
		System.out.println("brand is " + anklet27.brand);
		System.out.println("price is " + anklet27.price);
		System.out.println("colour is " + anklet27.colour);
		System.out.println("material is " + anklet27.material);
		System.out.println("design is " + anklet27.design);
		System.out.println("size is " + anklet27.size);
		System.out.println("type is " + anklet27.type);
		System.out.println("----------------------");

		Anklets anklet28 = new Anklets();
		anklet28.id = 28;
		anklet28.brand = "Giva";
		anklet28.price = 1700;
		anklet28.colour = "Silver";
		anklet28.material = "Silver";
		anklet28.design = "Plain";
		anklet28.size = "Free";
		anklet28.type = "Daily";
		System.out.println("anklet id is " + anklet28.id);
		System.out.println("brand is " + anklet28.brand);
		System.out.println("price is " + anklet28.price);
		System.out.println("colour is " + anklet28.colour);
		System.out.println("material is " + anklet28.material);
		System.out.println("design is " + anklet28.design);
		System.out.println("size is " + anklet28.size);
		System.out.println("type is " + anklet28.type);
		System.out.println("----------------------");

		Anklets anklet29 = new Anklets();
		anklet29.id = 29;
		anklet29.brand = "Priya";
		anklet29.price = 1300;
		anklet29.colour = "Silver";
		anklet29.material = "Alloy";
		anklet29.design = "Beads";
		anklet29.size = "Free";
		anklet29.type = "Daily";
		System.out.println("anklet id is " + anklet29.id);
		System.out.println("brand is " + anklet29.brand);
		System.out.println("price is " + anklet29.price);
		System.out.println("colour is " + anklet29.colour);
		System.out.println("material is " + anklet29.material);
		System.out.println("design is " + anklet29.design);
		System.out.println("size is " + anklet29.size);
		System.out.println("type is " + anklet29.type);
		System.out.println("----------------------");

		Anklets anklet30 = new Anklets();
		anklet30.id = 30;
		anklet30.brand = "Zaveri";
		anklet30.price = 2400;
		anklet30.colour = "Silver";
		anklet30.material = "Silver";
		anklet30.design = "Designer";
		anklet30.size = "Free";
		anklet30.type = "Party";
		System.out.println("anklet id is " + anklet30.id);
		System.out.println("brand is " + anklet30.brand);
		System.out.println("price is " + anklet30.price);
		System.out.println("colour is " + anklet30.colour);
		System.out.println("material is " + anklet30.material);
		System.out.println("design is " + anklet30.design);
		System.out.println("size is " + anklet30.size);
		System.out.println("type is " + anklet30.type);
		System.out.println("----------------------");



	}
}