class BanglesExecuter{
	public static void main(String[] args){

		Bangles bangle1 = new Bangles();
		bangle1.id = 1;
		bangle1.brand = "Giva";
		bangle1.price = 200;
		bangle1.colour = "Gold";
		bangle1.material = "Metal";
		bangle1.size = "2.4";
		bangle1.design = "Plain";
		bangle1.type = "Daily";
		System.out.println("bangle id is " + bangle1.id);
		System.out.println("brand is " + bangle1.brand);
		System.out.println("price is " + bangle1.price);
		System.out.println("colour is " + bangle1.colour);
		System.out.println("material is " + bangle1.material);
		System.out.println("size is " + bangle1.size);
		System.out.println("design is " + bangle1.design);
		System.out.println("type is " + bangle1.type);
		System.out.println("----------------------");

		Bangles bangle2 = new Bangles();
		bangle2.id = 2;
		bangle2.brand = "Priya";
		bangle2.price = 150;
		bangle2.colour = "Red";
		bangle2.material = "Glass";
		bangle2.size = "2.6";
		bangle2.design = "Simple";
		bangle2.type = "Daily";
		System.out.println("bangle id is " + bangle2.id);
		System.out.println("brand is " + bangle2.brand);
		System.out.println("price is " + bangle2.price);
		System.out.println("colour is " + bangle2.colour);
		System.out.println("material is " + bangle2.material);
		System.out.println("size is " + bangle2.size);
		System.out.println("design is " + bangle2.design);
		System.out.println("type is " + bangle2.type);
		System.out.println("----------------------");

		Bangles bangle3 = new Bangles();
		bangle3.id = 3;
		bangle3.brand = "Zaveri";
		bangle3.price = 350;
		bangle3.colour = "Green";
		bangle3.material = "Metal";
		bangle3.size = "2.4";
		bangle3.design = "Stone";
		bangle3.type = "Party";
		System.out.println("bangle id is " + bangle3.id);
		System.out.println("brand is " + bangle3.brand);
		System.out.println("price is " + bangle3.price);
		System.out.println("colour is " + bangle3.colour);
		System.out.println("material is " + bangle3.material);
		System.out.println("size is " + bangle3.size);
		System.out.println("design is " + bangle3.design);
		System.out.println("type is " + bangle3.type);
		System.out.println("----------------------");

		Bangles bangle4 = new Bangles();
		bangle4.id = 4;
		bangle4.brand = "Giva";
		bangle4.price = 400;
		bangle4.colour = "Gold";
		bangle4.material = "Metal";
		bangle4.size = "2.8";
		bangle4.design = "Designer";
		bangle4.type = "Wedding";
		System.out.println("bangle id is " + bangle4.id);
		System.out.println("brand is " + bangle4.brand);
		System.out.println("price is " + bangle4.price);
		System.out.println("colour is " + bangle4.colour);
		System.out.println("material is " + bangle4.material);
		System.out.println("size is " + bangle4.size);
		System.out.println("design is " + bangle4.design);
		System.out.println("type is " + bangle4.type);
		System.out.println("----------------------");

		Bangles bangle5 = new Bangles();
		bangle5.id = 5;
		bangle5.brand = "Priya";
		bangle5.price = 180;
		bangle5.colour = "Blue";
		bangle5.material = "Glass";
		bangle5.size = "2.6";
		bangle5.design = "Plain";
		bangle5.type = "Daily";
		System.out.println("bangle id is " + bangle5.id);
		System.out.println("brand is " + bangle5.brand);
		System.out.println("price is " + bangle5.price);
		System.out.println("colour is " + bangle5.colour);
		System.out.println("material is " + bangle5.material);
		System.out.println("size is " + bangle5.size);
		System.out.println("design is " + bangle5.design);
		System.out.println("type is " + bangle5.type);
		System.out.println("----------------------");

		Bangles bangle6 = new Bangles();
		bangle6.id = 6;
		bangle6.brand = "Zaveri";
		bangle6.price = 300;
		bangle6.colour = "Red";
		bangle6.material = "Metal";
		bangle6.size = "2.4";
		bangle6.design = "Stone";
		bangle6.type = "Party";
		System.out.println("bangle id is " + bangle6.id);
		System.out.println("brand is " + bangle6.brand);
		System.out.println("price is " + bangle6.price);
		System.out.println("colour is " + bangle6.colour);
		System.out.println("material is " + bangle6.material);
		System.out.println("size is " + bangle6.size);
		System.out.println("design is " + bangle6.design);
		System.out.println("type is " + bangle6.type);
		System.out.println("----------------------");

		Bangles bangle7 = new Bangles();
		bangle7.id = 7;
		bangle7.brand = "Giva";
		bangle7.price = 420;
		bangle7.colour = "Gold";
		bangle7.material = "Metal";
		bangle7.size = "2.8";
		bangle7.design = "Designer";
		bangle7.type = "Wedding";
		System.out.println("bangle id is " + bangle7.id);
		System.out.println("brand is " + bangle7.brand);
		System.out.println("price is " + bangle7.price);
		System.out.println("colour is " + bangle7.colour);
		System.out.println("material is " + bangle7.material);
		System.out.println("size is " + bangle7.size);
		System.out.println("design is " + bangle7.design);
		System.out.println("type is " + bangle7.type);
		System.out.println("----------------------");

		Bangles bangle8 = new Bangles();
		bangle8.id = 8;
		bangle8.brand = "Priya";
		bangle8.price = 160;
		bangle8.colour = "Green";
		bangle8.material = "Glass";
		bangle8.size = "2.6";
		bangle8.design = "Simple";
		bangle8.type = "Daily";
		System.out.println("bangle id is " + bangle8.id);
		System.out.println("brand is " + bangle8.brand);
		System.out.println("price is " + bangle8.price);
		System.out.println("colour is " + bangle8.colour);
		System.out.println("material is " + bangle8.material);
		System.out.println("size is " + bangle8.size);
		System.out.println("design is " + bangle8.design);
		System.out.println("type is " + bangle8.type);
		System.out.println("----------------------");
		
		Bangles bangle9 = new Bangles();
		bangle9.id = 9;
		bangle9.brand = "Zaveri";
		bangle9.price = 320;
		bangle9.colour = "Pink";
		bangle9.material = "Metal";
		bangle9.size = "2.4";
		bangle9.design = "Stone";
		bangle9.type = "Party";
		System.out.println("bangle id is " + bangle9.id);
		System.out.println("brand is " + bangle9.brand);
		System.out.println("price is " + bangle9.price);
		System.out.println("colour is " + bangle9.colour);
		System.out.println("material is " + bangle9.material);
		System.out.println("size is " + bangle9.size);
		System.out.println("design is " + bangle9.design);
		System.out.println("type is " + bangle9.type);
		System.out.println("----------------------");

		Bangles bangle10 = new Bangles();
		bangle10.id = 10;
		bangle10.brand = "Giva";
		bangle10.price = 450;
		bangle10.colour = "Gold";
		bangle10.material = "Metal";
		bangle10.size = "2.8";
		bangle10.design = "Designer";
		bangle10.type = "Wedding";
		System.out.println("bangle id is " + bangle10.id);
		System.out.println("brand is " + bangle10.brand);
		System.out.println("price is " + bangle10.price);
		System.out.println("colour is " + bangle10.colour);
		System.out.println("material is " + bangle10.material);
		System.out.println("size is " + bangle10.size);
		System.out.println("design is " + bangle10.design);
		System.out.println("type is " + bangle10.type);
		System.out.println("----------------------");

		Bangles bangle11 = new Bangles();
		bangle11.id = 11;
		bangle11.brand = "Priya";
		bangle11.price = 140;
		bangle11.colour = "Red";
		bangle11.material = "Glass";
		bangle11.size = "2.6";
		bangle11.design = "Simple";
		bangle11.type = "Daily";
		System.out.println("bangle id is " + bangle11.id);
		System.out.println("brand is " + bangle11.brand);
		System.out.println("price is " + bangle11.price);
		System.out.println("colour is " + bangle11.colour);
		System.out.println("material is " + bangle11.material);
		System.out.println("size is " + bangle11.size);
		System.out.println("design is " + bangle11.design);
		System.out.println("type is " + bangle11.type);
		System.out.println("----------------------");

		Bangles bangle12 = new Bangles();
		bangle12.id = 12;
		bangle12.brand = "Zaveri";
		bangle12.price = 360;
		bangle12.colour = "Green";
		bangle12.material = "Metal";
		bangle12.size = "2.4";
		bangle12.design = "Stone";
		bangle12.type = "Party";
		System.out.println("bangle id is " + bangle12.id);
		System.out.println("brand is " + bangle12.brand);
		System.out.println("price is " + bangle12.price);
		System.out.println("colour is " + bangle12.colour);
		System.out.println("material is " + bangle12.material);
		System.out.println("size is " + bangle12.size);
		System.out.println("design is " + bangle12.design);
		System.out.println("type is " + bangle12.type);
		System.out.println("----------------------");

		Bangles bangle13 = new Bangles();
		bangle13.id = 13;
		bangle13.brand = "Giva";
		bangle13.price = 480;
		bangle13.colour = "Gold";
		bangle13.material = "Metal";
		bangle13.size = "2.8";
		bangle13.design = "Designer";
		bangle13.type = "Wedding";
		System.out.println("bangle id is " + bangle13.id);
		System.out.println("brand is " + bangle13.brand);
		System.out.println("price is " + bangle13.price);
		System.out.println("colour is " + bangle13.colour);
		System.out.println("material is " + bangle13.material);
		System.out.println("size is " + bangle13.size);
		System.out.println("design is " + bangle13.design);
		System.out.println("type is " + bangle13.type);
		System.out.println("----------------------");

		Bangles bangle14 = new Bangles();
		bangle14.id = 14;
		bangle14.brand = "Priya";
		bangle14.price = 170;
		bangle14.colour = "Blue";
		bangle14.material = "Glass";
		bangle14.size = "2.6";
		bangle14.design = "Plain";
		bangle14.type = "Daily";
		System.out.println("bangle id is " + bangle14.id);
		System.out.println("brand is " + bangle14.brand);
		System.out.println("price is " + bangle14.price);
		System.out.println("colour is " + bangle14.colour);
		System.out.println("material is " + bangle14.material);
		System.out.println("size is " + bangle14.size);
		System.out.println("design is " + bangle14.design);
		System.out.println("type is " + bangle14.type);
		System.out.println("----------------------");

		Bangles bangle15 = new Bangles();
		bangle15.id = 15;
		bangle15.brand = "Zaveri";
		bangle15.price = 330;
		bangle15.colour = "Maroon";
		bangle15.material = "Metal";
		bangle15.size = "2.4";
		bangle15.design = "Stone";
		bangle15.type = "Party";
		System.out.println("bangle id is " + bangle15.id);
		System.out.println("brand is " + bangle15.brand);
		System.out.println("price is " + bangle15.price);
		System.out.println("colour is " + bangle15.colour);
		System.out.println("material is " + bangle15.material);
		System.out.println("size is " + bangle15.size);
		System.out.println("design is " + bangle15.design);
		System.out.println("type is " + bangle15.type);
		System.out.println("----------------------");

		Bangles bangle16 = new Bangles();
		bangle16.id = 16;
		bangle16.brand = "Giva";
		bangle16.price = 500;
		bangle16.colour = "Gold";
		bangle16.material = "Metal";
		bangle16.size = "2.8";
		bangle16.design = "Designer";
		bangle16.type = "Wedding";
		System.out.println("bangle id is " + bangle16.id);
		System.out.println("brand is " + bangle16.brand);
		System.out.println("price is " + bangle16.price);
		System.out.println("colour is " + bangle16.colour);
		System.out.println("material is " + bangle16.material);
		System.out.println("size is " + bangle16.size);
		System.out.println("design is " + bangle16.design);
		System.out.println("type is " + bangle16.type);
		System.out.println("----------------------");

		Bangles bangle17 = new Bangles();
		bangle17.id = 17;
		bangle17.brand = "Priya";
		bangle17.price = 155;
		bangle17.colour = "Green";
		bangle17.material = "Glass";
		bangle17.size = "2.6";
		bangle17.design = "Simple";
		bangle17.type = "Daily";
		System.out.println("bangle id is " + bangle17.id);
		System.out.println("brand is " + bangle17.brand);
		System.out.println("price is " + bangle17.price);
		System.out.println("colour is " + bangle17.colour);
		System.out.println("material is " + bangle17.material);
		System.out.println("size is " + bangle17.size);
		System.out.println("design is " + bangle17.design);
		System.out.println("type is " + bangle17.type);
		System.out.println("----------------------");

		Bangles bangle18 = new Bangles();
		bangle18.id = 18;
		bangle18.brand = "Zaveri";
		bangle18.price = 370;
		bangle18.colour = "Pink";
		bangle18.material = "Metal";
		bangle18.size = "2.4";
		bangle18.design = "Stone";
		bangle18.type = "Party";
		System.out.println("bangle id is " + bangle18.id);
		System.out.println("brand is " + bangle18.brand);
		System.out.println("price is " + bangle18.price);
		System.out.println("colour is " + bangle18.colour);
		System.out.println("material is " + bangle18.material);
		System.out.println("size is " + bangle18.size);
		System.out.println("design is " + bangle18.design);
		System.out.println("type is " + bangle18.type);
		System.out.println("----------------------");

		Bangles bangle19 = new Bangles();
		bangle19.id = 19;
		bangle19.brand = "Giva";
		bangle19.price = 520;
		bangle19.colour = "Gold";
		bangle19.material = "Metal";
		bangle19.size = "2.8";
		bangle19.design = "Designer";
		bangle19.type = "Wedding";
		System.out.println("bangle id is " + bangle19.id);
		System.out.println("brand is " + bangle19.brand);
		System.out.println("price is " + bangle19.price);
		System.out.println("colour is " + bangle19.colour);
		System.out.println("material is " + bangle19.material);
		System.out.println("size is " + bangle19.size);
		System.out.println("design is " + bangle19.design);
		System.out.println("type is " + bangle19.type);
		System.out.println("----------------------");

		Bangles bangle20 = new Bangles();
		bangle20.id = 20;
		bangle20.brand = "Priya";
		bangle20.price = 165;
		bangle20.colour = "Blue";
		bangle20.material = "Glass";
		bangle20.size = "2.6";
		bangle20.design = "Plain";
		bangle20.type = "Daily";
		System.out.println("bangle id is " + bangle20.id);
		System.out.println("brand is " + bangle20.brand);
		System.out.println("price is " + bangle20.price);
		System.out.println("colour is " + bangle20.colour);
		System.out.println("material is " + bangle20.material);
		System.out.println("size is " + bangle20.size);
		System.out.println("design is " + bangle20.design);
		System.out.println("type is " + bangle20.type);
		System.out.println("----------------------");

		Bangles bangle21 = new Bangles();
		bangle21.id = 21;
		bangle21.brand = "Zaveri";
		bangle21.price = 340;
		bangle21.colour = "Red";
		bangle21.material = "Metal";
		bangle21.size = "2.4";
		bangle21.design = "Stone";
		bangle21.type = "Party";
		System.out.println("bangle id is " + bangle21.id);
		System.out.println("brand is " + bangle21.brand);
		System.out.println("price is " + bangle21.price);
		System.out.println("colour is " + bangle21.colour);
		System.out.println("material is " + bangle21.material);
		System.out.println("size is " + bangle21.size);
		System.out.println("design is " + bangle21.design);
		System.out.println("type is " + bangle21.type);
		System.out.println("----------------------");

		Bangles bangle22 = new Bangles();
		bangle22.id = 22;
		bangle22.brand = "Giva";
		bangle22.price = 540;
		bangle22.colour = "Gold";
		bangle22.material = "Metal";
		bangle22.size = "2.8";
		bangle22.design = "Designer";
		bangle22.type = "Wedding";
		System.out.println("bangle id is " + bangle22.id);
		System.out.println("brand is " + bangle22.brand);
		System.out.println("price is " + bangle22.price);
		System.out.println("colour is " + bangle22.colour);
		System.out.println("material is " + bangle22.material);
		System.out.println("size is " + bangle22.size);
		System.out.println("design is " + bangle22.design);
		System.out.println("type is " + bangle22.type);
		System.out.println("----------------------");

		Bangles bangle23 = new Bangles();
		bangle23.id = 23;
		bangle23.brand = "Priya";
		bangle23.price = 175;
		bangle23.colour = "Green";
		bangle23.material = "Glass";
		bangle23.size = "2.6";
		bangle23.design = "Simple";
		bangle23.type = "Daily";
		System.out.println("bangle id is " + bangle23.id);
		System.out.println("brand is " + bangle23.brand);
		System.out.println("price is " + bangle23.price);
		System.out.println("colour is " + bangle23.colour);
		System.out.println("material is " + bangle23.material);
		System.out.println("size is " + bangle23.size);
		System.out.println("design is " + bangle23.design);
		System.out.println("type is " + bangle23.type);
		System.out.println("----------------------");

		Bangles bangle24 = new Bangles();
		bangle24.id = 24;
		bangle24.brand = "Zaveri";
		bangle24.price = 380;
		bangle24.colour = "Pink";
		bangle24.material = "Metal";
		bangle24.size = "2.4";
		bangle24.design = "Stone";
		bangle24.type = "Party";
		System.out.println("bangle id is " + bangle24.id);
		System.out.println("brand is " + bangle24.brand);
		System.out.println("price is " + bangle24.price);
		System.out.println("colour is " + bangle24.colour);
		System.out.println("material is " + bangle24.material);
		System.out.println("size is " + bangle24.size);
		System.out.println("design is " + bangle24.design);
		System.out.println("type is " + bangle24.type);
		System.out.println("----------------------");

		Bangles bangle25 = new Bangles();
		bangle25.id = 25;
		bangle25.brand = "Giva";
		bangle25.price = 560;
		bangle25.colour = "Gold";
		bangle25.material = "Metal";
		bangle25.size = "2.8";
		bangle25.design = "Designer";
		bangle25.type = "Wedding";
		System.out.println("bangle id is " + bangle25.id);
		System.out.println("brand is " + bangle25.brand);
		System.out.println("price is " + bangle25.price);
		System.out.println("colour is " + bangle25.colour);
		System.out.println("material is " + bangle25.material);
		System.out.println("size is " + bangle25.size);
		System.out.println("design is " + bangle25.design);
		System.out.println("type is " + bangle25.type);
		System.out.println("----------------------");

		Bangles bangle26 = new Bangles();
		bangle26.id = 26;
		bangle26.brand = "Priya";
		bangle26.price = 185;
		bangle26.colour = "Blue";
		bangle26.material = "Glass";
		bangle26.size = "2.6";
		bangle26.design = "Plain";
		bangle26.type = "Daily";
		System.out.println("bangle id is " + bangle26.id);
		System.out.println("brand is " + bangle26.brand);
		System.out.println("price is " + bangle26.price);
		System.out.println("colour is " + bangle26.colour);
		System.out.println("material is " + bangle26.material);
		System.out.println("size is " + bangle26.size);
		System.out.println("design is " + bangle26.design);
		System.out.println("type is " + bangle26.type);
		System.out.println("----------------------");

		Bangles bangle27 = new Bangles();
		bangle27.id = 27;
		bangle27.brand = "Zaveri";
		bangle27.price = 390;
		bangle27.colour = "Maroon";
		bangle27.material = "Metal";
		bangle27.size = "2.4";
		bangle27.design = "Stone";
		bangle27.type = "Party";
		System.out.println("bangle id is " + bangle27.id);
		System.out.println("brand is " + bangle27.brand);
		System.out.println("price is " + bangle27.price);
		System.out.println("colour is " + bangle27.colour);
		System.out.println("material is " + bangle27.material);
		System.out.println("size is " + bangle27.size);
		System.out.println("design is " + bangle27.design);
		System.out.println("type is " + bangle27.type);
		System.out.println("----------------------");

		Bangles bangle28 = new Bangles();
		bangle28.id = 28;
		bangle28.brand = "Giva";
		bangle28.price = 580;
		bangle28.colour = "Gold";
		bangle28.material = "Metal";
		bangle28.size = "2.8";
		bangle28.design = "Designer";
		bangle28.type = "Wedding";
		System.out.println("bangle id is " + bangle28.id);
		System.out.println("brand is " + bangle28.brand);
		System.out.println("price is " + bangle28.price);
		System.out.println("colour is " + bangle28.colour);
		System.out.println("material is " + bangle28.material);
		System.out.println("size is " + bangle28.size);
		System.out.println("design is " + bangle28.design);
		System.out.println("type is " + bangle28.type);
		System.out.println("----------------------");

		Bangles bangle29 = new Bangles();
		bangle29.id = 29;
		bangle29.brand = "Priya";
		bangle29.price = 190;
		bangle29.colour = "Green";
		bangle29.material = "Glass";
		bangle29.size = "2.6";
		bangle29.design = "Simple";
		bangle29.type = "Daily";
		System.out.println("bangle id is " + bangle29.id);
		System.out.println("brand is " + bangle29.brand);
		System.out.println("price is " + bangle29.price);
		System.out.println("colour is " + bangle29.colour);
		System.out.println("material is " + bangle29.material);
		System.out.println("size is " + bangle29.size);
		System.out.println("design is " + bangle29.design);
		System.out.println("type is " + bangle29.type);
		System.out.println("----------------------");

		Bangles bangle30 = new Bangles();
		bangle30.id = 30;
		bangle30.brand = "Zaveri";
		bangle30.price = 400;
		bangle30.colour = "Red";
		bangle30.material = "Metal";
		bangle30.size = "2.4";
		bangle30.design = "Stone";
		bangle30.type = "Wedding";
		System.out.println("bangle id is " + bangle30.id);
		System.out.println("brand is " + bangle30.brand);
		System.out.println("price is " + bangle30.price);
		System.out.println("colour is " + bangle30.colour);
		System.out.println("material is " + bangle30.material);
		System.out.println("size is " + bangle30.size);
		System.out.println("design is " + bangle30.design);
		System.out.println("type is " + bangle30.type);
		System.out.println("----------------------");
	}
}