class BindiExecuter{
	public static void main(String[] args){

		Bindi bindi1 = new Bindi();
		bindi1.id = 1;
		bindi1.brand = "Lakme";
		bindi1.price = 50;
		bindi1.colour = "Red";
		bindi1.shape = "Round";
		bindi1.size = "Small";
		bindi1.material = "Sticker";
		bindi1.type = "Daily";
		System.out.println("bindi id is " + bindi1.id);
		System.out.println("brand is " + bindi1.brand);
		System.out.println("price is " + bindi1.price);
		System.out.println("colour is " + bindi1.colour);
		System.out.println("shape is " + bindi1.shape);
		System.out.println("size is " + bindi1.size);
		System.out.println("material is " + bindi1.material);
		System.out.println("type is " + bindi1.type);
	    System.out.println("----------------------");

		Bindi bindi2 = new Bindi();
		bindi2.id = 2;
		bindi2.brand = "Elle18";
		bindi2.price = 60;
		bindi2.colour = "Black";
		bindi2.shape = "Round";
		bindi2.size = "Medium";
		bindi2.material = "Sticker";
		bindi2.type = "Daily";
		System.out.println("bindi id is " + bindi2.id);
		System.out.println("brand is " + bindi2.brand);
		System.out.println("price is " + bindi2.price);
		System.out.println("colour is " + bindi2.colour);
		System.out.println("shape is " + bindi2.shape);
		System.out.println("size is " + bindi2.size);
		System.out.println("material is " + bindi2.material);
		System.out.println("type is " + bindi2.type);
		System.out.println("----------------------");

		Bindi bindi3 = new Bindi();
		bindi3.id = 3;
		bindi3.brand = "BlueHeaven";
		bindi3.price = 45;
		bindi3.colour = "Maroon";
		bindi3.shape = "Oval";
		bindi3.size = "Small";
		bindi3.material = "Sticker";
		bindi3.type = "Daily";
		System.out.println("bindi id is " + bindi3.id);
		System.out.println("brand is " + bindi3.brand);
		System.out.println("price is " + bindi3.price);
		System.out.println("colour is " + bindi3.colour);
		System.out.println("shape is " + bindi3.shape);
		System.out.println("size is " + bindi3.size);
		System.out.println("material is " + bindi3.material);
		System.out.println("type is " + bindi3.type);
		System.out.println("----------------------");
		
		Bindi bindi4 = new Bindi();
		bindi4.id = 4;
		bindi4.brand = "Lakme";
		bindi4.price = 55;
		bindi4.colour = "Red";
		bindi4.shape = "Round";
		bindi4.size = "Medium";
		bindi4.material = "Sticker";
		bindi4.type = "Party";
		System.out.println("bindi id is " + bindi4.id);
		System.out.println("brand is " + bindi4.brand);
		System.out.println("price is " + bindi4.price);
		System.out.println("colour is " + bindi4.colour);
		System.out.println("shape is " + bindi4.shape);
		System.out.println("size is " + bindi4.size);
		System.out.println("material is " + bindi4.material);
		System.out.println("type is " + bindi4.type);
		System.out.println("----------------------");

		Bindi bindi5 = new Bindi();
		bindi5.id = 5;
		bindi5.brand = "Elle18";
		bindi5.price = 65;
		bindi5.colour = "Black";
		bindi5.shape = "Oval";
		bindi5.size = "Small";
		bindi5.material = "Sticker";
		bindi5.type = "Daily";
		System.out.println("bindi id is " + bindi5.id);
		System.out.println("brand is " + bindi5.brand);
		System.out.println("price is " + bindi5.price);
		System.out.println("colour is " + bindi5.colour);
		System.out.println("shape is " + bindi5.shape);
		System.out.println("size is " + bindi5.size);
		System.out.println("material is " + bindi5.material);
		System.out.println("type is " + bindi5.type);
		System.out.println("----------------------");

		Bindi bindi6 = new Bindi();
		bindi6.id = 6;
		bindi6.brand = "BlueHeaven";
		bindi6.price = 40;
		bindi6.colour = "Green";
		bindi6.shape = "Round";
		bindi6.size = "Small";
		bindi6.material = "Sticker";
		bindi6.type = "Daily";
		System.out.println("bindi id is " + bindi6.id);
		System.out.println("brand is " + bindi6.brand);
		System.out.println("price is " + bindi6.price);
		System.out.println("colour is " + bindi6.colour);
		System.out.println("shape is " + bindi6.shape);
		System.out.println("size is " + bindi6.size);
		System.out.println("material is " + bindi6.material);
		System.out.println("type is " + bindi6.type);
		System.out.println("----------------------");

		Bindi bindi7 = new Bindi();
		bindi7.id = 7;
		bindi7.brand = "Lakme";
		bindi7.price = 70;
		bindi7.colour = "Maroon";
		bindi7.shape = "Designer";
		bindi7.size = "Large";
		bindi7.material = "Velvet";
		bindi7.type = "Party";
		System.out.println("bindi id is " + bindi7.id);
		System.out.println("brand is " + bindi7.brand);
		System.out.println("price is " + bindi7.price);
		System.out.println("colour is " + bindi7.colour);
		System.out.println("shape is " + bindi7.shape);
		System.out.println("size is " + bindi7.size);
		System.out.println("material is " + bindi7.material);
		System.out.println("type is " + bindi7.type);
		System.out.println("----------------------");

		Bindi bindi8 = new Bindi();
		bindi8.id = 8;
		bindi8.brand = "Elle18";
		bindi8.price = 80;
		bindi8.colour = "Red";
		bindi8.shape = "Round";
		bindi8.size = "Large";
		bindi8.material = "Velvet";
		bindi8.type = "Wedding";
		System.out.println("bindi id is " + bindi8.id);
		System.out.println("brand is " + bindi8.brand);
		System.out.println("price is " + bindi8.price);
		System.out.println("colour is " + bindi8.colour);
		System.out.println("shape is " + bindi8.shape);
		System.out.println("size is " + bindi8.size);
		System.out.println("material is " + bindi8.material);
		System.out.println("type is " + bindi8.type);
		System.out.println("----------------------");
		
		Bindi bindi9 = new Bindi();
		bindi9.id = 9;
		bindi9.brand = "BlueHeaven";
		bindi9.price = 50;
		bindi9.colour = "Black";
		bindi9.shape = "Round";
		bindi9.size = "Medium";
		bindi9.material = "Sticker";
		bindi9.type = "Daily";
		System.out.println("bindi id is " + bindi9.id);
		System.out.println("brand is " + bindi9.brand);
		System.out.println("price is " + bindi9.price);
		System.out.println("colour is " + bindi9.colour);
		System.out.println("shape is " + bindi9.shape);
		System.out.println("size is " + bindi9.size);
		System.out.println("material is " + bindi9.material);
		System.out.println("type is " + bindi9.type);
		System.out.println("----------------------");

		Bindi bindi10 = new Bindi();
		bindi10.id = 10;
		bindi10.brand = "Lakme";
		bindi10.price = 90;
		bindi10.colour = "Red";
		bindi10.shape = "Designer";
		bindi10.size = "Large";
		bindi10.material = "Stone";
		bindi10.type = "Wedding";
		System.out.println("bindi id is " + bindi10.id);
		System.out.println("brand is " + bindi10.brand);
		System.out.println("price is " + bindi10.price);
		System.out.println("colour is " + bindi10.colour);
		System.out.println("shape is " + bindi10.shape);
		System.out.println("size is " + bindi10.size);
		System.out.println("material is " + bindi10.material);
		System.out.println("type is " + bindi10.type);
		System.out.println("----------------------");
		
		Bindi bindi11 = new Bindi();
		bindi11.id = 11;
		bindi11.brand = "Elle18";
		bindi11.price = 55;
		bindi11.colour = "Black";
		bindi11.shape = "Round";
		bindi11.size = "Small";
		bindi11.material = "Sticker";
		bindi11.type = "Daily";
		System.out.println("bindi id is " + bindi11.id);
		System.out.println("brand is " + bindi11.brand);
		System.out.println("price is " + bindi11.price);
		System.out.println("colour is " + bindi11.colour);
		System.out.println("shape is " + bindi11.shape);
		System.out.println("size is " + bindi11.size);
		System.out.println("material is " + bindi11.material);
		System.out.println("type is " + bindi11.type);
		System.out.println("----------------------");

		Bindi bindi12 = new Bindi();
		bindi12.id = 12;
		bindi12.brand = "Lakme";
		bindi12.price = 65;
		bindi12.colour = "Red";
		bindi12.shape = "Oval";
		bindi12.size = "Medium";
		bindi12.material = "Sticker";
		bindi12.type = "Daily";
		System.out.println("bindi id is " + bindi12.id);
		System.out.println("brand is " + bindi12.brand);
		System.out.println("price is " + bindi12.price);
		System.out.println("colour is " + bindi12.colour);
		System.out.println("shape is " + bindi12.shape);
		System.out.println("size is " + bindi12.size);
		System.out.println("material is " + bindi12.material);
		System.out.println("type is " + bindi12.type);
		System.out.println("----------------------");

		Bindi bindi13 = new Bindi();
		bindi13.id = 13;
		bindi13.brand = "BlueHeaven";
		bindi13.price = 45;
		bindi13.colour = "Green";
		bindi13.shape = "Round";
		bindi13.size = "Small";
		bindi13.material = "Sticker";
		bindi13.type = "Daily";
		System.out.println("bindi id is " + bindi13.id);
		System.out.println("brand is " + bindi13.brand);
		System.out.println("price is " + bindi13.price);
		System.out.println("colour is " + bindi13.colour);
		System.out.println("shape is " + bindi13.shape);
		System.out.println("size is " + bindi13.size);
		System.out.println("material is " + bindi13.material);
		System.out.println("type is " + bindi13.type);
		System.out.println("----------------------");

		Bindi bindi14 = new Bindi();
		bindi14.id = 14;
		bindi14.brand = "Lakme";
		bindi14.price = 75;
		bindi14.colour = "Maroon";
		bindi14.shape = "Designer";
		bindi14.size = "Large";
		bindi14.material = "Velvet";
		bindi14.type = "Party";
		System.out.println("bindi id is " + bindi14.id);
		System.out.println("brand is " + bindi14.brand);
		System.out.println("price is " + bindi14.price);
		System.out.println("colour is " + bindi14.colour);
		System.out.println("shape is " + bindi14.shape);
		System.out.println("size is " + bindi14.size);
		System.out.println("material is " + bindi14.material);
		System.out.println("type is " + bindi14.type);
		System.out.println("----------------------");

		Bindi bindi15 = new Bindi();
		bindi15.id = 15;
		bindi15.brand = "Elle18";
		bindi15.price = 80;
		bindi15.colour = "Red";
		bindi15.shape = "Round";
		bindi15.size = "Large";
		bindi15.material = "Velvet";
		bindi15.type = "Wedding";
		System.out.println("bindi id is " + bindi15.id);
		System.out.println("brand is " + bindi15.brand);
		System.out.println("price is " + bindi15.price);
		System.out.println("colour is " + bindi15.colour);
		System.out.println("shape is " + bindi15.shape);
		System.out.println("size is " + bindi15.size);
		System.out.println("material is " + bindi15.material);
		System.out.println("type is " + bindi15.type);
		System.out.println("----------------------");

		Bindi bindi16 = new Bindi();
		bindi16.id = 16;
		bindi16.brand = "BlueHeaven";
		bindi16.price = 50;
		bindi16.colour = "Black";
		bindi16.shape = "Round";
		bindi16.size = "Medium";
		bindi16.material = "Sticker";
		bindi16.type = "Daily";
		System.out.println("bindi id is " + bindi16.id);
		System.out.println("brand is " + bindi16.brand);
		System.out.println("price is " + bindi16.price);
		System.out.println("colour is " + bindi16.colour);
		System.out.println("shape is " + bindi16.shape);
		System.out.println("size is " + bindi16.size);
		System.out.println("material is " + bindi16.material);
		System.out.println("type is " + bindi16.type);
		System.out.println("----------------------");

		Bindi bindi17 = new Bindi();
		bindi17.id = 17;
		bindi17.brand = "Lakme";
		bindi17.price = 95;
		bindi17.colour = "Red";
		bindi17.shape = "Designer";
		bindi17.size = "Large";
		bindi17.material = "Stone";
		bindi17.type = "Wedding";
		System.out.println("bindi id is " + bindi17.id);
		System.out.println("brand is " + bindi17.brand);
		System.out.println("price is " + bindi17.price);
		System.out.println("colour is " + bindi17.colour);
		System.out.println("shape is " + bindi17.shape);
		System.out.println("size is " + bindi17.size);
		System.out.println("material is " + bindi17.material);
		System.out.println("type is " + bindi17.type);
		System.out.println("----------------------");

		Bindi bindi18 = new Bindi();
		bindi18.id = 18;
		bindi18.brand = "Elle18";
		bindi18.price = 60;
		bindi18.colour = "Black";
		bindi18.shape = "Oval";
		bindi18.size = "Medium";
		bindi18.material = "Sticker";
		bindi18.type = "Daily";
		System.out.println("bindi id is " + bindi18.id);
		System.out.println("brand is " + bindi18.brand);
		System.out.println("price is " + bindi18.price);
		System.out.println("colour is " + bindi18.colour);
		System.out.println("shape is " + bindi18.shape);
		System.out.println("size is " + bindi18.size);
		System.out.println("material is " + bindi18.material);
		System.out.println("type is " + bindi18.type);
		System.out.println("----------------------");
		
		Bindi bindi19 = new Bindi();
		bindi19.id = 19;
		bindi19.brand = "BlueHeaven";
		bindi19.price = 55;
		bindi19.colour = "Green";
		bindi19.shape = "Round";
		bindi19.size = "Small";
		bindi19.material = "Sticker";
		bindi19.type = "Daily";
		System.out.println("bindi id is " + bindi19.id);
		System.out.println("brand is " + bindi19.brand);
		System.out.println("price is " + bindi19.price);
		System.out.println("colour is " + bindi19.colour);
		System.out.println("shape is " + bindi19.shape);
		System.out.println("size is " + bindi19.size);
		System.out.println("material is " + bindi19.material);
		System.out.println("type is " + bindi19.type);
		System.out.println("----------------------");

		Bindi bindi20 = new Bindi();
		bindi20.id = 20;
		bindi20.brand = "Lakme";
		bindi20.price = 85;
		bindi20.colour = "Maroon";
		bindi20.shape = "Designer";
		bindi20.size = "Large";
		bindi20.material = "Velvet";
		bindi20.type = "Party";
		System.out.println("bindi id is " + bindi20.id);
		System.out.println("brand is " + bindi20.brand);
		System.out.println("price is " + bindi20.price);
		System.out.println("colour is " + bindi20.colour);
		System.out.println("shape is " + bindi20.shape);
		System.out.println("size is " + bindi20.size);
		System.out.println("material is " + bindi20.material);
		System.out.println("type is " + bindi20.type);
		System.out.println("----------------------");
		
		Bindi bindi21 = new Bindi();
		bindi21.id = 21;
		bindi21.brand = "Elle18";
		bindi21.price = 60;
		bindi21.colour = "Black";
		bindi21.shape = "Round";
		bindi21.size = "Small";
		bindi21.material = "Sticker";
		bindi21.type = "Daily";
		System.out.println("bindi id is " + bindi21.id);
		System.out.println("brand is " + bindi21.brand);
		System.out.println("price is " + bindi21.price);
		System.out.println("colour is " + bindi21.colour);
		System.out.println("shape is " + bindi21.shape);
		System.out.println("size is " + bindi21.size);
		System.out.println("material is " + bindi21.material);
		System.out.println("type is " + bindi21.type);
		System.out.println("----------------------");

		Bindi bindi22 = new Bindi();
		bindi22.id = 22;
		bindi22.brand = "Lakme";
		bindi22.price = 70;
		bindi22.colour = "Red";
		bindi22.shape = "Oval";
		bindi22.size = "Medium";
		bindi22.material = "Sticker";
		bindi22.type = "Daily";
		System.out.println("bindi id is " + bindi22.id);
		System.out.println("brand is " + bindi22.brand);
		System.out.println("price is " + bindi22.price);
		System.out.println("colour is " + bindi22.colour);
		System.out.println("shape is " + bindi22.shape);
		System.out.println("size is " + bindi22.size);
		System.out.println("material is " + bindi22.material);
		System.out.println("type is " + bindi22.type);
		System.out.println("----------------------");

		Bindi bindi23 = new Bindi();
		bindi23.id = 23;
		bindi23.brand = "BlueHeaven";
		bindi23.price = 50;
		bindi23.colour = "Green";
		bindi23.shape = "Round";
		bindi23.size = "Small";
		bindi23.material = "Sticker";
		bindi23.type = "Daily";
		System.out.println("bindi id is " + bindi23.id);
		System.out.println("brand is " + bindi23.brand);
		System.out.println("price is " + bindi23.price);
		System.out.println("colour is " + bindi23.colour);
		System.out.println("shape is " + bindi23.shape);
		System.out.println("size is " + bindi23.size);
		System.out.println("material is " + bindi23.material);
		System.out.println("type is " + bindi23.type);
		System.out.println("----------------------");

		Bindi bindi24 = new Bindi();
		bindi24.id = 24;
		bindi24.brand = "Lakme";
		bindi24.price = 90;
		bindi24.colour = "Maroon";
		bindi24.shape = "Designer";
		bindi24.size = "Large";
		bindi24.material = "Stone";
		bindi24.type = "Wedding";
		System.out.println("bindi id is " + bindi24.id);
		System.out.println("brand is " + bindi24.brand);
		System.out.println("price is " + bindi24.price);
		System.out.println("colour is " + bindi24.colour);
		System.out.println("shape is " + bindi24.shape);
		System.out.println("size is " + bindi24.size);
		System.out.println("material is " + bindi24.material);
		System.out.println("type is " + bindi24.type);
		System.out.println("----------------------");

		Bindi bindi25 = new Bindi();
		bindi25.id = 25;
		bindi25.brand = "Elle18";
		bindi25.price = 85;
		bindi25.colour = "Red";
		bindi25.shape = "Round";
		bindi25.size = "Large";
		bindi25.material = "Velvet";
		bindi25.type = "Wedding";
		System.out.println("bindi id is " + bindi25.id);
		System.out.println("brand is " + bindi25.brand);
		System.out.println("price is " + bindi25.price);
		System.out.println("colour is " + bindi25.colour);
		System.out.println("shape is " + bindi25.shape);
		System.out.println("size is " + bindi25.size);
		System.out.println("material is " + bindi25.material);
		System.out.println("type is " + bindi25.type);
		System.out.println("----------------------");

		Bindi bindi26 = new Bindi();
		bindi26.id = 26;
		bindi26.brand = "BlueHeaven";
		bindi26.price = 55;
		bindi26.colour = "Black";
		bindi26.shape = "Round";
		bindi26.size = "Medium";
		bindi26.material = "Sticker";
		bindi26.type = "Daily";
		System.out.println("bindi id is " + bindi26.id);
		System.out.println("brand is " + bindi26.brand);
		System.out.println("price is " + bindi26.price);
		System.out.println("colour is " + bindi26.colour);
		System.out.println("shape is " + bindi26.shape);
		System.out.println("size is " + bindi26.size);
		System.out.println("material is " + bindi26.material);
		System.out.println("type is " + bindi26.type);
		System.out.println("----------------------");

		Bindi bindi27 = new Bindi();
		bindi27.id = 27;
		bindi27.brand = "Lakme";
		bindi27.price = 95;
		bindi27.colour = "Red";
		bindi27.shape = "Designer";
		bindi27.size = "Large";
		bindi27.material = "Stone";
		bindi27.type = "Wedding";
		System.out.println("bindi id is " + bindi27.id);
		System.out.println("brand is " + bindi27.brand);
		System.out.println("price is " + bindi27.price);
		System.out.println("colour is " + bindi27.colour);
		System.out.println("shape is " + bindi27.shape);
		System.out.println("size is " + bindi27.size);
		System.out.println("material is " + bindi27.material);
		System.out.println("type is " + bindi27.type);
		System.out.println("----------------------");

		Bindi bindi28 = new Bindi();
		bindi28.id = 28;
		bindi28.brand = "Elle18";
		bindi28.price = 65;
		bindi28.colour = "Black";
		bindi28.shape = "Oval";
		bindi28.size = "Medium";
		bindi28.material = "Sticker";
		bindi28.type = "Daily";
		System.out.println("bindi id is " + bindi28.id);
		System.out.println("brand is " + bindi28.brand);
		System.out.println("price is " + bindi28.price);
		System.out.println("colour is " + bindi28.colour);
		System.out.println("shape is " + bindi28.shape);
		System.out.println("size is " + bindi28.size);
		System.out.println("material is " + bindi28.material);
		System.out.println("type is " + bindi28.type);
		System.out.println("----------------------");

		Bindi bindi29 = new Bindi();
		bindi29.id = 29;
		bindi29.brand = "BlueHeaven";
		bindi29.price = 50;
		bindi29.colour = "Green";
		bindi29.shape = "Round";
		bindi29.size = "Small";
		bindi29.material = "Sticker";
		bindi29.type = "Daily";
		System.out.println("bindi id is " + bindi29.id);
		System.out.println("brand is " + bindi29.brand);
		System.out.println("price is " + bindi29.price);
		System.out.println("colour is " + bindi29.colour);
		System.out.println("shape is " + bindi29.shape);
		System.out.println("size is " + bindi29.size);
		System.out.println("material is " + bindi29.material);
		System.out.println("type is " + bindi29.type);
		System.out.println("----------------------");

		Bindi bindi30 = new Bindi();
		bindi30.id = 30;
		bindi30.brand = "Lakme";
		bindi30.price = 100;
		bindi30.colour = "Maroon";
		bindi30.shape = "Designer";
		bindi30.size = "Large";
		bindi30.material = "Stone";
		bindi30.type = "Wedding";
		System.out.println("bindi id is " + bindi30.id);
		System.out.println("brand is " + bindi30.brand);
		System.out.println("price is " + bindi30.price);
		System.out.println("colour is " + bindi30.colour);
		System.out.println("shape is " + bindi30.shape);
		System.out.println("size is " + bindi30.size);
		System.out.println("material is " + bindi30.material);
		System.out.println("type is " + bindi30.type);
		System.out.println("----------------------");
	}
}