class GoggleExecuter{
	public static void main(String[] args){

		Goggle goggle1 = new Goggle();
		goggle1.id = 1;
		goggle1.brand = "RayBan";
		goggle1.price = 3500;
		goggle1.colour = "Black";
		goggle1.lensType = "UV";
		goggle1.frameMaterial = "Metal";
		goggle1.size = "Medium";
		goggle1.gender = "Unisex";
		System.out.println("goggle id is " + goggle1.id);
		System.out.println("brand is " + goggle1.brand);
		System.out.println("price is " + goggle1.price);
		System.out.println("colour is " + goggle1.colour);
		System.out.println("lens type is " + goggle1.lensType);
		System.out.println("frame material is " + goggle1.frameMaterial);
		System.out.println("size is " + goggle1.size);
		System.out.println("gender is " + goggle1.gender);
		System.out.println("----------------------");

		Goggle goggle2 = new Goggle();
		goggle2.id = 2;
		goggle2.brand = "Fastrack";
		goggle2.price = 1800;
		goggle2.colour = "Brown";
		goggle2.lensType = "Polarized";
		goggle2.frameMaterial = "Plastic";
		goggle2.size = "Large";
		goggle2.gender = "Men";
		System.out.println("goggle id is " + goggle2.id);
		System.out.println("brand is " + goggle2.brand);
		System.out.println("price is " + goggle2.price);
		System.out.println("colour is " + goggle2.colour);
		System.out.println("lens type is " + goggle2.lensType);
		System.out.println("frame material is " + goggle2.frameMaterial);
		System.out.println("size is " + goggle2.size);
		System.out.println("gender is " + goggle2.gender);
		System.out.println("----------------------");

		Goggle goggle3 = new Goggle();
		goggle3.id = 3;
		goggle3.brand = "Oakley";
		goggle3.price = 4200;
		goggle3.colour = "Grey";
		goggle3.lensType = "UV";
		goggle3.frameMaterial = "Fiber";
		goggle3.size = "Medium";
		goggle3.gender = "Unisex";
		System.out.println("goggle id is " + goggle3.id);
		System.out.println("brand is " + goggle3.brand);
		System.out.println("price is " + goggle3.price);
		System.out.println("colour is " + goggle3.colour);
		System.out.println("lens type is " + goggle3.lensType);
		System.out.println("frame material is " + goggle3.frameMaterial);
		System.out.println("size is " + goggle3.size);
		System.out.println("gender is " + goggle3.gender);
		System.out.println("----------------------");

		Goggle goggle4 = new Goggle();
		goggle4.id = 4;
		goggle4.brand = "RayBan";
		goggle4.price = 3900;
		goggle4.colour = "Green";
		goggle4.lensType = "Polarized";
		goggle4.frameMaterial = "Metal";
		goggle4.size = "Large";
		goggle4.gender = "Women";
		System.out.println("goggle id is " + goggle4.id);
		System.out.println("brand is " + goggle4.brand);
		System.out.println("price is " + goggle4.price);
		System.out.println("colour is " + goggle4.colour);
		System.out.println("lens type is " + goggle4.lensType);
		System.out.println("frame material is " + goggle4.frameMaterial);
		System.out.println("size is " + goggle4.size);
		System.out.println("gender is " + goggle4.gender);
		System.out.println("----------------------");

		Goggle goggle5 = new Goggle();
		goggle5.id = 5;
		goggle5.brand = "Fastrack";
		goggle5.price = 1600;
		goggle5.colour = "Black";
		goggle5.lensType = "UV";
		goggle5.frameMaterial = "Plastic";
		goggle5.size = "Medium";
		goggle5.gender = "Men";
		System.out.println("goggle id is " + goggle5.id);
		System.out.println("brand is " + goggle5.brand);
		System.out.println("price is " + goggle5.price);
		System.out.println("colour is " + goggle5.colour);
		System.out.println("lens type is " + goggle5.lensType);
		System.out.println("frame material is " + goggle5.frameMaterial);
		System.out.println("size is " + goggle5.size);
		System.out.println("gender is " + goggle5.gender);
		System.out.println("----------------------");
		
		Goggle goggle6 = new Goggle();
		goggle6.id = 6;
		goggle6.brand = "Oakley";
		goggle6.price = 4100;
		goggle6.colour = "Blue";
		goggle6.lensType = "Polarized";
		goggle6.frameMaterial = "Fiber";
		goggle6.size = "Large";
		goggle6.gender = "Unisex";
		System.out.println("goggle id is " + goggle6.id);
		System.out.println("brand is " + goggle6.brand);
		System.out.println("price is " + goggle6.price);
		System.out.println("colour is " + goggle6.colour);
		System.out.println("lens type is " + goggle6.lensType);
		System.out.println("frame material is " + goggle6.frameMaterial);
		System.out.println("size is " + goggle6.size);
		System.out.println("gender is " + goggle6.gender);
		System.out.println("----------------------");

		Goggle goggle7 = new Goggle();
		goggle7.id = 7;
		goggle7.brand = "RayBan";
		goggle7.price = 3600;
		goggle7.colour = "Brown";
		goggle7.lensType = "UV";
		goggle7.frameMaterial = "Metal";
		goggle7.size = "Medium";
		goggle7.gender = "Men";
		System.out.println("goggle id is " + goggle7.id);
		System.out.println("brand is " + goggle7.brand);
		System.out.println("price is " + goggle7.price);
		System.out.println("colour is " + goggle7.colour);
		System.out.println("lens type is " + goggle7.lensType);
		System.out.println("frame material is " + goggle7.frameMaterial);
		System.out.println("size is " + goggle7.size);
		System.out.println("gender is " + goggle7.gender);
		System.out.println("----------------------");

		Goggle goggle8 = new Goggle();
		goggle8.id = 8;
		goggle8.brand = "Fastrack";
		goggle8.price = 1700;
		goggle8.colour = "Grey";
		goggle8.lensType = "Polarized";
		goggle8.frameMaterial = "Plastic";
		goggle8.size = "Medium";
		goggle8.gender = "Women";
		System.out.println("goggle id is " + goggle8.id);
		System.out.println("brand is " + goggle8.brand);
		System.out.println("price is " + goggle8.price);
		System.out.println("colour is " + goggle8.colour);
		System.out.println("lens type is " + goggle8.lensType);
		System.out.println("frame material is " + goggle8.frameMaterial);
		System.out.println("size is " + goggle8.size);
		System.out.println("gender is " + goggle8.gender);
		System.out.println("----------------------");

		Goggle goggle9 = new Goggle();
		goggle9.id = 9;
		goggle9.brand = "Oakley";
		goggle9.price = 4300;
		goggle9.colour = "Black";
		goggle9.lensType = "UV";
		goggle9.frameMaterial = "Fiber";
		goggle9.size = "Large";
		goggle9.gender = "Unisex";
		System.out.println("goggle id is " + goggle9.id);
		System.out.println("brand is " + goggle9.brand);
		System.out.println("price is " + goggle9.price);
		System.out.println("colour is " + goggle9.colour);
		System.out.println("lens type is " + goggle9.lensType);
		System.out.println("frame material is " + goggle9.frameMaterial);
		System.out.println("size is " + goggle9.size);
		System.out.println("gender is " + goggle9.gender);
		System.out.println("----------------------");

		Goggle goggle10 = new Goggle();
		goggle10.id = 10;
		goggle10.brand = "RayBan";
		goggle10.price = 3800;
		goggle10.colour = "Green";
		goggle10.lensType = "Polarized";
		goggle10.frameMaterial = "Metal";
		goggle10.size = "Large";
		goggle10.gender = "Women";
		System.out.println("goggle id is " + goggle10.id);
		System.out.println("brand is " + goggle10.brand);
		System.out.println("price is " + goggle10.price);
		System.out.println("colour is " + goggle10.colour);
		System.out.println("lens type is " + goggle10.lensType);
		System.out.println("frame material is " + goggle10.frameMaterial);
		System.out.println("size is " + goggle10.size);
		System.out.println("gender is " + goggle10.gender);
		System.out.println("----------------------");

		Goggle goggle11 = new Goggle();
		goggle11.id = 11;
		goggle11.brand = "Fastrack";
		goggle11.price = 1500;
		goggle11.colour = "Black";
		goggle11.lensType = "UV";
		goggle11.frameMaterial = "Plastic";
		goggle11.size = "Medium";
		goggle11.gender = "Men";
		System.out.println("goggle id is " + goggle11.id);
		System.out.println("brand is " + goggle11.brand);
		System.out.println("price is " + goggle11.price);
		System.out.println("colour is " + goggle11.colour);
		System.out.println("lens type is " + goggle11.lensType);
		System.out.println("frame material is " + goggle11.frameMaterial);
		System.out.println("size is " + goggle11.size);
		System.out.println("gender is " + goggle11.gender);
		System.out.println("----------------------");

		Goggle goggle12 = new Goggle();
		goggle12.id = 12;
		goggle12.brand = "Oakley";
		goggle12.price = 4400;
		goggle12.colour = "Blue";
		goggle12.lensType = "Polarized";
		goggle12.frameMaterial = "Fiber";
		goggle12.size = "Large";
		goggle12.gender = "Unisex";
		System.out.println("goggle id is " + goggle12.id);
		System.out.println("brand is " + goggle12.brand);
		System.out.println("price is " + goggle12.price);
		System.out.println("colour is " + goggle12.colour);
		System.out.println("lens type is " + goggle12.lensType);
		System.out.println("frame material is " + goggle12.frameMaterial);
		System.out.println("size is " + goggle12.size);
		System.out.println("gender is " + goggle12.gender);
		System.out.println("----------------------");

		Goggle goggle13 = new Goggle();
		goggle13.id = 13;
		goggle13.brand = "RayBan";
		goggle13.price = 3700;
		goggle13.colour = "Brown";
		goggle13.lensType = "UV";
		goggle13.frameMaterial = "Metal";
		goggle13.size = "Medium";
		goggle13.gender = "Men";
		System.out.println("goggle id is " + goggle13.id);
		System.out.println("brand is " + goggle13.brand);
		System.out.println("price is " + goggle13.price);
		System.out.println("colour is " + goggle13.colour);
		System.out.println("lens type is " + goggle13.lensType);
		System.out.println("frame material is " + goggle13.frameMaterial);
		System.out.println("size is " + goggle13.size);
		System.out.println("gender is " + goggle13.gender);
		System.out.println("----------------------");

		Goggle goggle14 = new Goggle();
		goggle14.id = 14;
		goggle14.brand = "Fastrack";
		goggle14.price = 1750;
		goggle14.colour = "Grey";
		goggle14.lensType = "Polarized";
		goggle14.frameMaterial = "Plastic";
		goggle14.size = "Medium";
		goggle14.gender = "Women";
		System.out.println("goggle id is " + goggle14.id);
		System.out.println("brand is " + goggle14.brand);
		System.out.println("price is " + goggle14.price);
		System.out.println("colour is " + goggle14.colour);
		System.out.println("lens type is " + goggle14.lensType);
		System.out.println("frame material is " + goggle14.frameMaterial);
		System.out.println("size is " + goggle14.size);
		System.out.println("gender is " + goggle14.gender);
		System.out.println("----------------------");

		Goggle goggle15 = new Goggle();
		goggle15.id = 15;
		goggle15.brand = "Oakley";
		goggle15.price = 4500;
		goggle15.colour = "Black";
		goggle15.lensType = "UV";
		goggle15.frameMaterial = "Fiber";
		goggle15.size = "Large";
		goggle15.gender = "Unisex";
		System.out.println("goggle id is " + goggle15.id);
		System.out.println("brand is " + goggle15.brand);
		System.out.println("price is " + goggle15.price);
		System.out.println("colour is " + goggle15.colour);
		System.out.println("lens type is " + goggle15.lensType);
		System.out.println("frame material is " + goggle15.frameMaterial);
		System.out.println("size is " + goggle15.size);
		System.out.println("gender is " + goggle15.gender);
		System.out.println("----------------------");

		Goggle goggle16 = new Goggle();
		goggle16.id = 16;
		goggle16.brand = "RayBan";
		goggle16.price = 3900;
		goggle16.colour = "Green";
		goggle16.lensType = "Polarized";
		goggle16.frameMaterial = "Metal";
		goggle16.size = "Large";
		goggle16.gender = "Women";
		System.out.println("goggle id is " + goggle16.id);
		System.out.println("brand is " + goggle16.brand);
		System.out.println("price is " + goggle16.price);
		System.out.println("colour is " + goggle16.colour);
		System.out.println("lens type is " + goggle16.lensType);
		System.out.println("frame material is " + goggle16.frameMaterial);
		System.out.println("size is " + goggle16.size);
		System.out.println("gender is " + goggle16.gender);
		System.out.println("----------------------");

		Goggle goggle17 = new Goggle();
		goggle17.id = 17;
		goggle17.brand = "Fastrack";
		goggle17.price = 1650;
		goggle17.colour = "Black";
		goggle17.lensType = "UV";
		goggle17.frameMaterial = "Plastic";
		goggle17.size = "Medium";
		goggle17.gender = "Men";
		System.out.println("goggle id is " + goggle17.id);
		System.out.println("brand is " + goggle17.brand);
		System.out.println("price is " + goggle17.price);
		System.out.println("colour is " + goggle17.colour);
		System.out.println("lens type is " + goggle17.lensType);
		System.out.println("frame material is " + goggle17.frameMaterial);
		System.out.println("size is " + goggle17.size);
		System.out.println("gender is " + goggle17.gender);
		System.out.println("----------------------");

		Goggle goggle18 = new Goggle();
		goggle18.id = 18;
		goggle18.brand = "Oakley";
		goggle18.price = 4600;
		goggle18.colour = "Blue";
		goggle18.lensType = "Polarized";
		goggle18.frameMaterial = "Fiber";
		goggle18.size = "Large";
		goggle18.gender = "Unisex";
		System.out.println("goggle id is " + goggle18.id);
		System.out.println("brand is " + goggle18.brand);
		System.out.println("price is " + goggle18.price);
		System.out.println("colour is " + goggle18.colour);
		System.out.println("lens type is " + goggle18.lensType);
		System.out.println("frame material is " + goggle18.frameMaterial);
		System.out.println("size is " + goggle18.size);
		System.out.println("gender is " + goggle18.gender);
		System.out.println("----------------------");

		Goggle goggle19 = new Goggle();
		goggle19.id = 19;
		goggle19.brand = "RayBan";
		goggle19.price = 4000;
		goggle19.colour = "Brown";
		goggle19.lensType = "UV";
		goggle19.frameMaterial = "Metal";
		goggle19.size = "Medium";
		goggle19.gender = "Men";
		System.out.println("goggle id is " + goggle19.id);
		System.out.println("brand is " + goggle19.brand);
		System.out.println("price is " + goggle19.price);
		System.out.println("colour is " + goggle19.colour);
		System.out.println("lens type is " + goggle19.lensType);
		System.out.println("frame material is " + goggle19.frameMaterial);
		System.out.println("size is " + goggle19.size);
		System.out.println("gender is " + goggle19.gender);
		System.out.println("----------------------");

		Goggle goggle20 = new Goggle();
		goggle20.id = 20;
		goggle20.brand = "Fastrack";
		goggle20.price = 1800;
		goggle20.colour = "Grey";
		goggle20.lensType = "Polarized";
		goggle20.frameMaterial = "Plastic";
		goggle20.size = "Medium";
		goggle20.gender = "Women";
		System.out.println("goggle id is " + goggle20.id);
		System.out.println("brand is " + goggle20.brand);
		System.out.println("price is " + goggle20.price);
		System.out.println("colour is " + goggle20.colour);
		System.out.println("lens type is " + goggle20.lensType);
		System.out.println("frame material is " + goggle20.frameMaterial);
		System.out.println("size is " + goggle20.size);
		System.out.println("gender is " + goggle20.gender);
		System.out.println("----------------------");

		Goggle goggle21 = new Goggle();
		goggle21.id = 21;
		goggle21.brand = "Oakley";
		goggle21.price = 4700;
		goggle21.colour = "Black";
		goggle21.lensType = "UV";
		goggle21.frameMaterial = "Fiber";
		goggle21.size = "Large";
		goggle21.gender = "Unisex";
		System.out.println("goggle id is " + goggle21.id);
		System.out.println("brand is " + goggle21.brand);
		System.out.println("price is " + goggle21.price);
		System.out.println("colour is " + goggle21.colour);
		System.out.println("lens type is " + goggle21.lensType);
		System.out.println("frame material is " + goggle21.frameMaterial);
		System.out.println("size is " + goggle21.size);
		System.out.println("gender is " + goggle21.gender);
		System.out.println("----------------------");

		Goggle goggle22 = new Goggle();
		goggle22.id = 22;
		goggle22.brand = "RayBan";
		goggle22.price = 4100;
		goggle22.colour = "Green";
		goggle22.lensType = "Polarized";
		goggle22.frameMaterial = "Metal";
		goggle22.size = "Large";
		goggle22.gender = "Women";
		System.out.println("goggle id is " + goggle22.id);
		System.out.println("brand is " + goggle22.brand);
		System.out.println("price is " + goggle22.price);
		System.out.println("colour is " + goggle22.colour);
		System.out.println("lens type is " + goggle22.lensType);
		System.out.println("frame material is " + goggle22.frameMaterial);
		System.out.println("size is " + goggle22.size);
		System.out.println("gender is " + goggle22.gender);
		System.out.println("----------------------");

		Goggle goggle23 = new Goggle();
		goggle23.id = 23;
		goggle23.brand = "Fastrack";
		goggle23.price = 1700;
		goggle23.colour = "Black";
		goggle23.lensType = "UV";
		goggle23.frameMaterial = "Plastic";
		goggle23.size = "Medium";
		goggle23.gender = "Men";
		System.out.println("goggle id is " + goggle23.id);
		System.out.println("brand is " + goggle23.brand);
		System.out.println("price is " + goggle23.price);
		System.out.println("colour is " + goggle23.colour);
		System.out.println("lens type is " + goggle23.lensType);
		System.out.println("frame material is " + goggle23.frameMaterial);
		System.out.println("size is " + goggle23.size);
		System.out.println("gender is " + goggle23.gender);
		System.out.println("----------------------");

		Goggle goggle24 = new Goggle();
		goggle24.id = 24;
		goggle24.brand = "Oakley";
		goggle24.price = 4800;
		goggle24.colour = "Blue";
		goggle24.lensType = "Polarized";
		goggle24.frameMaterial = "Fiber";
		goggle24.size = "Large";
		goggle24.gender = "Unisex";
		System.out.println("goggle id is " + goggle24.id);
		System.out.println("brand is " + goggle24.brand);
		System.out.println("price is " + goggle24.price);
		System.out.println("colour is " + goggle24.colour);
		System.out.println("lens type is " + goggle24.lensType);
		System.out.println("frame material is " + goggle24.frameMaterial);
		System.out.println("size is " + goggle24.size);
		System.out.println("gender is " + goggle24.gender);
		System.out.println("----------------------");

		Goggle goggle25 = new Goggle();
		goggle25.id = 25;
		goggle25.brand = "RayBan";
		goggle25.price = 4200;
		goggle25.colour = "Brown";
		goggle25.lensType = "UV";
		goggle25.frameMaterial = "Metal";
		goggle25.size = "Medium";
		goggle25.gender = "Men";
		System.out.println("goggle id is " + goggle25.id);
		System.out.println("brand is " + goggle25.brand);
		System.out.println("price is " + goggle25.price);
		System.out.println("colour is " + goggle25.colour);
		System.out.println("lens type is " + goggle25.lensType);
		System.out.println("frame material is " + goggle25.frameMaterial);
		System.out.println("size is " + goggle25.size);
		System.out.println("gender is " + goggle25.gender);
		System.out.println("----------------------");

		Goggle goggle26 = new Goggle();
		goggle26.id = 26;
		goggle26.brand = "Fastrack";
		goggle26.price = 1850;
		goggle26.colour = "Grey";
		goggle26.lensType = "Polarized";
		goggle26.frameMaterial = "Plastic";
		goggle26.size = "Medium";
		goggle26.gender = "Women";
		System.out.println("goggle id is " + goggle26.id);
		System.out.println("brand is " + goggle26.brand);
		System.out.println("price is " + goggle26.price);
		System.out.println("colour is " + goggle26.colour);
		System.out.println("lens type is " + goggle26.lensType);
		System.out.println("frame material is " + goggle26.frameMaterial);
		System.out.println("size is " + goggle26.size);
		System.out.println("gender is " + goggle26.gender);
		System.out.println("----------------------");

		Goggle goggle27 = new Goggle();
		goggle27.id = 27;
		goggle27.brand = "Oakley";
		goggle27.price = 4900;
		goggle27.colour = "Black";
		goggle27.lensType = "UV";
		goggle27.frameMaterial = "Fiber";
		goggle27.size = "Large";
		goggle27.gender = "Unisex";
		System.out.println("goggle id is " + goggle27.id);
		System.out.println("brand is " + goggle27.brand);
		System.out.println("price is " + goggle27.price);
		System.out.println("colour is " + goggle27.colour);
		System.out.println("lens type is " + goggle27.lensType);
		System.out.println("frame material is " + goggle27.frameMaterial);
		System.out.println("size is " + goggle27.size);
		System.out.println("gender is " + goggle27.gender);
		System.out.println("----------------------");

		Goggle goggle28 = new Goggle();
		goggle28.id = 28;
		goggle28.brand = "RayBan";
		goggle28.price = 4300;
		goggle28.colour = "Green";
		goggle28.lensType = "Polarized";
		goggle28.frameMaterial = "Metal";
		goggle28.size = "Large";
		goggle28.gender = "Women";
		System.out.println("goggle id is " + goggle28.id);
		System.out.println("brand is " + goggle28.brand);
		System.out.println("price is " + goggle28.price);
		System.out.println("colour is " + goggle28.colour);
		System.out.println("lens type is " + goggle28.lensType);
		System.out.println("frame material is " + goggle28.frameMaterial);
		System.out.println("size is " + goggle28.size);
		System.out.println("gender is " + goggle28.gender);
		System.out.println("----------------------");

		Goggle goggle29 = new Goggle();
		goggle29.id = 29;
		goggle29.brand = "Fastrack";
		goggle29.price = 1750;
		goggle29.colour = "Black";
		goggle29.lensType = "UV";
		goggle29.frameMaterial = "Plastic";
		goggle29.size = "Medium";
		goggle29.gender = "Men";
		System.out.println("goggle id is " + goggle29.id);
		System.out.println("brand is " + goggle29.brand);
		System.out.println("price is " + goggle29.price);
		System.out.println("colour is " + goggle29.colour);
		System.out.println("lens type is " + goggle29.lensType);
		System.out.println("frame material is " + goggle29.frameMaterial);
		System.out.println("size is " + goggle29.size);
		System.out.println("gender is " + goggle29.gender);
		System.out.println("----------------------");

		Goggle goggle30 = new Goggle();
		goggle30.id = 30;
		goggle30.brand = "Oakley";
		goggle30.price = 5000;
		goggle30.colour = "Blue";
		goggle30.lensType = "Polarized";
		goggle30.frameMaterial = "Fiber";
		goggle30.size = "Large";
		goggle30.gender = "Unisex";
		System.out.println("goggle id is " + goggle30.id);
		System.out.println("brand is " + goggle30.brand);
		System.out.println("price is " + goggle30.price);
		System.out.println("colour is " + goggle30.colour);
		System.out.println("lens type is " + goggle30.lensType);
		System.out.println("frame material is " + goggle30.frameMaterial);
		System.out.println("size is " + goggle30.size);
		System.out.println("gender is " + goggle30.gender);
		System.out.println("----------------------");
		
	}
}