class LightsExecuter{
	public static void main(String[] args){

		Lights light1 = new Lights();
		light1.id = 1;
		light1.brand = "Philips";
		light1.price = 250;
		light1.colour = "White";
		light1.type = "LED";
		light1.material = "Plastic";
		light1.watts = 9;
		light1.shape = "Round";
		System.out.println("light id is " + light1.id);
		System.out.println("brand is " + light1.brand);
		System.out.println("price is " + light1.price);
		System.out.println("colour is " + light1.colour);
		System.out.println("type is " + light1.type);
		System.out.println("material is " + light1.material);
		System.out.println("watts is " + light1.watts);
		System.out.println("shape is " + light1.shape);

		Lights light2 = new Lights();
		light2.id = 2;
		light2.brand = "Wipro";
		light2.price = 220;
		light2.colour = "Warm White";
		light2.type = "LED";
		light2.material = "Plastic";
		light2.watts = 7;
		light2.shape = "Round";
		System.out.println("light id is " + light2.id);
		System.out.println("brand is " + light2.brand);
		System.out.println("price is " + light2.price);
		System.out.println("colour is " + light2.colour);
		System.out.println("type is " + light2.type);
		System.out.println("material is " + light2.material);
		System.out.println("watts is " + light2.watts);
		System.out.println("shape is " + light2.shape);

		Lights light3 = new Lights();
		light3.id = 3;
		light3.brand = "Havells";
		light3.price = 300;
		light3.colour = "White";
		light3.type = "LED";
		light3.material = "Plastic";
		light3.watts = 12;
		light3.shape = "Round";
		System.out.println("light id is " + light3.id);
		System.out.println("brand is " + light3.brand);
		System.out.println("price is " + light3.price);
		System.out.println("colour is " + light3.colour);
		System.out.println("type is " + light3.type);
		System.out.println("material is " + light3.material);
		System.out.println("watts is " + light3.watts);
		System.out.println("shape is " + light3.shape);

		Lights light4 = new Lights();
		light4.id = 4;
		light4.brand = "Philips";
		light4.price = 270;
		light4.colour = "Warm White";
		light4.type = "LED";
		light4.material = "Plastic";
		light4.watts = 10;
		light4.shape = "Round";
		System.out.println("light id is " + light4.id);
		System.out.println("brand is " + light4.brand);
		System.out.println("price is " + light4.price);
		System.out.println("colour is " + light4.colour);
		System.out.println("type is " + light4.type);
		System.out.println("material is " + light4.material);
		System.out.println("watts is " + light4.watts);
		System.out.println("shape is " + light4.shape);

		Lights light5 = new Lights();
		light5.id = 5;
		light5.brand = "Wipro";
		light5.price = 240;
		light5.colour = "White";
		light5.type = "LED";
		light5.material = "Plastic";
		light5.watts = 9;
		light5.shape = "Round";
		System.out.println("light id is " + light5.id);
		System.out.println("brand is " + light5.brand);
		System.out.println("price is " + light5.price);
		System.out.println("colour is " + light5.colour);
		System.out.println("type is " + light5.type);
		System.out.println("material is " + light5.material);
		System.out.println("watts is " + light5.watts);
		System.out.println("shape is " + light5.shape);

		Lights light6 = new Lights();
		light6.id = 6;
		light6.brand = "Havells";
		light6.price = 320;
		light6.colour = "White";
		light6.type = "LED";
		light6.material = "Plastic";
		light6.watts = 15;
		light6.shape = "Round";
		System.out.println("light id is " + light6.id);
		System.out.println("brand is " + light6.brand);
		System.out.println("price is " + light6.price);
		System.out.println("colour is " + light6.colour);
		System.out.println("type is " + light6.type);
		System.out.println("material is " + light6.material);
		System.out.println("watts is " + light6.watts);
		System.out.println("shape is " + light6.shape);

		Lights light7 = new Lights();
		light7.id = 7;
		light7.brand = "Philips";
		light7.price = 260;
		light7.colour = "White";
		light7.type = "LED";
		light7.material = "Plastic";
		light7.watts = 8;
		light7.shape = "Round";
		System.out.println("light id is " + light7.id);
		System.out.println("brand is " + light7.brand);
		System.out.println("price is " + light7.price);
		System.out.println("colour is " + light7.colour);
		System.out.println("type is " + light7.type);
		System.out.println("material is " + light7.material);
		System.out.println("watts is " + light7.watts);
		System.out.println("shape is " + light7.shape);

		Lights light8 = new Lights();
		light8.id = 8;
		light8.brand = "Wipro";
		light8.price = 210;
		light8.colour = "Warm White";
		light8.type = "LED";
		light8.material = "Plastic";
		light8.watts = 7;
		light8.shape = "Round";
		System.out.println("light id is " + light8.id);
		System.out.println("brand is " + light8.brand);
		System.out.println("price is " + light8.price);
		System.out.println("colour is " + light8.colour);
		System.out.println("type is " + light8.type);
		System.out.println("material is " + light8.material);
		System.out.println("watts is " + light8.watts);
		System.out.println("shape is " + light8.shape);

		Lights light9 = new Lights();
		light9.id = 9;
		light9.brand = "Havells";
		light9.price = 350;
		light9.colour = "White";
		light9.type = "LED";
		light9.material = "Plastic";
		light9.watts = 18;
		light9.shape = "Round";
		System.out.println("light id is " + light9.id);
		System.out.println("brand is " + light9.brand);
		System.out.println("price is " + light9.price);
		System.out.println("colour is " + light9.colour);
		System.out.println("type is " + light9.type);
		System.out.println("material is " + light9.material);
		System.out.println("watts is " + light9.watts);
		System.out.println("shape is " + light9.shape);

		Lights light10 = new Lights();
		light10.id = 10;
		light10.brand = "Philips";
		light10.price = 280;
		light10.colour = "Warm White";
		light10.type = "LED";
		light10.material = "Plastic";
		light10.watts = 10;
		light10.shape = "Round";
		System.out.println("light id is " + light10.id);
		System.out.println("brand is " + light10.brand);
		System.out.println("price is " + light10.price);
		System.out.println("colour is " + light10.colour);
		System.out.println("type is " + light10.type);
		System.out.println("material is " + light10.material);
		System.out.println("watts is " + light10.watts);
		System.out.println("shape is " + light10.shape);

		Lights light11 = new Lights();
		light11.id = 11;
		light11.brand = "Wipro";
		light11.price = 230;
		light11.colour = "White";
		light11.type = "LED";
		light11.material = "Plastic";
		light11.watts = 9;
		light11.shape = "Round";
		System.out.println("light id is " + light11.id);
		System.out.println("brand is " + light11.brand);
		System.out.println("price is " + light11.price);
		System.out.println("colour is " + light11.colour);
		System.out.println("type is " + light11.type);
		System.out.println("material is " + light11.material);
		System.out.println("watts is " + light11.watts);
		System.out.println("shape is " + light11.shape);

		Lights light12 = new Lights();
		light12.id = 12;
		light12.brand = "Havells";
		light12.price = 360;
		light12.colour = "White";
		light12.type = "LED";
		light12.material = "Plastic";
		light12.watts = 20;
		light12.shape = "Round";
		System.out.println("light id is " + light12.id);
		System.out.println("brand is " + light12.brand);
		System.out.println("price is " + light12.price);
		System.out.println("colour is " + light12.colour);
		System.out.println("type is " + light12.type);
		System.out.println("material is " + light12.material);
		System.out.println("watts is " + light12.watts);
		System.out.println("shape is " + light12.shape);

		Lights light13 = new Lights();
		light13.id = 13;
		light13.brand = "Philips";
		light13.price = 290;
		light13.colour = "White";
		light13.type = "LED";
		light13.material = "Plastic";
		light13.watts = 12;
		light13.shape = "Round";
		System.out.println("light id is " + light13.id);
		System.out.println("brand is " + light13.brand);
		System.out.println("price is " + light13.price);
		System.out.println("colour is " + light13.colour);
		System.out.println("type is " + light13.type);
		System.out.println("material is " + light13.material);
		System.out.println("watts is " + light13.watts);
		System.out.println("shape is " + light13.shape);

		Lights light14 = new Lights();
		light14.id = 14;
		light14.brand = "Wipro";
		light14.price = 215;
		light14.colour = "Warm White";
		light14.type = "LED";
		light14.material = "Plastic";
		light14.watts = 7;
		light14.shape = "Round";
		System.out.println("light id is " + light14.id);
		System.out.println("brand is " + light14.brand);
		System.out.println("price is " + light14.price);
		System.out.println("colour is " + light14.colour);
		System.out.println("type is " + light14.type);
		System.out.println("material is " + light14.material);
		System.out.println("watts is " + light14.watts);
		System.out.println("shape is " + light14.shape);

		Lights light15 = new Lights();
		light15.id = 15;
		light15.brand = "Havells";
		light15.price = 380;
		light15.colour = "White";
		light15.type = "LED";
		light15.material = "Plastic";
		light15.watts = 22;
		light15.shape = "Round";
		System.out.println("light id is " + light15.id);
		System.out.println("brand is " + light15.brand);
		System.out.println("price is " + light15.price);
		System.out.println("colour is " + light15.colour);
		System.out.println("type is " + light15.type);
		System.out.println("material is " + light15.material);
		System.out.println("watts is " + light15.watts);
		System.out.println("shape is " + light15.shape);

		Lights light16 = new Lights();
		light16.id = 16;
		light16.brand = "Philips";
		light16.price = 300;
		light16.colour = "White";
		light16.type = "LED";
		light16.material = "Plastic";
		light16.watts = 14;
		light16.shape = "Round";
		System.out.println("light id is " + light16.id);
		System.out.println("brand is " + light16.brand);
		System.out.println("price is " + light16.price);
		System.out.println("colour is " + light16.colour);
		System.out.println("type is " + light16.type);
		System.out.println("material is " + light16.material);
		System.out.println("watts is " + light16.watts);
		System.out.println("shape is " + light16.shape);

		Lights light17 = new Lights();
		light17.id = 17;
		light17.brand = "Wipro";
		light17.price = 240;
		light17.colour = "White";
		light17.type = "LED";
		light17.material = "Plastic";
		light17.watts = 9;
		light17.shape = "Round";
		System.out.println("light id is " + light17.id);
		System.out.println("brand is " + light17.brand);
		System.out.println("price is " + light17.price);
		System.out.println("colour is " + light17.colour);
		System.out.println("type is " + light17.type);
		System.out.println("material is " + light17.material);
		System.out.println("watts is " + light17.watts);
		System.out.println("shape is " + light17.shape);

		Lights light18 = new Lights();
		light18.id = 18;
		light18.brand = "Havells";
		light18.price = 400;
		light18.colour = "White";
		light18.type = "LED";
		light18.material = "Plastic";
		light18.watts = 24;
		light18.shape = "Round";
		System.out.println("light id is " + light18.id);
		System.out.println("brand is " + light18.brand);
		System.out.println("price is " + light18.price);
		System.out.println("colour is " + light18.colour);
		System.out.println("type is " + light18.type);
		System.out.println("material is " + light18.material);
		System.out.println("watts is " + light18.watts);
		System.out.println("shape is " + light18.shape);

		Lights light19 = new Lights();
		light19.id = 19;
		light19.brand = "Philips";
		light19.price = 310;
		light19.colour = "Warm White";
		light19.type = "LED";
		light19.material = "Plastic";
		light19.watts = 15;
		light19.shape = "Round";
		System.out.println("light id is " + light19.id);
		System.out.println("brand is " + light19.brand);
		System.out.println("price is " + light19.price);
		System.out.println("colour is " + light19.colour);
		System.out.println("type is " + light19.type);
		System.out.println("material is " + light19.material);
		System.out.println("watts is " + light19.watts);
		System.out.println("shape is " + light19.shape);

		Lights light20 = new Lights();
		light20.id = 20;
		light20.brand = "Wipro";
		light20.price = 250;
		light20.colour = "White";
		light20.type = "LED";
		light20.material = "Plastic";
		light20.watts = 12;
		light20.shape = "Round";
		System.out.println("light id is " + light20.id);
		System.out.println("brand is " + light20.brand);
		System.out.println("price is " + light20.price);
		System.out.println("colour is " + light20.colour);
		System.out.println("type is " + light20.type);
		System.out.println("material is " + light20.material);
		System.out.println("watts is " + light20.watts);
		System.out.println("shape is " + light20.shape);

		Lights light21 = new Lights();
		light21.id = 21;
		light21.brand = "Havells";
		light21.price = 420;
		light21.colour = "White";
		light21.type = "LED";
		light21.material = "Plastic";
		light21.watts = 26;
		light21.shape = "Round";
		System.out.println("light id is " + light21.id);
		System.out.println("brand is " + light21.brand);
		System.out.println("price is " + light21.price);
		System.out.println("colour is " + light21.colour);
		System.out.println("type is " + light21.type);
		System.out.println("material is " + light21.material);
		System.out.println("watts is " + light21.watts);
		System.out.println("shape is " + light21.shape);

		Lights light22 = new Lights();
		light22.id = 22;
		light22.brand = "Philips";
		light22.price = 320;
		light22.colour = "White";
		light22.type = "LED";
		light22.material = "Plastic";
		light22.watts = 16;
		light22.shape = "Round";
		System.out.println("light id is " + light22.id);
		System.out.println("brand is " + light22.brand);
		System.out.println("price is " + light22.price);
		System.out.println("colour is " + light22.colour);
		System.out.println("type is " + light22.type);
		System.out.println("material is " + light22.material);
		System.out.println("watts is " + light22.watts);
		System.out.println("shape is " + light22.shape);

		Lights light23 = new Lights();
		light23.id = 23;
		light23.brand = "Wipro";
		light23.price = 260;
		light23.colour = "Warm White";
		light23.type = "LED";
		light23.material = "Plastic";
		light23.watts = 10;
		light23.shape = "Round";
		System.out.println("light id is " + light23.id);
		System.out.println("brand is " + light23.brand);
		System.out.println("price is " + light23.price);
		System.out.println("colour is " + light23.colour);
		System.out.println("type is " + light23.type);
		System.out.println("material is " + light23.material);
		System.out.println("watts is " + light23.watts);
		System.out.println("shape is " + light23.shape);

		Lights light24 = new Lights();
		light24.id = 24;
		light24.brand = "Havells";
		light24.price = 440;
		light24.colour = "White";
		light24.type = "LED";
		light24.material = "Plastic";
		light24.watts = 28;
		light24.shape = "Round";
		System.out.println("light id is " + light24.id);
		System.out.println("brand is " + light24.brand);
		System.out.println("price is " + light24.price);
		System.out.println("colour is " + light24.colour);
		System.out.println("type is " + light24.type);
		System.out.println("material is " + light24.material);
		System.out.println("watts is " + light24.watts);
		System.out.println("shape is " + light24.shape);

		Lights light25 = new Lights();
		light25.id = 25;
		light25.brand = "Philips";
		light25.price = 330;
		light25.colour = "White";
		light25.type = "LED";
		light25.material = "Plastic";
		light25.watts = 18;
		light25.shape = "Round";
		System.out.println("light id is " + light25.id);
		System.out.println("brand is " + light25.brand);
		System.out.println("price is " + light25.price);
		System.out.println("colour is " + light25.colour);
		System.out.println("type is " + light25.type);
		System.out.println("material is " + light25.material);
		System.out.println("watts is " + light25.watts);
		System.out.println("shape is " + light25.shape);

		Lights light26 = new Lights();
		light26.id = 26;
		light26.brand = "Wipro";
		light26.price = 270;
		light26.colour = "White";
		light26.type = "LED";
		light26.material = "Plastic";
		light26.watts = 12;
		light26.shape = "Round";
		System.out.println("light id is " + light26.id);
		System.out.println("brand is " + light26.brand);
		System.out.println("price is " + light26.price);
		System.out.println("colour is " + light26.colour);
		System.out.println("type is " + light26.type);
		System.out.println("material is " + light26.material);
		System.out.println("watts is " + light26.watts);
		System.out.println("shape is " + light26.shape);

		Lights light27 = new Lights();
		light27.id = 27;
		light27.brand = "Havells";
		light27.price = 460;
		light27.colour = "White";
		light27.type = "LED";
		light27.material = "Plastic";
		light27.watts = 30;
		light27.shape = "Round";
		System.out.println("light id is " + light27.id);
		System.out.println("brand is " + light27.brand);
		System.out.println("price is " + light27.price);
		System.out.println("colour is " + light27.colour);
		System.out.println("type is " + light27.type);
		System.out.println("material is " + light27.material);
		System.out.println("watts is " + light27.watts);
		System.out.println("shape is " + light27.shape);

		Lights light28 = new Lights();
		light28.id = 28;
		light28.brand = "Philips";
		light28.price = 340;
		light28.colour = "Warm White";
		light28.type = "LED";
		light28.material = "Plastic";
		light28.watts = 20;
		light28.shape = "Round";
		System.out.println("light id is " + light28.id);
		System.out.println("brand is " + light28.brand);
		System.out.println("price is " + light28.price);
		System.out.println("colour is " + light28.colour);
		System.out.println("type is " + light28.type);
		System.out.println("material is " + light28.material);
		System.out.println("watts is " + light28.watts);
		System.out.println("shape is " + light28.shape);

		Lights light29 = new Lights();
		light29.id = 29;
		light29.brand = "Wipro";
		light29.price = 280;
		light29.colour = "White";
		light29.type = "LED";
		light29.material = "Plastic";
		light29.watts = 14;
		light29.shape = "Round";
		System.out.println("light id is " + light29.id);
		System.out.println("brand is " + light29.brand);
		System.out.println("price is " + light29.price);
		System.out.println("colour is " + light29.colour);
		System.out.println("type is " + light29.type);
		System.out.println("material is " + light29.material);
		System.out.println("watts is " + light29.watts);
		System.out.println("shape is " + light29.shape);

		Lights light30 = new Lights();
		light30.id = 30;
		light30.brand = "Havells";
		light30.price = 480;
		light30.colour = "White";
		light30.type = "LED";
		light30.material = "Plastic";
		light30.watts = 32;
		light30.shape = "Round";
		System.out.println("light id is " + light30.id);
		System.out.println("brand is " + light30.brand);
		System.out.println("price is " + light30.price);
		System.out.println("colour is " + light30.colour);
		System.out.println("type is " + light30.type);
		System.out.println("material is " + light30.material);
		System.out.println("watts is " + light30.watts);
		System.out.println("shape is " + light30.shape);

	}
}