class MascaraRunner {
    public static void main(String[] args) {

        Mascara m1 = new Mascara();
        m1.mascaraId = 1;
        m1.price = 299;
        m1.brandName = "Maybelline";
        m1.type = "Curl";
        m1.color = "Black";
        m1.waterproof = "Yes";
        m1.volumeEffect = "High";
        m1.expiryMonths = 12;
        System.out.println("The mascaraId is : " + m1.mascaraId);
        System.out.println("The price is : " + m1.price);
        System.out.println("The brandName is : " + m1.brandName);
        System.out.println("The type is : " + m1.type);
        System.out.println("The color is : " + m1.color);
        System.out.println("The waterproof is : " + m1.waterproof);
        System.out.println("The volumeEffect is : " + m1.volumeEffect);
        System.out.println("The expiryMonths is : " + m1.expiryMonths);
        System.out.println("---------------------------");

        Mascara m2 = new Mascara();
        m2.mascaraId = 2;
        m2.price = 350;
        m2.brandName = "Lakme";
        m2.type = "Volume";
        m2.color = "Black";
        m2.waterproof = "No";
        m2.volumeEffect = "Medium";
        m2.expiryMonths = 10;
        System.out.println("The mascaraId is : " + m2.mascaraId);
        System.out.println("The price is : " + m2.price);
        System.out.println("The brandName is : " + m2.brandName);
        System.out.println("The type is : " + m2.type);
        System.out.println("The color is : " + m2.color);
        System.out.println("The waterproof is : " + m2.waterproof);
        System.out.println("The volumeEffect is : " + m2.volumeEffect);
        System.out.println("The expiryMonths is : " + m2.expiryMonths);
        System.out.println("---------------------------");

        Mascara m3 = new Mascara();
        m3.mascaraId = 3;
        m3.price = 450;
        m3.brandName = "Loreal";
        m3.type = "Length";
        m3.color = "Brown";
        m3.waterproof = "Yes";
        m3.volumeEffect = "High";
        m3.expiryMonths = 12;
		System.out.println("The mascaraId is : " + m3.mascaraId);
        System.out.println("The price is : " + m3.price);
        System.out.println("The brandName is : " + m3.brandName);
        System.out.println("The type is : " + m3.type);
        System.out.println("The color is : " + m3.color);
        System.out.println("The waterproof is : " + m3.waterproof);
        System.out.println("The volumeEffect is : " + m3.volumeEffect);
        System.out.println("The expiryMonths is : " + m3.expiryMonths);
        System.out.println("---------------------------");

        Mascara m4 = new Mascara();
        m4.mascaraId = 4;
        m4.price = 280;
        m4.brandName = "Colorbar";
        m4.type = "Curl";
        m4.color = "Black";
        m4.waterproof = "No";
        m4.volumeEffect = "Low";
        m4.expiryMonths = 8;
        System.out.println("The mascaraId is : " + m4.mascaraId);
        System.out.println("The price is : " + m4.price);
        System.out.println("The brandName is : " + m4.brandName);
        System.out.println("The type is : " + m4.type);
        System.out.println("The color is : " + m4.color);
        System.out.println("The waterproof is : " + m4.waterproof);
        System.out.println("The volumeEffect is : " + m4.volumeEffect);
        System.out.println("The expiryMonths is : " + m4.expiryMonths);
        System.out.println("---------------------------");
		
        Mascara m5 = new Mascara();
        m5.mascaraId = 5;
        m5.price = 399;
        m5.brandName = "Faces";
        m5.type = "Volume";
        m5.color = "Black";
        m5.waterproof = "Yes";
        m5.volumeEffect = "High";
        m5.expiryMonths = 11;
		System.out.println("The mascaraId is : " + m5.mascaraId);
        System.out.println("The price is : " + m5.price);
        System.out.println("The brandName is : " + m5.brandName);
        System.out.println("The type is : " + m5.type);
        System.out.println("The color is : " + m5.color);
        System.out.println("The waterproof is : " + m5.waterproof);
        System.out.println("The volumeEffect is : " + m5.volumeEffect);
        System.out.println("The expiryMonths is : " + m5.expiryMonths);
        System.out.println("---------------------------");

        Mascara m6 = new Mascara();
        m6.mascaraId = 6;
        m6.price = 420;
        m6.brandName = "Revlon";
        m6.type = "Length";
        m6.color = "Brown";
        m6.waterproof = "Yes";
        m6.volumeEffect = "Medium";
        m6.expiryMonths = 12;
		System.out.println("The mascaraId is : " + m6.mascaraId);
        System.out.println("The price is : " + m6.price);
        System.out.println("The brandName is : " + m6.brandName);
        System.out.println("The type is : " + m6.type);
        System.out.println("The color is : " + m6.color);
        System.out.println("The waterproof is : " + m6.waterproof);
        System.out.println("The volumeEffect is : " + m6.volumeEffect);
        System.out.println("The expiryMonths is : " + m6.expiryMonths);
        System.out.println("---------------------------");

        Mascara m7 = new Mascara();
        m7.mascaraId = 7;
        m7.price = 310;
        m7.brandName = "Elle18";
        m7.type = "Curl";
        m7.color = "Black";
        m7.waterproof = "No";
        m7.volumeEffect = "Low";
        m7.expiryMonths = 9;
		System.out.println("The mascaraId is : " + m7.mascaraId);
        System.out.println("The price is : " + m7.price);
        System.out.println("The brandName is : " + m7.brandName);
        System.out.println("The type is : " + m7.type);
        System.out.println("The color is : " + m7.color);
        System.out.println("The waterproof is : " + m7.waterproof);
        System.out.println("The volumeEffect is : " + m7.volumeEffect);
        System.out.println("The expiryMonths is : " + m7.expiryMonths);
        System.out.println("---------------------------");

        Mascara m8 = new Mascara();
        m8.mascaraId = 8;
        m8.price = 500;
        m8.brandName = "MAC";
        m8.type = "Volume";
        m8.color = "Black";
        m8.waterproof = "Yes";
        m8.volumeEffect = "High";
        m8.expiryMonths = 12;
		System.out.println("The mascaraId is : " + m8.mascaraId);
        System.out.println("The price is : " + m8.price);
        System.out.println("The brandName is : " + m8.brandName);
        System.out.println("The type is : " + m8.type);
        System.out.println("The color is : " + m8.color);
        System.out.println("The waterproof is : " + m8.waterproof);
        System.out.println("The volumeEffect is : " + m8.volumeEffect);
        System.out.println("The expiryMonths is : " + m8.expiryMonths);
        System.out.println("---------------------------");
		
        Mascara m9 = new Mascara();
        m9.mascaraId = 9;
        m9.price = 550;
        m9.brandName = "Huda";
        m9.type = "Length";
        m9.color = "Black";
        m9.waterproof = "Yes";
        m9.volumeEffect = "High";
        m9.expiryMonths = 12;
		System.out.println("The mascaraId is : " + m9.mascaraId);
        System.out.println("The price is : " + m9.price);
        System.out.println("The brandName is : " + m9.brandName);
        System.out.println("The type is : " + m9.type);
        System.out.println("The color is : " + m9.color);
        System.out.println("The waterproof is : " + m9.waterproof);
        System.out.println("The volumeEffect is : " + m9.volumeEffect);
        System.out.println("The expiryMonths is : " + m9.expiryMonths);
        System.out.println("---------------------------");

        Mascara m10 = new Mascara();
        m10.mascaraId = 10;
        m10.price = 260;
        m10.brandName = "BlueHeaven";
        m10.type = "Curl";
        m10.color = "Black";
        m10.waterproof = "No";
        m10.volumeEffect = "Medium";
        m10.expiryMonths = 8;
		System.out.println("The mascaraId is : " + m10.mascaraId);
        System.out.println("The price is : " + m10.price);
        System.out.println("The brandName is : " + m10.brandName);
        System.out.println("The type is : " + m10.type);
        System.out.println("The color is : " + m10.color);
        System.out.println("The waterproof is : " + m10.waterproof);
        System.out.println("The volumeEffect is : " + m10.volumeEffect);
        System.out.println("The expiryMonths is : " + m10.expiryMonths);
        System.out.println("---------------------------");
		
		Mascara m11 = new Mascara();
		m11.mascaraId = 11;
		m11.price = 610;
		m11.brandName = "SwissBeauty";
		m11.type = "Curl";
		m11.color = "Black";
		m11.waterproof = "No";
		m11.volumeEffect = "Medium";
		m11.expiryMonths = 10;
		System.out.println("The mascaraId is : " + m11.mascaraId);
		System.out.println("The price is : " + m11.price);
		System.out.println("The brandName is : " + m11.brandName);
		System.out.println("The type is : " + m11.type);
		System.out.println("The color is : " + m11.color);
		System.out.println("The waterproof is : " + m11.waterproof);
		System.out.println("The volumeEffect is : " + m11.volumeEffect);
		System.out.println("The expiryMonths is : " + m11.expiryMonths);
		System.out.println("---------------------------");
		
		Mascara m12 = new Mascara();
		m12.mascaraId = 12;
		m12.price = 420;
		m12.brandName = "Insight";
		m12.type = "Volume";
		m12.color = "Brown";
		m12.waterproof = "Yes";
		m12.volumeEffect = "High";
		m12.expiryMonths = 11;
		System.out.println("The mascaraId is : " + m12.mascaraId);
		System.out.println("The price is : " + m12.price);
		System.out.println("The brandName is : " + m12.brandName);
		System.out.println("The type is : " + m12.type);
		System.out.println("The color is : " + m12.color);
		System.out.println("The waterproof is : " + m12.waterproof);
		System.out.println("The volumeEffect is : " + m12.volumeEffect);
		System.out.println("The expiryMonths is : " + m12.expiryMonths);
		System.out.println("---------------------------");

		Mascara m13 = new Mascara();
		m13.mascaraId = 13;
		m13.price = 390;
		m13.brandName = "Plum";
		m13.type = "Length";
		m13.color = "Black";
		m13.waterproof = "No";
		m13.volumeEffect = "Medium";
		m13.expiryMonths = 9;
		System.out.println("The mascaraId is : " + m13.mascaraId);
		System.out.println("The price is : " + m13.price);
		System.out.println("The brandName is : " + m13.brandName);
		System.out.println("The type is : " + m13.type);
		System.out.println("The color is : " + m13.color);
		System.out.println("The waterproof is : " + m13.waterproof);
		System.out.println("The volumeEffect is : " + m13.volumeEffect);
		System.out.println("The expiryMonths is : " + m13.expiryMonths);
		System.out.println("---------------------------");

		Mascara m14 = new Mascara();
		m14.mascaraId = 14;
		m14.price = 720;
		m14.brandName = "BobbiBrown";
		m14.type = "Volume";
		m14.color = "Black";
		m14.waterproof = "Yes";
		m14.volumeEffect = "High";
		m14.expiryMonths = 12;

		System.out.println("The mascaraId is : " + m14.mascaraId);
		System.out.println("The price is : " + m14.price);
		System.out.println("The brandName is : " + m14.brandName);
		System.out.println("The type is : " + m14.type);
		System.out.println("The color is : " + m14.color);
		System.out.println("The waterproof is : " + m14.waterproof);
		System.out.println("The volumeEffect is : " + m14.volumeEffect);
		System.out.println("The expiryMonths is : " + m14.expiryMonths);
		System.out.println("---------------------------");

		Mascara m15 = new Mascara();
		m15.mascaraId = 15;
		m15.price = 480;
		m15.brandName = "FacesCanada";
		m15.type = "Curl";
		m15.color = "Blue";
		m15.waterproof = "Yes";
		m15.volumeEffect = "Medium";
		m15.expiryMonths = 10;
		System.out.println("The mascaraId is : " + m15.mascaraId);
		System.out.println("The price is : " + m15.price);
		System.out.println("The brandName is : " + m15.brandName);
		System.out.println("The type is : " + m15.type);
		System.out.println("The color is : " + m15.color);
		System.out.println("The waterproof is : " + m15.waterproof);
		System.out.println("The volumeEffect is : " + m15.volumeEffect);
		System.out.println("The expiryMonths is : " + m15.expiryMonths);
		System.out.println("---------------------------");

		Mascara m16 = new Mascara();
		m16.mascaraId = 16;
		m16.price = 510;
		m16.brandName = "KayBeauty";
		m16.type = "Length";
		m16.color = "Black";
		m16.waterproof = "No";
		m16.volumeEffect = "High";
		m16.expiryMonths = 11;
		System.out.println("The mascaraId is : " + m16.mascaraId);
		System.out.println("The price is : " + m16.price);
		System.out.println("The brandName is : " + m16.brandName);
		System.out.println("The type is : " + m16.type);
		System.out.println("The color is : " + m16.color);
		System.out.println("The waterproof is : " + m16.waterproof);
		System.out.println("The volumeEffect is : " + m16.volumeEffect);
		System.out.println("The expiryMonths is : " + m16.expiryMonths);
		System.out.println("---------------------------");

		Mascara m17 = new Mascara();
		m17.mascaraId = 17;
		m17.price = 460;
		m17.brandName = "WetnWild";
		m17.type = "Volume";
		m17.color = "Brown";
		m17.waterproof = "Yes";
		m17.volumeEffect = "Medium";
		m17.expiryMonths = 10;
		System.out.println("The mascaraId is : " + m17.mascaraId);
		System.out.println("The price is : " + m17.price);
		System.out.println("The brandName is : " + m17.brandName);
		System.out.println("The type is : " + m17.type);
		System.out.println("The color is : " + m17.color);
		System.out.println("The waterproof is : " + m17.waterproof);
		System.out.println("The volumeEffect is : " + m17.volumeEffect);
		System.out.println("The expiryMonths is : " + m17.expiryMonths);
		System.out.println("---------------------------");

		Mascara m18 = new Mascara();
		m18.mascaraId = 18;
		m18.price = 530;
		m18.brandName = "Essence";
		m18.type = "Curl";
		m18.color = "Black";
		m18.waterproof = "No";
		m18.volumeEffect = "High";
		m18.expiryMonths = 9;
		System.out.println("The mascaraId is : " + m18.mascaraId);
		System.out.println("The price is : " + m18.price);
		System.out.println("The brandName is : " + m18.brandName);
		System.out.println("The type is : " + m18.type);
		System.out.println("The color is : " + m18.color);
		System.out.println("The waterproof is : " + m18.waterproof);
		System.out.println("The volumeEffect is : " + m18.volumeEffect);
		System.out.println("The expiryMonths is : " + m18.expiryMonths);
		System.out.println("---------------------------");

		Mascara m19 = new Mascara();
		m19.mascaraId = 19;
		m19.price = 670;
		m19.brandName = "Clinique";
		m19.type = "Length";
		m19.color = "Black";
		m19.waterproof = "Yes";
		m19.volumeEffect = "High";
		m19.expiryMonths = 12;
		System.out.println("The mascaraId is : " + m19.mascaraId);
		System.out.println("The price is : " + m19.price);
		System.out.println("The brandName is : " + m19.brandName);
		System.out.println("The type is : " + m19.type);
		System.out.println("The color is : " + m19.color);
		System.out.println("The waterproof is : " + m19.waterproof);
		System.out.println("The volumeEffect is : " + m19.volumeEffect);
		System.out.println("The expiryMonths is : " + m19.expiryMonths);
		System.out.println("---------------------------");

		Mascara m20 = new Mascara();
		m20.mascaraId = 20;
		m20.price = 750;
		m20.brandName = "EsteeLauder";
		m20.type = "Volume";
		m20.color = "Black";
		m20.waterproof = "Yes";
		m20.volumeEffect = "High";
		m20.expiryMonths = 12;
		System.out.println("The mascaraId is : " + m20.mascaraId);
		System.out.println("The price is : " + m20.price);
		System.out.println("The brandName is : " + m20.brandName);
		System.out.println("The type is : " + m20.type);
		System.out.println("The color is : " + m20.color);
		System.out.println("The waterproof is : " + m20.waterproof);
		System.out.println("The volumeEffect is : " + m20.volumeEffect);
		System.out.println("The expiryMonths is : " + m20.expiryMonths);
		System.out.println("---------------------------");
		
		Mascara m21 = new Mascara();
		m21.mascaraId = 21;
		m21.price = 365;
		m21.brandName = "Lotus";
		m21.type = "Curl";
		m21.color = "Black";
		m21.waterproof = "No";
		m21.volumeEffect = "Medium";
		m21.expiryMonths = 9;
		System.out.println("The mascaraId is : " + m21.mascaraId);
		System.out.println("The price is : " + m21.price);
		System.out.println("The brandName is : " + m21.brandName);
		System.out.println("The type is : " + m21.type);
		System.out.println("The color is : " + m21.color);
		System.out.println("The waterproof is : " + m21.waterproof);
		System.out.println("The volumeEffect is : " + m21.volumeEffect);
		System.out.println("The expiryMonths is : " + m21.expiryMonths);
		System.out.println("---------------------------");

		Mascara m22 = new Mascara();
		m22.mascaraId = 22;
		m22.price = 430;
		m22.brandName = "Mamaearth";
		m22.type = "Volume";
		m22.color = "Brown";
		m22.waterproof = "Yes";
		m22.volumeEffect = "High";
		m22.expiryMonths = 11;
		System.out.println("The mascaraId is : " + m22.mascaraId);
		System.out.println("The price is : " + m22.price);
		System.out.println("The brandName is : " + m22.brandName);
		System.out.println("The type is : " + m22.type);
		System.out.println("The color is : " + m22.color);
		System.out.println("The waterproof is : " + m22.waterproof);
		System.out.println("The volumeEffect is : " + m22.volumeEffect);
		System.out.println("The expiryMonths is : " + m22.expiryMonths);
		System.out.println("---------------------------");

		Mascara m23 = new Mascara();
		m23.mascaraId = 23;
		m23.price = 520;
		m23.brandName = "Kiko";
		m23.type = "Length";
		m23.color = "Black";
		m23.waterproof = "Yes";
		m23.volumeEffect = "Medium";
		m23.expiryMonths = 12;
		System.out.println("The mascaraId is : " + m23.mascaraId);
		System.out.println("The price is : " + m23.price);
		System.out.println("The brandName is : " + m23.brandName);
		System.out.println("The type is : " + m23.type);
		System.out.println("The color is : " + m23.color);
		System.out.println("The waterproof is : " + m23.waterproof);
		System.out.println("The volumeEffect is : " + m23.volumeEffect);
		System.out.println("The expiryMonths is : " + m23.expiryMonths);
		System.out.println("---------------------------");

		Mascara m24 = new Mascara();
		m24.mascaraId = 24;
		m24.price = 390;
		m24.brandName = "Chambor";
		m24.type = "Curl";
		m24.color = "Blue";
		m24.waterproof = "No";
		m24.volumeEffect = "Low";
		m24.expiryMonths = 8;
		System.out.println("The mascaraId is : " + m24.mascaraId);
		System.out.println("The price is : " + m24.price);
		System.out.println("The brandName is : " + m24.brandName);
		System.out.println("The type is : " + m24.type);
		System.out.println("The color is : " + m24.color);
		System.out.println("The waterproof is : " + m24.waterproof);
		System.out.println("The volumeEffect is : " + m24.volumeEffect);
		System.out.println("The expiryMonths is : " + m24.expiryMonths);
		System.out.println("---------------------------");

		Mascara m25 = new Mascara();
		m25.mascaraId = 25;
		m25.price = 610;
		m25.brandName = "Innisfree";
		m25.type = "Volume";
		m25.color = "Black";
		m25.waterproof = "Yes";
		m25.volumeEffect = "High";
		m25.expiryMonths = 12;
		System.out.println("The mascaraId is : " + m25.mascaraId);
		System.out.println("The price is : " + m25.price);
		System.out.println("The brandName is : " + m25.brandName);
		System.out.println("The type is : " + m25.type);
		System.out.println("The color is : " + m25.color);
		System.out.println("The waterproof is : " + m25.waterproof);
		System.out.println("The volumeEffect is : " + m25.volumeEffect);
		System.out.println("The expiryMonths is : " + m25.expiryMonths);
		System.out.println("---------------------------");

		Mascara m26 = new Mascara();
		m26.mascaraId = 26;
		m26.price = 470;
		m26.brandName = "EtudeHouse";
		m26.type = "Length";
		m26.color = "Brown";
		m26.waterproof = "No";
		m26.volumeEffect = "Medium";
		m26.expiryMonths = 10;
		System.out.println("The mascaraId is : " + m26.mascaraId);
		System.out.println("The price is : " + m26.price);
		System.out.println("The brandName is : " + m26.brandName);
		System.out.println("The type is : " + m26.type);
		System.out.println("The color is : " + m26.color);
		System.out.println("The waterproof is : " + m26.waterproof);
		System.out.println("The volumeEffect is : " + m26.volumeEffect);
		System.out.println("The expiryMonths is : " + m26.expiryMonths);
		System.out.println("---------------------------");

		Mascara m27 = new Mascara();
		m27.mascaraId = 27;
		m27.price = 680;
		m27.brandName = "TooFaced";
		m27.type = "Volume";
		m27.color = "Black";
		m27.waterproof = "Yes";
		m27.volumeEffect = "High";
		m27.expiryMonths = 12;
		System.out.println("The mascaraId is : " + m27.mascaraId);
		System.out.println("The price is : " + m27.price);
		System.out.println("The brandName is : " + m27.brandName);
		System.out.println("The type is : " + m27.type);
		System.out.println("The color is : " + m27.color);
		System.out.println("The waterproof is : " + m27.waterproof);
		System.out.println("The volumeEffect is : " + m27.volumeEffect);
		System.out.println("The expiryMonths is : " + m27.expiryMonths);
		System.out.println("---------------------------");

        Mascara m28 = new Mascara();
        m28.mascaraId = 28;
        m28.price = 520;
        m28.brandName = "Nykaa";
        m28.type = "Curl";
        m28.color = "Black";
        m28.waterproof = "Yes";
        m28.volumeEffect = "High";
        m28.expiryMonths = 11;

        System.out.println("The mascaraId is : " + m28.mascaraId);
        System.out.println("The price is : " + m28.price);
        System.out.println("The brandName is : " + m28.brandName);
        System.out.println("The type is : " + m28.type);
        System.out.println("The color is : " + m28.color);
        System.out.println("The waterproof is : " + m28.waterproof);
        System.out.println("The volumeEffect is : " + m28.volumeEffect);
        System.out.println("The expiryMonths is : " + m28.expiryMonths);
        System.out.println("---------------------------");

        Mascara m29 = new Mascara();
        m29.mascaraId = 29;
        m29.price = 580;
        m29.brandName = "Sugar";
        m29.type = "Volume";
        m29.color = "Black";
        m29.waterproof = "Yes";
        m29.volumeEffect = "High";
        m29.expiryMonths = 12;

        System.out.println("The mascaraId is : " + m29.mascaraId);
        System.out.println("The price is : " + m29.price);
        System.out.println("The brandName is : " + m29.brandName);
        System.out.println("The type is : " + m29.type);
        System.out.println("The color is : " + m29.color);
        System.out.println("The waterproof is : " + m29.waterproof);
        System.out.println("The volumeEffect is : " + m29.volumeEffect);
        System.out.println("The expiryMonths is : " + m29.expiryMonths);
        System.out.println("---------------------------");

        Mascara m30 = new Mascara();
        m30.mascaraId = 30;
        m30.price = 600;
        m30.brandName = "Dior";
        m30.type = "Length";
        m30.color = "Black";
        m30.waterproof = "Yes";
        m30.volumeEffect = "High";
        m30.expiryMonths = 12;

        System.out.println("The mascaraId is : " + m30.mascaraId);
        System.out.println("The price is : " + m30.price);
        System.out.println("The brandName is : " + m30.brandName);
        System.out.println("The type is : " + m30.type);
        System.out.println("The color is : " + m30.color);
        System.out.println("The waterproof is : " + m30.waterproof);
        System.out.println("The volumeEffect is : " + m30.volumeEffect);
        System.out.println("The expiryMonths is : " + m30.expiryMonths);
        System.out.println("---------------------------");

    }
}