class RingExecuter{
	public static void main(String[] args){

		Ring ring1 = new Ring();
		ring1.id = 1;
		ring1.brand = "Tanishq";
		ring1.price = 12000;
		ring1.colour = "Gold";
		ring1.material = "Gold";
		ring1.size = "12";
		ring1.design = "Plain";
		ring1.gender = "Women";
		System.out.println("ring id is " + ring1.id);
		System.out.println("brand is " + ring1.brand);
		System.out.println("price is " + ring1.price);
		System.out.println("colour is " + ring1.colour);
		System.out.println("material is " + ring1.material);
		System.out.println("size is " + ring1.size);
		System.out.println("design is " + ring1.design);
		System.out.println("gender is " + ring1.gender);

		Ring ring2 = new Ring();
		ring2.id = 2;
		ring2.brand = "Malabar";
		ring2.price = 15000;
		ring2.colour = "Gold";
		ring2.material = "Gold";
		ring2.size = "14";
		ring2.design = "Stone";
		ring2.gender = "Women";
		System.out.println("ring id is " + ring2.id);
		System.out.println("brand is " + ring2.brand);
		System.out.println("price is " + ring2.price);
		System.out.println("colour is " + ring2.colour);
		System.out.println("material is " + ring2.material);
		System.out.println("size is " + ring2.size);
		System.out.println("design is " + ring2.design);
		System.out.println("gender is " + ring2.gender);

		Ring ring3 = new Ring();
		ring3.id = 3;
		ring3.brand = "Giva";
		ring3.price = 2500;
		ring3.colour = "Silver";
		ring3.material = "Silver";
		ring3.size = "13";
		ring3.design = "Designer";
		ring3.gender = "Women";
		System.out.println("ring id is " + ring3.id);
		System.out.println("brand is " + ring3.brand);
		System.out.println("price is " + ring3.price);
		System.out.println("colour is " + ring3.colour);
		System.out.println("material is " + ring3.material);
		System.out.println("size is " + ring3.size);
		System.out.println("design is " + ring3.design);
		System.out.println("gender is " + ring3.gender);
		
		Ring ring4 = new Ring();
		ring4.id = 4;
		ring4.brand = "Tanishq";
		ring4.price = 18000;
		ring4.colour = "Gold";
		ring4.material = "Gold";
		ring4.size = "15";
		ring4.design = "Stone";
		ring4.gender = "Women";
		System.out.println("ring id is " + ring4.id);
		System.out.println("brand is " + ring4.brand);
		System.out.println("price is " + ring4.price);
		System.out.println("colour is " + ring4.colour);
		System.out.println("material is " + ring4.material);
		System.out.println("size is " + ring4.size);
		System.out.println("design is " + ring4.design);
		System.out.println("gender is " + ring4.gender);

		Ring ring5 = new Ring();
		ring5.id = 5;
		ring5.brand = "Malabar";
		ring5.price = 20000;
		ring5.colour = "Gold";
		ring5.material = "Gold";
		ring5.size = "16";
		ring5.design = "Designer";
		ring5.gender = "Women";
		System.out.println("ring id is " + ring5.id);
		System.out.println("brand is " + ring5.brand);
		System.out.println("price is " + ring5.price);
		System.out.println("colour is " + ring5.colour);
		System.out.println("material is " + ring5.material);
		System.out.println("size is " + ring5.size);
		System.out.println("design is " + ring5.design);
		System.out.println("gender is " + ring5.gender);

		Ring ring6 = new Ring();
		ring6.id = 6;
		ring6.brand = "Giva";
		ring6.price = 3000;
		ring6.colour = "Silver";
		ring6.material = "Silver";
		ring6.size = "14";
		ring6.design = "Plain";
		ring6.gender = "Women";
		System.out.println("ring id is " + ring6.id);
		System.out.println("brand is " + ring6.brand);
		System.out.println("price is " + ring6.price);
		System.out.println("colour is " + ring6.colour);
		System.out.println("material is " + ring6.material);
		System.out.println("size is " + ring6.size);
		System.out.println("design is " + ring6.design);
		System.out.println("gender is " + ring6.gender);

		Ring ring7 = new Ring();
		ring7.id = 7;
		ring7.brand = "Tanishq";
		ring7.price = 22000;
		ring7.colour = "Gold";
		ring7.material = "Gold";
		ring7.size = "17";
		ring7.design = "Stone";
		ring7.gender = "Women";
		System.out.println("ring id is " + ring7.id);
		System.out.println("brand is " + ring7.brand);
		System.out.println("price is " + ring7.price);
		System.out.println("colour is " + ring7.colour);
		System.out.println("material is " + ring7.material);
		System.out.println("size is " + ring7.size);
		System.out.println("design is " + ring7.design);
		System.out.println("gender is " + ring7.gender);

		Ring ring8 = new Ring();
		ring8.id = 8;
		ring8.brand = "Malabar";
		ring8.price = 24000;
		ring8.colour = "Gold";
		ring8.material = "Gold";
		ring8.size = "18";
		ring8.design = "Designer";
		ring8.gender = "Women";
		System.out.println("ring id is " + ring8.id);
		System.out.println("brand is " + ring8.brand);
		System.out.println("price is " + ring8.price);
		System.out.println("colour is " + ring8.colour);
		System.out.println("material is " + ring8.material);
		System.out.println("size is " + ring8.size);
		System.out.println("design is " + ring8.design);
		System.out.println("gender is " + ring8.gender);

		Ring ring9 = new Ring();
		ring9.id = 9;
		ring9.brand = "Giva";
		ring9.price = 3500;
		ring9.colour = "Silver";
		ring9.material = "Silver";
		ring9.size = "13";
		ring9.design = "Designer";
		ring9.gender = "Women";

		System.out.println("ring id is " + ring9.id);
		System.out.println("brand is " + ring9.brand);
		System.out.println("price is " + ring9.price);
		System.out.println("colour is " + ring9.colour);
		System.out.println("material is " + ring9.material);
		System.out.println("size is " + ring9.size);
		System.out.println("design is " + ring9.design);
		System.out.println("gender is " + ring9.gender);
		
		Ring ring10 = new Ring();
		ring10.id = 10;
		ring10.brand = "Malabar";
		ring10.price = 26000;
		ring10.colour = "Gold";
		ring10.material = "Gold";
		ring10.size = "19";
		ring10.design = "Stone";
		ring10.gender = "Women";

		System.out.println("ring id is " + ring10.id);
		System.out.println("brand is " + ring10.brand);
		System.out.println("price is " + ring10.price);
		System.out.println("colour is " + ring10.colour);
		System.out.println("material is " + ring10.material);
		System.out.println("size is " + ring10.size);
		System.out.println("design is " + ring10.design);
		System.out.println("gender is " + ring10.gender);

		Ring ring11 = new Ring();
		ring11.id = 11;
		ring11.brand = "Giva";
		ring11.price = 3200;
		ring11.colour = "Silver";
		ring11.material = "Silver";
		ring11.size = "14";
		ring11.design = "Plain";
		ring11.gender = "Women";
		System.out.println("ring id is " + ring11.id);
		System.out.println("brand is " + ring11.brand);
		System.out.println("price is " + ring11.price);
		System.out.println("colour is " + ring11.colour);
		System.out.println("material is " + ring11.material);
		System.out.println("size is " + ring11.size);
		System.out.println("design is " + ring11.design);
		System.out.println("gender is " + ring11.gender);

		Ring ring12 = new Ring();
		ring12.id = 12;
		ring12.brand = "Tanishq";
		ring12.price = 28000;
		ring12.colour = "Gold";
		ring12.material = "Gold";
		ring12.size = "18";
		ring12.design = "Designer";
		ring12.gender = "Women";
		System.out.println("ring id is " + ring12.id);
		System.out.println("brand is " + ring12.brand);
		System.out.println("price is " + ring12.price);
		System.out.println("colour is " + ring12.colour);
		System.out.println("material is " + ring12.material);
		System.out.println("size is " + ring12.size);
		System.out.println("design is " + ring12.design);
		System.out.println("gender is " + ring12.gender);

		Ring ring13 = new Ring();
		ring13.id = 13;
		ring13.brand = "Malabar";
		ring13.price = 27000;
		ring13.colour = "Gold";
		ring13.material = "Gold";
		ring13.size = "17";
		ring13.design = "Stone";
		ring13.gender = "Women";
		System.out.println("ring id is " + ring13.id);
		System.out.println("brand is " + ring13.brand);
		System.out.println("price is " + ring13.price);
		System.out.println("colour is " + ring13.colour);
		System.out.println("material is " + ring13.material);
		System.out.println("size is " + ring13.size);
		System.out.println("design is " + ring13.design);
		System.out.println("gender is " + ring13.gender);

		Ring ring14 = new Ring();
		ring14.id = 14;
		ring14.brand = "Giva";
		ring14.price = 3500;
		ring14.colour = "Silver";
		ring14.material = "Silver";
		ring14.size = "13";
		ring14.design = "Designer";
		ring14.gender = "Women";
		System.out.println("ring id is " + ring14.id);
		System.out.println("brand is " + ring14.brand);
		System.out.println("price is " + ring14.price);
		System.out.println("colour is " + ring14.colour);
		System.out.println("material is " + ring14.material);
		System.out.println("size is " + ring14.size);
		System.out.println("design is " + ring14.design);
		System.out.println("gender is " + ring14.gender);

		Ring ring15 = new Ring();
		ring15.id = 15;
		ring15.brand = "Tanishq";
		ring15.price = 30000;
		ring15.colour = "Gold";
		ring15.material = "Gold";
		ring15.size = "20";
		ring15.design = "Stone";
		ring15.gender = "Women";
		System.out.println("ring id is " + ring15.id);
		System.out.println("brand is " + ring15.brand);
		System.out.println("price is " + ring15.price);
		System.out.println("colour is " + ring15.colour);
		System.out.println("material is " + ring15.material);
		System.out.println("size is " + ring15.size);
		System.out.println("design is " + ring15.design);
		System.out.println("gender is " + ring15.gender);

		Ring ring16 = new Ring();
		ring16.id = 16;
		ring16.brand = "Malabar";
		ring16.price = 31000;
		ring16.colour = "Gold";
		ring16.material = "Gold";
		ring16.size = "19";
		ring16.design = "Designer";
		ring16.gender = "Women";
		System.out.println("ring id is " + ring16.id);
		System.out.println("brand is " + ring16.brand);
		System.out.println("price is " + ring16.price);
		System.out.println("colour is " + ring16.colour);
		System.out.println("material is " + ring16.material);
		System.out.println("size is " + ring16.size);
		System.out.println("design is " + ring16.design);
		System.out.println("gender is " + ring16.gender);

		Ring ring17 = new Ring();
		ring17.id = 17;
		ring17.brand = "Giva";
		ring17.price = 3700;
		ring17.colour = "Silver";
		ring17.material = "Silver";
		ring17.size = "14";
		ring17.design = "Plain";
		ring17.gender = "Women";
		System.out.println("ring id is " + ring17.id);
		System.out.println("brand is " + ring17.brand);
		System.out.println("price is " + ring17.price);
		System.out.println("colour is " + ring17.colour);
		System.out.println("material is " + ring17.material);
		System.out.println("size is " + ring17.size);
		System.out.println("design is " + ring17.design);
		System.out.println("gender is " + ring17.gender);

		Ring ring18 = new Ring();
		ring18.id = 18;
		ring18.brand = "Tanishq";
		ring18.price = 33000;
		ring18.colour = "Gold";
		ring18.material = "Gold";
		ring18.size = "21";
		ring18.design = "Designer";
		ring18.gender = "Women";
		System.out.println("ring id is " + ring18.id);
		System.out.println("brand is " + ring18.brand);
		System.out.println("price is " + ring18.price);
		System.out.println("colour is " + ring18.colour);
		System.out.println("material is " + ring18.material);
		System.out.println("size is " + ring18.size);
		System.out.println("design is " + ring18.design);
		System.out.println("gender is " + ring18.gender);

		Ring ring19 = new Ring();
		ring19.id = 19;
		ring19.brand = "Malabar";
		ring19.price = 29000;
		ring19.colour = "Gold";
		ring19.material = "Gold";
		ring19.size = "18";
		ring19.design = "Stone";
		ring19.gender = "Women";
		System.out.println("ring id is " + ring19.id);
		System.out.println("brand is " + ring19.brand);
		System.out.println("price is " + ring19.price);
		System.out.println("colour is " + ring19.colour);
		System.out.println("material is " + ring19.material);
		System.out.println("size is " + ring19.size);
		System.out.println("design is " + ring19.design);
		System.out.println("gender is " + ring19.gender);

		Ring ring20 = new Ring();
		ring20.id = 20;
		ring20.brand = "Giva";
		ring20.price = 4000;
		ring20.colour = "Silver";
		ring20.material = "Silver";
		ring20.size = "15";
		ring20.design = "Designer";
		ring20.gender = "Women";
		System.out.println("ring id is " + ring20.id);
		System.out.println("brand is " + ring20.brand);
		System.out.println("price is " + ring20.price);
		System.out.println("colour is " + ring20.colour);
		System.out.println("material is " + ring20.material);
		System.out.println("size is " + ring20.size);
		System.out.println("design is " + ring20.design);
		System.out.println("gender is " + ring20.gender);

		Ring ring21 = new Ring();
		ring21.id = 21;
		ring21.brand = "Tanishq";
		ring21.price = 34000;
		ring21.colour = "Gold";
		ring21.material = "Gold";
		ring21.size = "22";
		ring21.design = "Stone";
		ring21.gender = "Women";
		System.out.println("ring id is " + ring21.id);
		System.out.println("brand is " + ring21.brand);
		System.out.println("price is " + ring21.price);
		System.out.println("colour is " + ring21.colour);
		System.out.println("material is " + ring21.material);
		System.out.println("size is " + ring21.size);
		System.out.println("design is " + ring21.design);
		System.out.println("gender is " + ring21.gender);

		Ring ring22 = new Ring();
		ring22.id = 22;
		ring22.brand = "Malabar";
		ring22.price = 36000;
		ring22.colour = "Gold";
		ring22.material = "Gold";
		ring22.size = "21";
		ring22.design = "Designer";
		ring22.gender = "Women";
		System.out.println("ring id is " + ring22.id);
		System.out.println("brand is " + ring22.brand);
		System.out.println("price is " + ring22.price);
		System.out.println("colour is " + ring22.colour);
		System.out.println("material is " + ring22.material);
		System.out.println("size is " + ring22.size);
		System.out.println("design is " + ring22.design);
		System.out.println("gender is " + ring22.gender);

		Ring ring23 = new Ring();
		ring23.id = 23;
		ring23.brand = "Giva";
		ring23.price = 4200;
		ring23.colour = "Silver";
		ring23.material = "Silver";
		ring23.size = "16";
		ring23.design = "Plain";
		ring23.gender = "Women";
		System.out.println("ring id is " + ring23.id);
		System.out.println("brand is " + ring23.brand);
		System.out.println("price is " + ring23.price);
		System.out.println("colour is " + ring23.colour);
		System.out.println("material is " + ring23.material);
		System.out.println("size is " + ring23.size);
		System.out.println("design is " + ring23.design);
		System.out.println("gender is " + ring23.gender);

		Ring ring24 = new Ring();
		ring24.id = 24;
		ring24.brand = "Tanishq";
		ring24.price = 37000;
		ring24.colour = "Gold";
		ring24.material = "Gold";
		ring24.size = "23";
		ring24.design = "Designer";
		ring24.gender = "Women";
		System.out.println("ring id is " + ring24.id);
		System.out.println("brand is " + ring24.brand);
		System.out.println("price is " + ring24.price);
		System.out.println("colour is " + ring24.colour);
		System.out.println("material is " + ring24.material);
		System.out.println("size is " + ring24.size);
		System.out.println("design is " + ring24.design);
		System.out.println("gender is " + ring24.gender);

		Ring ring25 = new Ring();
		ring25.id = 25;
		ring25.brand = "Malabar";
		ring25.price = 38000;
		ring25.colour = "Gold";
		ring25.material = "Gold";
		ring25.size = "22";
		ring25.design = "Stone";
		ring25.gender = "Women";
		System.out.println("ring id is " + ring25.id);
		System.out.println("brand is " + ring25.brand);
		System.out.println("price is " + ring25.price);
		System.out.println("colour is " + ring25.colour);
		System.out.println("material is " + ring25.material);
		System.out.println("size is " + ring25.size);
		System.out.println("design is " + ring25.design);
		System.out.println("gender is " + ring25.gender);

		Ring ring26 = new Ring();
		ring26.id = 26;
		ring26.brand = "Giva";
		ring26.price = 4500;
		ring26.colour = "Silver";
		ring26.material = "Silver";
		ring26.size = "17";
		ring26.design = "Designer";
		ring26.gender = "Women";
		System.out.println("ring id is " + ring26.id);
		System.out.println("brand is " + ring26.brand);
		System.out.println("price is " + ring26.price);
		System.out.println("colour is " + ring26.colour);
		System.out.println("material is " + ring26.material);
		System.out.println("size is " + ring26.size);
		System.out.println("design is " + ring26.design);
		System.out.println("gender is " + ring26.gender);

		Ring ring27 = new Ring();
		ring27.id = 27;
		ring27.brand = "Tanishq";
		ring27.price = 39000;
		ring27.colour = "Gold";
		ring27.material = "Gold";
		ring27.size = "24";
		ring27.design = "Stone";
		ring27.gender = "Women";
		System.out.println("ring id is " + ring27.id);
		System.out.println("brand is " + ring27.brand);
		System.out.println("price is " + ring27.price);
		System.out.println("colour is " + ring27.colour);
		System.out.println("material is " + ring27.material);
		System.out.println("size is " + ring27.size);
		System.out.println("design is " + ring27.design);
		System.out.println("gender is " + ring27.gender);

		Ring ring28 = new Ring();
		ring28.id = 28;
		ring28.brand = "Malabar";
		ring28.price = 40000;
		ring28.colour = "Gold";
		ring28.material = "Gold";
		ring28.size = "23";
		ring28.design = "Designer";
		ring28.gender = "Women";
		System.out.println("ring id is " + ring28.id);
		System.out.println("brand is " + ring28.brand);
		System.out.println("price is " + ring28.price);
		System.out.println("colour is " + ring28.colour);
		System.out.println("material is " + ring28.material);
		System.out.println("size is " + ring28.size);
		System.out.println("design is " + ring28.design);
		System.out.println("gender is " + ring28.gender);

		Ring ring29 = new Ring();
		ring29.id = 29;
		ring29.brand = "Giva";
		ring29.price = 4800;
		ring29.colour = "Silver";
		ring29.material = "Silver";
		ring29.size = "18";
		ring29.design = "Plain";
		ring29.gender = "Women";
		System.out.println("ring id is " + ring29.id);
		System.out.println("brand is " + ring29.brand);
		System.out.println("price is " + ring29.price);
		System.out.println("colour is " + ring29.colour);
		System.out.println("material is " + ring29.material);
		System.out.println("size is " + ring29.size);
		System.out.println("design is " + ring29.design);
		System.out.println("gender is " + ring29.gender);

		Ring ring30 = new Ring();
		ring30.id = 30;
		ring30.brand = "Tanishq";
		ring30.price = 42000;
		ring30.colour = "Gold";
		ring30.material = "Gold";
		ring30.size = "25";
		ring30.design = "Designer";
		ring30.gender = "Women";
		System.out.println("ring id is " + ring30.id);
		System.out.println("brand is " + ring30.brand);
		System.out.println("price is " + ring30.price);
		System.out.println("colour is " + ring30.colour);
		System.out.println("material is " + ring30.material);
		System.out.println("size is " + ring30.size);
		System.out.println("design is " + ring30.design);
		System.out.println("gender is " + ring30.gender);
	}
	
}





