class ShoesExecuter{
	public static void main(String[] args){

		Shoes shoe1 = new Shoe();
		shoe1.id=1;
		shoe1.brand="Nike"; 
		shoe1.price=2500; 
		shoe1.colour="Black"; 
		shoe1.size=6; 
		shoe1.material="Mesh"; 
		shoe1.type="Sports"; 
		shoe1.gender="Women";
		System.out.println("shoe id is "+shoe1.id);
		System.out.println("brand is "+shoe1.brand);
		System.out.println("price is "+shoe1.price);
		System.out.println("colour is "+shoe1.colour);
		System.out.println("size is "+shoe1.size);
		System.out.println("material is "+shoe1.material);
		System.out.println("type is "+shoe1.type);
		System.out.println("gender is "+shoe1.gender);

		Shoes shoe2 = new Shoes();
		shoe2.id=2; 
		shoe2.brand="Puma";
		shoe2.price=2700; 
		shoe2.colour="White";
		shoe2.size=7;
		shoe2.material="Leather";
		shoe2.type="Casual";
		shoe2.gender="Men";
		System.out.println("shoe id is "+shoe2.id);
		System.out.println("brand is "+shoe2.brand);
		System.out.println("price is "+shoe2.price);
		System.out.println("colour is "+shoe2.colour);
		System.out.println("size is "+shoe2.size);
		System.out.println("material is "+shoe2.material);
		System.out.println("type is "+shoe2.type);
		System.out.println("gender is "+shoe2.gender);

		Shoes shoe3 = new Shoes();
		shoe3.id=3;
		shoe3.brand="Adidas";
		shoe3.price=3000; 
		shoe3.colour="Blue";
		shoe3.size=8;
		shoe3.material="Mesh";
		shoe3.type="Running"; 
		shoe3.gender="Unisex";
		System.out.println("shoe id is "+shoe3.id);
		System.out.println("brand is "+shoe3.brand);
		System.out.println("price is "+shoe3.price);
		System.out.println("colour is "+shoe3.colour);
		System.out.println("size is "+shoe3.size);
		System.out.println("material is "+shoe3.material);
		System.out.println("type is "+shoe3.type);
		System.out.println("gender is "+shoe3.gender);

		Shoes shoe4 = new Shoes();
		shoe4.id=4;
		shoe4.brand="Reebok"; 
		shoe4.price=2200; 
		shoe4.colour="Grey";
		shoe4.size=6; 
		shoe4.material="Synthetic";
		shoe4.type="Sports";
		shoe4.gender="Women";
		System.out.println("shoe id is "+shoe4.id);
		System.out.println("brand is "+shoe4.brand);
		System.out.println("price is "+shoe4.price);
		System.out.println("colour is "+shoe4.colour);
		System.out.println("size is "+shoe4.size);
		System.out.println("material is "+shoe4.material);
		System.out.println("type is "+shoe4.type);
		System.out.println("gender is "+shoe4.gender);


		Shoes shoe5 = new Shoes();
		shoe5.id=5;
		shoe5.brand="Sparx";
		shoe5.price=1500;
		shoe5.colour="Black";
		shoe5.size=9;
		shoe5.material="Rubber";
		shoe5.type="Casual";
		shoe5.gender="Men";
		System.out.println("shoe id is "+shoe5.id);
		System.out.println("brand is "+shoe5.brand);
		System.out.println("price is "+shoe5.price);
		System.out.println("colour is "+shoe5.colour);
		System.out.println("size is "+shoe5.size);
		System.out.println("material is "+shoe5.material);
		System.out.println("type is "+shoe5.type);
		System.out.println("gender is "+shoe5.gender);

		Shoes shoe6 = new Shoes();
		shoe6.id=6;
		shoe6.brand="Woodland";
		shoe6.price=3500; 
		shoe6.colour="Brown";
		shoe6.size=8;
		shoe6.material="Leather";
		shoe6.type="Boot"; 
		shoe6.gender="Men";
		System.out.println("shoe id is "+shoe6.id);
		System.out.println("brand is "+shoe6.brand);
		System.out.println("price is "+shoe6.price);
		System.out.println("colour is "+shoe6.colour);
		System.out.println("size is "+shoe6.size);
		System.out.println("material is "+shoe6.material);
		System.out.println("type is "+shoe6.type);
		System.out.println("gender is "+shoe6.gender);

		Shoes shoe7 = new Shoes();
		shoe7.id=7; 
		shoe7.brand="Campus"; 
		shoe7.price=1800;
		shoe7.colour="White";
		shoe7.size=7; 
		shoe7.material="Mesh";
		shoe7.type="Sports"; 
		shoe7.gender="Women";
		System.out.println("shoe id is "+shoe7.id);
		System.out.println("brand is "+shoe7.brand);
		System.out.println("price is "+shoe7.price);
		System.out.println("colour is "+shoe7.colour);
		System.out.println("size is "+shoe7.size);
		System.out.println("material is "+shoe7.material);
		System.out.println("type is "+shoe7.type);
		System.out.println("gender is "+shoe7.gender);

		Shoes shoe8 = new Shoes();
		shoe8.id=8;
		shoe8.brand="Bata";
		shoe8.price=2000;
		shoe8.colour="Black";
		shoe8.size=8;
		shoe8.material="Leather"; 
		shoe8.type="Formal";
		shoe8.gender="Men";
		System.out.println("shoe id is "+shoe8.id);
		System.out.println("brand is "+shoe8.brand);
		System.out.println("price is "+shoe8.price);
		System.out.println("colour is "+shoe8.colour);
		System.out.println("size is "+shoe8.size);
		System.out.println("material is "+shoe8.material);
		System.out.println("type is "+shoe8.type);
		System.out.println("gender is "+shoe8.gender);

		Shoes shoe9 = new Shoes();
		shoe9.id=9;
		shoe9.brand="RedTape";
		shoe9.price=3200; 
		shoe9.colour="Brown";
		shoe9.size=9; 
		shoe9.material="Leather";
		shoe9.type="Casual";
		shoe9.gender="Men";
		System.out.println("shoe id is "+shoe9.id);
		System.out.println("brand is "+shoe9.brand);
		System.out.println("price is "+shoe9.price);
		System.out.println("colour is "+shoe9.colour);
		System.out.println("size is "+shoe9.size);
		System.out.println("material is "+shoe9.material);
		System.out.println("type is "+shoe9.type);
		System.out.println("gender is "+shoe9.gender);

		Shoes shoe10 = new Shoes();
		shoe10.id=10;
		shoe10.brand="Liberty";
		shoe10.price=2100;
		shoe10.colour="Blue";
		shoe10.size=6;
		shoe10.material="Synthetic";
		shoe10.type="Sports"; 
		shoe10.gender="Women";
		System.out.println("shoe id is "+shoe10.id);
		System.out.println("brand is "+shoe10.brand);
		System.out.println("price is "+shoe10.price);
		System.out.println("colour is "+shoe10.colour);
		System.out.println("size is "+shoe10.size);
		System.out.println("material is "+shoe10.material);
		System.out.println("type is "+shoe10.type);
		System.out.println("gender is "+shoe10.gender);

		Shoes shoe11 = new Shoes();
		shoe11.id=11;
		shoe11.brand="Nike";
		shoe11.price=2600;
		shoe11.colour="Pink";
		shoe11.size=5; 
		shoe11.material="Mesh";
		shoe11.type="Running";
		shoe11.gender="Women";
		System.out.println("shoe id is "+shoe11.id);
		System.out.println("brand is "+shoe11.brand);
		System.out.println("price is "+shoe11.price);
		System.out.println("colour is "+shoe11.colour);
		System.out.println("size is "+shoe11.size);
		System.out.println("material is "+shoe11.material);
		System.out.println("type is "+shoe11.type);
		System.out.println("gender is "+shoe11.gender);

		Shoes shoe12 = new Shoes();
		shoe12.id=12;
		shoe12.brand="Puma";
		shoe12.price=2900;
		shoe12.colour="Green";
		shoe12.size=8;
		shoe12.material="Mesh";
		shoe12.type="Sports";
		shoe12.gender="Men";
		System.out.println("shoe id is "+shoe12.id);
		System.out.println("brand is "+shoe12.brand);
		System.out.println("price is "+shoe12.price);
		System.out.println("colour is "+shoe12.colour);
		System.out.println("size is "+shoe12.size);
		System.out.println("material is "+shoe12.material);
		System.out.println("type is "+shoe12.type);
		System.out.println("gender is "+shoe12.gender);

		Shoes shoe13 = new Shoes();
		shoe13.id=13;
		shoe13.brand="Adidas"; 
		shoe13.price=3100;
		shoe13.colour="Black"; 
		shoe13.size=9;
		shoe13.material="Leather"; 
		shoe13.type="Casual";
		shoe13.gender="Unisex";
		System.out.println("shoe id is "+shoe13.id);
		System.out.println("brand is "+shoe13.brand);
		System.out.println("price is "+shoe13.price);
		System.out.println("colour is "+shoe13.colour);
		System.out.println("size is "+shoe13.size);
		System.out.println("material is "+shoe13.material);
		System.out.println("type is "+shoe13.type);
		System.out.println("gender is "+shoe13.gender);

		Shoes shoe14 = new Shoes();
		shoe14.id=14;
		shoe14.brand="Reebok";
		shoe14.price=2400; 
		shoe14.colour="White"; 
		shoe14.size=7;
		shoe14.material="Synthetic";
		shoe14.type="Running";
		shoe14.gender="Women";
		System.out.println("shoe id is "+shoe14.id);
		System.out.println("brand is "+shoe14.brand);
		System.out.println("price is "+shoe14.price);
		System.out.println("colour is "+shoe14.colour);
		System.out.println("size is "+shoe14.size);
		System.out.println("material is "+shoe14.material);
		System.out.println("type is "+shoe14.type);
		System.out.println("gender is "+shoe14.gender);


		Shoes shoe15 = new Shoes();
		shoe15.id=15; 
		shoe15.brand="Sparx"; 
		shoe15.price=1600; 
		shoe15.colour="Grey";
		shoe15.size=8; 
		shoe15.material="Rubber"; 
		shoe15.type="Casual";
		shoe15.gender="Men";
		System.out.println("shoe id is "+shoe15.id);
		System.out.println("brand is "+shoe15.brand);
		System.out.println("price is "+shoe15.price);
		System.out.println("colour is "+shoe15.colour);
		System.out.println("size is "+shoe15.size);
		System.out.println("material is "+shoe15.material);
		System.out.println("type is "+shoe15.type);
		System.out.println("gender is "+shoe15.gender);

		Shoes shoe16 = new Shoes();
		shoe16.id=16;
		shoe16.brand="Woodland";
		shoe16.price=3700;
		shoe16.colour="Brown";
		shoe16.size=9;
		shoe16.material="Leather";
		shoe16.type="Boot";
		shoe16.gender="Men";
		System.out.println("shoe id is "+shoe16.id);
		System.out.println("brand is "+shoe16.brand);
		System.out.println("price is "+shoe16.price);
		System.out.println("colour is "+shoe16.colour);
		System.out.println("size is "+shoe16.size);
		System.out.println("material is "+shoe16.material);
		System.out.println("type is "+shoe16.type);
		System.out.println("gender is "+shoe16.gender);

		Shoes shoe17 = new Shoes();
		shoe17.id=17;
		shoe17.brand="Campus";
		shoe17.price=1900;
		shoe17.colour="Blue";
		shoe17.size=6;
		shoe17.material="Mesh";
		shoe17.type="Sports";
		shoe17.gender="Women";
		System.out.println("shoe id is "+shoe17.id);
		System.out.println("brand is "+shoe17.brand);
		System.out.println("price is "+shoe17.price);
		System.out.println("colour is "+shoe17.colour);
		System.out.println("size is "+shoe17.size);
		System.out.println("material is "+shoe17.material);
		System.out.println("type is "+shoe17.type);
		System.out.println("gender is "+shoe17.gender);

		Shoes shoe18 = new Shoes();
		shoe18.id=18;
		shoe18.brand="Bata";
		shoe18.price=2200;
		shoe18.colour="Black";
		shoe18.size=8;
		shoe18.material="Leather";
		shoe18.type="Formal";
		shoe18.gender="Men";
		System.out.println("shoe id is "+shoe18.id);
		System.out.println("brand is "+shoe18.brand);
		System.out.println("price is "+shoe18.price);
		System.out.println("colour is "+shoe18.colour);
		System.out.println("size is "+shoe18.size);
		System.out.println("material is "+shoe18.material);
		System.out.println("type is "+shoe18.type);
		System.out.println("gender is "+shoe18.gender);

		Shoes shoe19 = new Shoes();
		shoe19.id=19;
		shoe19.brand="RedTape"; 
		shoe19.price=3300; 
		shoe19.colour="Brown";
		shoe19.size=9; 
		shoe19.material="Leather";
		shoe19.type="Casual";
		shoe19.gender="Men";
		System.out.println("shoe id is "+shoe19.id);
		System.out.println("brand is "+shoe19.brand);
		System.out.println("price is "+shoe19.price);
		System.out.println("colour is "+shoe19.colour);
		System.out.println("size is "+shoe19.size);
		System.out.println("material is "+shoe19.material);
		System.out.println("type is "+shoe19.type);
		System.out.println("gender is "+shoe19.gender);

		Shoes shoe20 = new Shoes();
		shoe20.id=20;
		shoe20.brand="Liberty";
		shoe20.price=2300;
		shoe20.colour="White";
		shoe20.size=7; 
		shoe20.material="Synthetic";
		shoe20.type="Sports";
		shoe20.gender="Women";
		System.out.println("shoe id is "+shoe20.id);
		System.out.println("brand is "+shoe20.brand);
		System.out.println("price is "+shoe20.price);
		System.out.println("colour is "+shoe20.colour);
		System.out.println("size is "+shoe20.size);
		System.out.println("material is "+shoe20.material);
		System.out.println("type is "+shoe20.type);
		System.out.println("gender is "+shoe20.gender);

		Shoes shoe21 = new Shoes();
		shoe21.id=21;
		shoe21.brand="Nike";
		shoe21.price=2800;
		shoe21.colour="Black";
		shoe21.size=8;
		shoe21.material="Mesh";
		shoe21.type="Running";
		shoe21.gender="Men";
		System.out.println("shoe id is "+shoe21.id);
		System.out.println("brand is "+shoe21.brand);
		System.out.println("price is "+shoe21.price);
		System.out.println("colour is "+shoe21.colour);
		System.out.println("size is "+shoe21.size);
		System.out.println("material is "+shoe21.material);
		System.out.println("type is "+shoe21.type);
		System.out.println("gender is "+shoe21.gender);

		Shoes shoe22 = new Shoes();
		shoe22.id=22;
		shoe22.brand="Puma";
		shoe22.price=3000;
		shoe22.colour="Grey";
		shoe22.size=9;
		shoe22.material="Mesh";
		shoe22.type="Sports";
		shoe22.gender="Unisex";
		System.out.println("shoe id is "+shoe22.id);
		System.out.println("brand is "+shoe22.brand);
		System.out.println("price is "+shoe22.price);
		System.out.println("colour is "+shoe22.colour);
		System.out.println("size is "+shoe22.size);
		System.out.println("material is "+shoe22.material);
		System.out.println("type is "+shoe22.type);
		System.out.println("gender is "+shoe22.gender);

		Shoes shoe23 = new Shoes();
		shoe23.id=23;
		shoe23.brand="Adidas";
		shoe23.price=3500; 
		shoe23.colour="White";
		shoe23.size=7; 
		shoe23.material="Leather";
		shoe23.type="Casual";
		shoe23.gender="Women";
		System.out.println("shoe id is "+shoe23.id);
		System.out.println("brand is "+shoe23.brand);
		System.out.println("price is "+shoe23.price);
		System.out.println("colour is "+shoe23.colour);
		System.out.println("size is "+shoe23.size);
		System.out.println("material is "+shoe23.material);
		System.out.println("type is "+shoe23.type);
		System.out.println("gender is "+shoe23.gender);

		Shoes shoe24 = new Shoes();
		shoe24.id=24;
		shoe24.brand="Reebok";
		shoe24.price=2600;
		shoe24.colour="Blue";
		shoe24.size=8;
		shoe24.material="Synthetic";
		shoe24.type="Running"; 
		shoe24.gender="Men";
		System.out.println("shoe id is "+shoe24.id);
		System.out.println("brand is "+shoe24.brand);
		System.out.println("price is "+shoe24.price);
		System.out.println("colour is "+shoe24.colour);
		System.out.println("size is "+shoe24.size);
		System.out.println("material is "+shoe24.material);
		System.out.println("type is "+shoe24.type);
		System.out.println("gender is "+shoe24.gender);

		Shoes shoe25 = new Shoes();
		shoe25.id=25;
		shoe25.brand="Sparx";
		shoe25.price=1700;
		shoe25.colour="Black";
		shoe25.size=9;
		shoe25.material="Rubber"; 
		shoe25.type="Casual"; 
		shoe25.gender="Men";
		System.out.println("shoe id is "+shoe25.id);
		System.out.println("brand is "+shoe25.brand);
		System.out.println("price is "+shoe25.price);
		System.out.println("colour is "+shoe25.colour);
		System.out.println("size is "+shoe25.size);
		System.out.println("material is "+shoe25.material);
		System.out.println("type is "+shoe25.type);
		System.out.println("gender is "+shoe25.gender);

		Shoes shoe26 = new Shoes();
		shoe26.id=26;
		shoe26.brand="Woodland";
		shoe26.price=3900; 
		shoe26.colour="Brown";
		shoe26.size=10;
		shoe26.material="Leather"; 
		shoe26.type="Boot";
		shoe26.gender="Men";
		System.out.println("shoe id is "+shoe26.id);
		System.out.println("brand is "+shoe26.brand);
		System.out.println("price is "+shoe26.price);
		System.out.println("colour is "+shoe26.colour);
		System.out.println("size is "+shoe26.size);
		System.out.println("material is "+shoe26.material);
		System.out.println("type is "+shoe26.type);
		System.out.println("gender is "+shoe26.gender);

		Shoes shoe27 = new Shoes();
		shoe27.id=27;
		shoe27.brand="Campus";
		shoe27.price=2000;
		shoe27.colour="Pink";
		shoe27.size=6; 
		shoe27.material="Mesh"; 
		shoe27.type="Sports";
		shoe27.gender="Women";
		System.out.println("shoe id is "+shoe27.id);
		System.out.println("brand is "+shoe27.brand);
		System.out.println("price is "+shoe27.price);
		System.out.println("colour is "+shoe27.colour);
		System.out.println("size is "+shoe27.size);
		System.out.println("material is "+shoe27.material);
		System.out.println("type is "+shoe27.type);
		System.out.println("gender is "+shoe27.gender);

		Shoes shoe28 = new Shoes();
		shoe28.id=28;
		shoe28.brand="Bata";
		shoe28.price=2400;
		shoe28.colour="Black";
		shoe28.size=8;
		shoe28.material="Leather";
		shoe28.type="Formal";
		shoe28.gender="Men";
		System.out.println("shoe id is "+shoe28.id);
		System.out.println("brand is "+shoe28.brand);
		System.out.println("price is "+shoe28.price);
		System.out.println("colour is "+shoe28.colour);
		System.out.println("size is "+shoe28.size);
		System.out.println("material is "+shoe28.material);
		System.out.println("type is "+shoe28.type);
		System.out.println("gender is "+shoe28.gender);

		Shoes shoe29 = new Shoes();
		shoe29.id=29;
		shoe29.brand="RedTape";
		shoe29.price=3400;
		shoe29.colour="Brown";
		shoe29.size=9;
		shoe29.material="Leather";
		shoe29.type="Casual"; 
		shoe29.gender="Men";
		System.out.println("shoe id is "+shoe29.id);
		System.out.println("brand is "+shoe29.brand);
		System.out.println("price is "+shoe29.price);
		System.out.println("colour is "+shoe29.colour);
		System.out.println("size is "+shoe29.size);
		System.out.println("material is "+shoe29.material);
		System.out.println("type is "+shoe29.type);
		System.out.println("gender is "+shoe29.gender);

		Shoes shoe30 = new Shoes();
		shoe30.id=30;
		shoe30.brand="Liberty";
		shoe30.price=2500; 
		shoe30.colour="White";
		shoe30.size=7;
		shoe30.material="Synthetic";
		shoe30.type="Sports";
		shoe30.gender="Women";
		System.out.println("shoe id is "+shoe30.id);
		System.out.println("brand is "+shoe30.brand);
		System.out.println("price is "+shoe30.price);
		System.out.println("colour is "+shoe30.colour);
		System.out.println("size is "+shoe30.size);
		System.out.println("material is "+shoe30.material);
		System.out.println("type is "+shoe30.type);
		System.out.println("gender is "+shoe30.gender);

	}
}