class StudyTableExecuter{
	public static void main(String[] args){

		StudyTable studyTable1 = new StudyTable();
		studyTable1.id = 1;
		studyTable1.brand = "Ikea";
		studyTable1.price = 5500;
		studyTable1.colour = "Brown";
		studyTable1.material = "Wood";
		studyTable1.shape = "Rectangle";
		studyTable1.drawers = 2;
		studyTable1.size = "Medium";
		System.out.println("table id is " + studyTable1.id);
		System.out.println("brand is " + studyTable1.brand);
		System.out.println("price is " + studyTable1.price);
		System.out.println("colour is " + studyTable1.colour);
		System.out.println("material is " + studyTable1.material);
		System.out.println("shape is " + studyTable1.shape);
		System.out.println("drawers are " + studyTable1.drawers);
		System.out.println("size is " + studyTable1.size);

		StudyTable studyTable2 = new StudyTable();
		studyTable2.id = 2;
		studyTable2.brand = "Nilkamal";
		studyTable2.price = 4800;
		studyTable2.colour = "Black";
		studyTable2.material = "Engineered Wood";
		studyTable2.shape = "Rectangle";
		studyTable2.drawers = 1;
		studyTable2.size = "Small";
		System.out.println("table id is " + studyTable2.id);
		System.out.println("brand is " + studyTable2.brand);
		System.out.println("price is " + studyTable2.price);
		System.out.println("colour is " + studyTable2.colour);
		System.out.println("material is " + studyTable2.material);
		System.out.println("shape is " + studyTable2.shape);
		System.out.println("drawers are " + studyTable2.drawers);
		System.out.println("size is " + studyTable2.size);

		StudyTable studyTable3 = new StudyTable();
		studyTable3.id = 3;
		studyTable3.brand = "UrbanLadder";
		studyTable3.price = 7200;
		studyTable3.colour = "White";
		studyTable3.material = "Wood";
		studyTable3.shape = "Rectangle";
		studyTable3.drawers = 3;
		studyTable3.size = "Large";
		System.out.println("table id is " + studyTable3.id);
		System.out.println("brand is " + studyTable3.brand);
		System.out.println("price is " + studyTable3.price);
		System.out.println("colour is " + studyTable3.colour);
		System.out.println("material is " + studyTable3.material);
		System.out.println("shape is " + studyTable3.shape);
		System.out.println("drawers are " + studyTable3.drawers);
		System.out.println("size is " + studyTable3.size);

		StudyTable studyTable4 = new StudyTable();
		studyTable4.id = 4;
		studyTable4.brand = "Ikea";
		studyTable4.price = 6000;
		studyTable4.colour = "Black";
		studyTable4.material = "Wood";
		studyTable4.shape = "Rectangle";
		studyTable4.drawers = 2;
		studyTable4.size = "Medium";
		System.out.println("table id is " + studyTable4.id);
		System.out.println("brand is " + studyTable4.brand);
		System.out.println("price is " + studyTable4.price);
		System.out.println("colour is " + studyTable4.colour);
		System.out.println("material is " + studyTable4.material);
		System.out.println("shape is " + studyTable4.shape);
		System.out.println("drawers are " + studyTable4.drawers);
		System.out.println("size is " + studyTable4.size);

		StudyTable studyTable5 = new StudyTable();
		studyTable5.id = 5;
		studyTable5.brand = "Nilkamal";
		studyTable5.price = 5000;
		studyTable5.colour = "Brown";
		studyTable5.material = "Engineered Wood";
		studyTable5.shape = "Rectangle";
		studyTable5.drawers = 1;
		studyTable5.size = "Small";
		System.out.println("table id is " + studyTable5.id);
		System.out.println("brand is " + studyTable5.brand);
		System.out.println("price is " + studyTable5.price);
		System.out.println("colour is " + studyTable5.colour);
		System.out.println("material is " + studyTable5.material);
		System.out.println("shape is " + studyTable5.shape);
		System.out.println("drawers are " + studyTable5.drawers);
		System.out.println("size is " + studyTable5.size);

		StudyTable studyTable6 = new StudyTable();
		studyTable6.id = 6;
		studyTable6.brand = "UrbanLadder";
		studyTable6.price = 8000;
		studyTable6.colour = "White";
		studyTable6.material = "Wood";
		studyTable6.shape = "Rectangle";
		studyTable6.drawers = 3;
		studyTable6.size = "Large";
		System.out.println("table id is " + studyTable6.id);
		System.out.println("brand is " + studyTable6.brand);
		System.out.println("price is " + studyTable6.price);
		System.out.println("colour is " + studyTable6.colour);
		System.out.println("material is " + studyTable6.material);
		System.out.println("shape is " + studyTable6.shape);
		System.out.println("drawers are " + studyTable6.drawers);
		System.out.println("size is " + studyTable6.size);

		StudyTable studyTable7 = new StudyTable();
		studyTable7.id = 7;
		studyTable7.brand = "Ikea";
		studyTable7.price = 6200;
		studyTable7.colour = "Brown";
		studyTable7.material = "Wood";
		studyTable7.shape = "Rectangle";
		studyTable7.drawers = 2;
		studyTable7.size = "Medium";
		System.out.println("table id is " + studyTable7.id);
		System.out.println("brand is " + studyTable7.brand);
		System.out.println("price is " + studyTable7.price);
		System.out.println("colour is " + studyTable7.colour);
		System.out.println("material is " + studyTable7.material);
		System.out.println("shape is " + studyTable7.shape);
		System.out.println("drawers are " + studyTable7.drawers);
		System.out.println("size is " + studyTable7.size);
		
		StudyTable studyTable7 = new StudyTable();
		studyTable7.id = 7;
		studyTable7.brand = "Ikea";
		studyTable7.price = 6200;
		studyTable7.colour = "Brown";
		studyTable7.material = "Wood";
		studyTable7.shape = "Rectangle";
		studyTable7.drawers = 2;
		studyTable7.size = "Medium";
		System.out.println("table id is " + studyTable7.id);
		System.out.println("brand is " + studyTable7.brand);
		System.out.println("price is " + studyTable7.price);
		System.out.println("colour is " + studyTable7.colour);
		System.out.println("material is " + studyTable7.material);
		System.out.println("shape is " + studyTable7.shape);
		System.out.println("drawers are " + studyTable7.drawers);
		System.out.println("size is " + studyTable7.size);


		StudyTable studyTable8 = new StudyTable();
		studyTable8.id = 8;
		studyTable8.brand = "Nilkamal";
		studyTable8.price = 5100;
		studyTable8.colour = "Black";
		studyTable8.material = "Engineered Wood";
		studyTable8.shape = "Rectangle";
		studyTable8.drawers = 1;
		studyTable8.size = "Small";
		System.out.println("table id is " + studyTable8.id);
		System.out.println("brand is " + studyTable8.brand);
		System.out.println("price is " + studyTable8.price);
		System.out.println("colour is " + studyTable8.colour);
		System.out.println("material is " + studyTable8.material);
		System.out.println("shape is " + studyTable8.shape);
		System.out.println("drawers are " + studyTable8.drawers);
		System.out.println("size is " + studyTable8.size);

		StudyTable studyTable9 = new StudyTable();
		studyTable9.id = 9;
		studyTable9.brand = "UrbanLadder";
		studyTable9.price = 8300;
		studyTable9.colour = "White";
		studyTable9.material = "Wood";
		studyTable9.shape = "Rectangle";
		studyTable9.drawers = 3;
		studyTable9.size = "Large";
		System.out.println("table id is " + studyTable9.id);
		System.out.println("brand is " + studyTable9.brand);
		System.out.println("price is " + studyTable9.price);
		System.out.println("colour is " + studyTable9.colour);
		System.out.println("material is " + studyTable9.material);
		System.out.println("shape is " + studyTable9.shape);
		System.out.println("drawers are " + studyTable9.drawers);
		System.out.println("size is " + studyTable9.size);

		StudyTable studyTable10 = new StudyTable();
		studyTable10.id = 10;
		studyTable10.brand = "Ikea";
		studyTable10.price = 6400;
		studyTable10.colour = "Brown";
		studyTable10.material = "Wood";
		studyTable10.shape = "Rectangle";
		studyTable10.drawers = 2;
		studyTable10.size = "Medium";
		System.out.println("table id is " + studyTable10.id);
		System.out.println("brand is " + studyTable10.brand);
		System.out.println("price is " + studyTable10.price);
		System.out.println("colour is " + studyTable10.colour);
		System.out.println("material is " + studyTable10.material);
		System.out.println("shape is " + studyTable10.shape);
		System.out.println("drawers are " + studyTable10.drawers);
		System.out.println("size is " + studyTable10.size);

		StudyTable studyTable11 = new StudyTable();
		studyTable11.id = 11;
		studyTable11.brand = "Nilkamal";
		studyTable11.price = 5300;
		studyTable11.colour = "Black";
		studyTable11.material = "Engineered Wood";
		studyTable11.shape = "Rectangle";
		studyTable11.drawers = 1;
		studyTable11.size = "Small";
		System.out.println("table id is " + studyTable11.id);
		System.out.println("brand is " + studyTable11.brand);
		System.out.println("price is " + studyTable11.price);
		System.out.println("colour is " + studyTable11.colour);
		System.out.println("material is " + studyTable11.material);
		System.out.println("shape is " + studyTable11.shape);
		System.out.println("drawers are " + studyTable11.drawers);
		System.out.println("size is " + studyTable11.size);

		StudyTable studyTable12 = new StudyTable();
		studyTable12.id = 12;
		studyTable12.brand = "UrbanLadder";
		studyTable12.price = 8700;
		studyTable12.colour = "White";
		studyTable12.material = "Wood";
		studyTable12.shape = "Rectangle";
		studyTable12.drawers = 3;
		studyTable12.size = "Large";
		System.out.println("table id is " + studyTable12.id);
		System.out.println("brand is " + studyTable12.brand);
		System.out.println("price is " + studyTable12.price);
		System.out.println("colour is " + studyTable12.colour);
		System.out.println("material is " + studyTable12.material);
		System.out.println("shape is " + studyTable12.shape);
		System.out.println("drawers are " + studyTable12.drawers);
		System.out.println("size is " + studyTable12.size);

		StudyTable studyTable13 = new StudyTable();
		studyTable13.id = 13;
		studyTable13.brand = "Ikea";
		studyTable13.price = 6600;
		studyTable13.colour = "Brown";
		studyTable13.material = "Wood";
		studyTable13.shape = "Rectangle";
		studyTable13.drawers = 2;
		studyTable13.size = "Medium";
		System.out.println("table id is " + studyTable13.id);
		System.out.println("brand is " + studyTable13.brand);
		System.out.println("price is " + studyTable13.price);
		System.out.println("colour is " + studyTable13.colour);
		System.out.println("material is " + studyTable13.material);
		System.out.println("shape is " + studyTable13.shape);
		System.out.println("drawers are " + studyTable13.drawers);
		System.out.println("size is " + studyTable13.size);

		StudyTable studyTable14 = new StudyTable();
		studyTable14.id = 14;
		studyTable14.brand = "Nilkamal";
		studyTable14.price = 5400;
		studyTable14.colour = "Black";
		studyTable14.material = "Engineered Wood";
		studyTable14.shape = "Rectangle";
		studyTable14.drawers = 1;
		studyTable14.size = "Small";
		System.out.println("table id is " + studyTable14.id);
		System.out.println("brand is " + studyTable14.brand);
		System.out.println("price is " + studyTable14.price);
		System.out.println("colour is " + studyTable14.colour);
		System.out.println("material is " + studyTable14.material);
		System.out.println("shape is " + studyTable14.shape);
		System.out.println("drawers are " + studyTable14.drawers);
		System.out.println("size is " + studyTable14.size);

		StudyTable studyTable15 = new StudyTable();
		studyTable15.id = 15;
		studyTable15.brand = "UrbanLadder";
		studyTable15.price = 8900;
		studyTable15.colour = "White";
		studyTable15.material = "Wood";
		studyTable15.shape = "Rectangle";
		studyTable15.drawers = 3;
		studyTable15.size = "Large";
		System.out.println("table id is " + studyTable15.id);
		System.out.println("brand is " + studyTable15.brand);
		System.out.println("price is " + studyTable15.price);
		System.out.println("colour is " + studyTable15.colour);
		System.out.println("material is " + studyTable15.material);
		System.out.println("shape is " + studyTable15.shape);
		System.out.println("drawers are " + studyTable15.drawers);
		System.out.println("size is " + studyTable15.size);

		StudyTable studyTable16 = new StudyTable();
		studyTable16.id = 16;
		studyTable16.brand = "Ikea";
		studyTable16.price = 6800;
		studyTable16.colour = "Brown";
		studyTable16.material = "Wood";
		studyTable16.shape = "Rectangle";
		studyTable16.drawers = 2;
		studyTable16.size = "Medium";
		System.out.println("table id is " + studyTable16.id);
		System.out.println("brand is " + studyTable16.brand);
		System.out.println("price is " + studyTable16.price);
		System.out.println("colour is " + studyTable16.colour);
		System.out.println("material is " + studyTable16.material);
		System.out.println("shape is " + studyTable16.shape);
		System.out.println("drawers are " + studyTable16.drawers);
		System.out.println("size is " + studyTable16.size);

		StudyTable studyTable17 = new StudyTable();
		studyTable17.id = 17;
		studyTable17.brand = "Nilkamal";
		studyTable17.price = 5600;
		studyTable17.colour = "Black";
		studyTable17.material = "Engineered Wood";
		studyTable17.shape = "Rectangle";
		studyTable17.drawers = 1;
		studyTable17.size = "Small";
		System.out.println("table id is " + studyTable17.id);
		System.out.println("brand is " + studyTable17.brand);
		System.out.println("price is " + studyTable17.price);
		System.out.println("colour is " + studyTable17.colour);
		System.out.println("material is " + studyTable17.material);
		System.out.println("shape is " + studyTable17.shape);
		System.out.println("drawers are " + studyTable17.drawers);
		System.out.println("size is " + studyTable17.size);

		StudyTable studyTable18 = new StudyTable();
		studyTable18.id = 18;
		studyTable18.brand = "UrbanLadder";
		studyTable18.price = 9100;
		studyTable18.colour = "White";
		studyTable18.material = "Wood";
		studyTable18.shape = "Rectangle";
		studyTable18.drawers = 3;
		studyTable18.size = "Large";
		System.out.println("table id is " + studyTable18.id);
		System.out.println("brand is " + studyTable18.brand);
		System.out.println("price is " + studyTable18.price);
		System.out.println("colour is " + studyTable18.colour);
		System.out.println("material is " + studyTable18.material);
		System.out.println("shape is " + studyTable18.shape);
		System.out.println("drawers are " + studyTable18.drawers);
		System.out.println("size is " + studyTable18.size);

		StudyTable studyTable19 = new StudyTable();
		studyTable19.id = 19;
		studyTable19.brand = "Ikea";
		studyTable19.price = 7000;
		studyTable19.colour = "Brown";
		studyTable19.material = "Wood";
		studyTable19.shape = "Rectangle";
		studyTable19.drawers = 2;
		studyTable19.size = "Medium";
		System.out.println("table id is " + studyTable19.id);
		System.out.println("brand is " + studyTable19.brand);
		System.out.println("price is " + studyTable19.price);
		System.out.println("colour is " + studyTable19.colour);
		System.out.println("material is " + studyTable19.material);
		System.out.println("shape is " + studyTable19.shape);
		System.out.println("drawers are " + studyTable19.drawers);
		System.out.println("size is " + studyTable19.size);

		StudyTable studyTable20 = new StudyTable();
		studyTable20.id = 20;
		studyTable20.brand = "Nilkamal";
		studyTable20.price = 5800;
		studyTable20.colour = "Black";
		studyTable20.material = "Engineered Wood";
		studyTable20.shape = "Rectangle";
		studyTable20.drawers = 1;
		studyTable20.size = "Small";
		System.out.println("table id is " + studyTable20.id);
		System.out.println("brand is " + studyTable20.brand);
		System.out.println("price is " + studyTable20.price);
		System.out.println("colour is " + studyTable20.colour);
		System.out.println("material is " + studyTable20.material);
		System.out.println("shape is " + studyTable20.shape);
		System.out.println("drawers are " + studyTable20.drawers);
		System.out.println("size is " + studyTable20.size);

		StudyTable studyTable21 = new StudyTable();
		studyTable21.id = 21;
		studyTable21.brand = "UrbanLadder";
		studyTable21.price = 9300;
		studyTable21.colour = "White";
		studyTable21.material = "Wood";
		studyTable21.shape = "Rectangle";
		studyTable21.drawers = 3;
		studyTable21.size = "Large";
		System.out.println("table id is " + studyTable21.id);
		System.out.println("brand is " + studyTable21.brand);
		System.out.println("price is " + studyTable21.price);
		System.out.println("colour is " + studyTable21.colour);
		System.out.println("material is " + studyTable21.material);
		System.out.println("shape is " + studyTable21.shape);
		System.out.println("drawers are " + studyTable21.drawers);
		System.out.println("size is " + studyTable21.size);

		StudyTable studyTable22 = new StudyTable();
		studyTable22.id = 22;
		studyTable22.brand = "Ikea";
		studyTable22.price = 7200;
		studyTable22.colour = "Brown";
		studyTable22.material = "Wood";
		studyTable22.shape = "Rectangle";
		studyTable22.drawers = 2;
		studyTable22.size = "Medium";
		System.out.println("table id is " + studyTable22.id);
		System.out.println("brand is " + studyTable22.brand);
		System.out.println("price is " + studyTable22.price);
		System.out.println("colour is " + studyTable22.colour);
		System.out.println("material is " + studyTable22.material);
		System.out.println("shape is " + studyTable22.shape);
		System.out.println("drawers are " + studyTable22.drawers);
		System.out.println("size is " + studyTable22.size);

		StudyTable studyTable23 = new StudyTable();
		studyTable23.id = 23;
		studyTable23.brand = "Nilkamal";
		studyTable23.price = 6000;
		studyTable23.colour = "Black";
		studyTable23.material = "Engineered Wood";
		studyTable23.shape = "Rectangle";
		studyTable23.drawers = 1;
		studyTable23.size = "Small";
		System.out.println("table id is " + studyTable23.id);
		System.out.println("brand is " + studyTable23.brand);
		System.out.println("price is " + studyTable23.price);
		System.out.println("colour is " + studyTable23.colour);
		System.out.println("material is " + studyTable23.material);
		System.out.println("shape is " + studyTable23.shape);
		System.out.println("drawers are " + studyTable23.drawers);
		System.out.println("size is " + studyTable23.size);

		StudyTable studyTable24 = new StudyTable();
		studyTable24.id = 24;
		studyTable24.brand = "UrbanLadder";
		studyTable24.price = 9500;
		studyTable24.colour = "White";
		studyTable24.material = "Wood";
		studyTable24.shape = "Rectangle";
		studyTable24.drawers = 3;
		studyTable24.size = "Large";
		System.out.println("table id is " + studyTable24.id);
		System.out.println("brand is " + studyTable24.brand);
		System.out.println("price is " + studyTable24.price);
		System.out.println("colour is " + studyTable24.colour);
		System.out.println("material is " + studyTable24.material);
		System.out.println("shape is " + studyTable24.shape);
		System.out.println("drawers are " + studyTable24.drawers);
		System.out.println("size is " + studyTable24.size);

		StudyTable studyTable25 = new StudyTable();
		studyTable25.id = 25;
		studyTable25.brand = "Ikea";
		studyTable25.price = 7400;
		studyTable25.colour = "Brown";
		studyTable25.material = "Wood";
		studyTable25.shape = "Rectangle";
		studyTable25.drawers = 2;
		studyTable25.size = "Medium";
		System.out.println("table id is " + studyTable25.id);
		System.out.println("brand is " + studyTable25.brand);
		System.out.println("price is " + studyTable25.price);
		System.out.println("colour is " + studyTable25.colour);
		System.out.println("material is " + studyTable25.material);
		System.out.println("shape is " + studyTable25.shape);
		System.out.println("drawers are " + studyTable25.drawers);
		System.out.println("size is " + studyTable25.size);

		StudyTable studyTable26 = new StudyTable();
		studyTable26.id = 26;
		studyTable26.brand = "Nilkamal";
		studyTable26.price = 6200;
		studyTable26.colour = "Black";
		studyTable26.material = "Engineered Wood";
		studyTable26.shape = "Rectangle";
		studyTable26.drawers = 1;
		studyTable26.size = "Small";
		System.out.println("table id is " + studyTable26.id);
		System.out.println("brand is " + studyTable26.brand);
		System.out.println("price is " + studyTable26.price);
		System.out.println("colour is " + studyTable26.colour);
		System.out.println("material is " + studyTable26.material);
		System.out.println("shape is " + studyTable26.shape);
		System.out.println("drawers are " + studyTable26.drawers);
		System.out.println("size is " + studyTable26.size);

		StudyTable studyTable27 = new StudyTable();
		studyTable27.id = 27;
		studyTable27.brand = "UrbanLadder";
		studyTable27.price = 9700;
		studyTable27.colour = "White";
		studyTable27.material = "Wood";
		studyTable27.shape = "Rectangle";
		studyTable27.drawers = 3;
		studyTable27.size = "Large";
		System.out.println("table id is " + studyTable27.id);
		System.out.println("brand is " + studyTable27.brand);
		System.out.println("price is " + studyTable27.price);
		System.out.println("colour is " + studyTable27.colour);
		System.out.println("material is " + studyTable27.material);
		System.out.println("shape is " + studyTable27.shape);
		System.out.println("drawers are " + studyTable27.drawers);
		System.out.println("size is " + studyTable27.size);

		StudyTable studyTable28 = new StudyTable();
		studyTable28.id = 28;
		studyTable28.brand = "Ikea";
		studyTable28.price = 7600;
		studyTable28.colour = "Brown";
		studyTable28.material = "Wood";
		studyTable28.shape = "Rectangle";
		studyTable28.drawers = 2;
		studyTable28.size = "Medium";
		System.out.println("table id is " + studyTable28.id);
		System.out.println("brand is " + studyTable28.brand);
		System.out.println("price is " + studyTable28.price);
		System.out.println("colour is " + studyTable28.colour);
		System.out.println("material is " + studyTable28.material);
		System.out.println("shape is " + studyTable28.shape);
		System.out.println("drawers are " + studyTable28.drawers);
		System.out.println("size is " + studyTable28.size);

		StudyTable studyTable29 = new StudyTable();
		studyTable29.id = 29;
		studyTable29.brand = "Nilkamal";
		studyTable29.price = 6400;
		studyTable29.colour = "Black";
		studyTable29.material = "Engineered Wood";
		studyTable29.shape = "Rectangle";
		studyTable29.drawers = 1;
		studyTable29.size = "Small";
		System.out.println("table id is " + studyTable29.id);
		System.out.println("brand is " + studyTable29.brand);
		System.out.println("price is " + studyTable29.price);
		System.out.println("colour is " + studyTable29.colour);
		System.out.println("material is " + studyTable29.material);
		System.out.println("shape is " + studyTable29.shape);
		System.out.println("drawers are " + studyTable29.drawers);
		System.out.println("size is " + studyTable29.size);

		StudyTable studyTable30 = new StudyTable();
		studyTable30.id = 30;
		studyTable30.brand = "UrbanLadder";
		studyTable30.price = 9900;
		studyTable30.colour = "White";
		studyTable30.material = "Wood";
		studyTable30.shape = "Rectangle";
		studyTable30.drawers = 3;
		studyTable30.size = "Large";
		System.out.println("table id is " + studyTable30.id);
		System.out.println("brand is " + studyTable30.brand);
		System.out.println("price is " + studyTable30.price);
		System.out.println("colour is " + studyTable30.colour);
		System.out.println("material is " + studyTable30.material);
		System.out.println("shape is " + studyTable30.shape);
		System.out.println("drawers are " + studyTable30.drawers);
		System.out.println("size is " + studyTable30.size);



	}
}