class WalletExecuter{
	public static void main(String[] args){

		Wallet wallet1 = new Wallet();
		wallet1.id = 1;
		wallet1.brand = "Wildcraft";
		wallet1.price = 799;
		wallet1.colour = "Black";
		wallet1.material = "Leather";
		wallet1.compartments = 4;
		wallet1.type = "BiFold";
		wallet1.gender = "Men";
		System.out.println("wallet id is " + wallet1.id);
		System.out.println("brand is " + wallet1.brand);
		System.out.println("price is " + wallet1.price);
		System.out.println("colour is " + wallet1.colour);
		System.out.println("material is " + wallet1.material);
		System.out.println("compartments are " + wallet1.compartments);
		System.out.println("type is " + wallet1.type);
		System.out.println("gender is " + wallet1.gender);

		Wallet wallet2 = new Wallet();
		wallet2.id = 2;
		wallet2.brand = "Fastrack";
		wallet2.price = 699;
		wallet2.colour = "Brown";
		wallet2.material = "Leather";
		wallet2.compartments = 5;
		wallet2.type = "BiFold";
		wallet2.gender = "Men";
		System.out.println("wallet id is " + wallet2.id);
		System.out.println("brand is " + wallet2.brand);
		System.out.println("price is " + wallet2.price);
		System.out.println("colour is " + wallet2.colour);
		System.out.println("material is " + wallet2.material);
		System.out.println("compartments are " + wallet2.compartments);
		System.out.println("type is " + wallet2.type);
		System.out.println("gender is " + wallet2.gender);

		Wallet wallet3 = new Wallet();
		wallet3.id = 3;
		wallet3.brand = "Woodland";
		wallet3.price = 999;
		wallet3.colour = "Tan";
		wallet3.material = "Leather";
		wallet3.compartments = 6;
		wallet3.type = "TriFold";
		wallet3.gender = "Men";
		System.out.println("wallet id is " + wallet3.id);
		System.out.println("brand is " + wallet3.brand);
		System.out.println("price is " + wallet3.price);
		System.out.println("colour is " + wallet3.colour);
		System.out.println("material is " + wallet3.material);
		System.out.println("compartments are " + wallet3.compartments);
		System.out.println("type is " + wallet3.type);
		System.out.println("gender is " + wallet3.gender);

		Wallet wallet4 = new Wallet();
		wallet4.id = 4;
		wallet4.brand = "Lavie";
		wallet4.price = 850;
		wallet4.colour = "Pink";
		wallet4.material = "PU";
		wallet4.compartments = 7;
		wallet4.type = "Zip";
		wallet4.gender = "Women";
		System.out.println("wallet id is " + wallet4.id);
		System.out.println("brand is " + wallet4.brand);
		System.out.println("price is " + wallet4.price);
		System.out.println("colour is " + wallet4.colour);
		System.out.println("material is " + wallet4.material);
		System.out.println("compartments are " + wallet4.compartments);
		System.out.println("type is " + wallet4.type);
		System.out.println("gender is " + wallet4.gender);

		Wallet wallet5 = new Wallet();
		wallet5.id = 5;
		wallet5.brand = "Baggit";
		wallet5.price = 900;
		wallet5.colour = "Red";
		wallet5.material = "PU";
		wallet5.compartments = 6;
		wallet5.type = "Zip";
		wallet5.gender = "Women";
		System.out.println("wallet id is " + wallet5.id);
		System.out.println("brand is " + wallet5.brand);
		System.out.println("price is " + wallet5.price);
		System.out.println("colour is " + wallet5.colour);
		System.out.println("material is " + wallet5.material);
		System.out.println("compartments are " + wallet5.compartments);
		System.out.println("type is " + wallet5.type);
		System.out.println("gender is " + wallet5.gender);
		
	    Wallet wallet6 = new Wallet();
		wallet6.id = 6;
		wallet6.brand = "Wildcraft";
		wallet6.price = 750;
		wallet6.colour = "Blue";
		wallet6.material = "Fabric";
		wallet6.compartments = 5;
		wallet6.type = "BiFold";
		wallet6.gender = "Men";
		System.out.println("wallet id is " + wallet6.id);
		System.out.println("brand is " + wallet6.brand);
		System.out.println("price is " + wallet6.price);
		System.out.println("colour is " + wallet6.colour);
		System.out.println("material is " + wallet6.material);
		System.out.println("compartments are " + wallet6.compartments);
		System.out.println("type is " + wallet6.type);
		System.out.println("gender is " + wallet6.gender);

		Wallet wallet7 = new Wallet();
		wallet7.id = 7;
		wallet7.brand = "Fastrack";
		wallet7.price = 680;
		wallet7.colour = "Black";
		wallet7.material = "Leather";
		wallet7.compartments = 4;
		wallet7.type = "BiFold";
		wallet7.gender = "Men";
		System.out.println("wallet id is " + wallet7.id);
		System.out.println("brand is " + wallet7.brand);
		System.out.println("price is " + wallet7.price);
		System.out.println("colour is " + wallet7.colour);
		System.out.println("material is " + wallet7.material);
		System.out.println("compartments are " + wallet7.compartments);
		System.out.println("type is " + wallet7.type);
		System.out.println("gender is " + wallet7.gender);

		Wallet wallet8 = new Wallet();
		wallet8.id = 8;
		wallet8.brand = "Woodland";
		wallet8.price = 1050;
		wallet8.colour = "Brown";
		wallet8.material = "Leather";
		wallet8.compartments = 6;
		wallet8.type = "TriFold";
		wallet8.gender = "Men";
		System.out.println("wallet id is " + wallet8.id);
		System.out.println("brand is " + wallet8.brand);
		System.out.println("price is " + wallet8.price);
		System.out.println("colour is " + wallet8.colour);
		System.out.println("material is " + wallet8.material);
		System.out.println("compartments are " + wallet8.compartments);
		System.out.println("type is " + wallet8.type);
		System.out.println("gender is " + wallet8.gender);

		Wallet wallet9 = new Wallet();
		wallet9.id = 9;
		wallet9.brand = "Lavie";
		wallet9.price = 920;
		wallet9.colour = "Purple";
		wallet9.material = "PU";
		wallet9.compartments = 7;
		wallet9.type = "Zip";
		wallet9.gender = "Women";
		System.out.println("wallet id is " + wallet9.id);
		System.out.println("brand is " + wallet9.brand);
		System.out.println("price is " + wallet9.price);
		System.out.println("colour is " + wallet9.colour);
		System.out.println("material is " + wallet9.material);
		System.out.println("compartments are " + wallet9.compartments);
		System.out.println("type is " + wallet9.type);
		System.out.println("gender is " + wallet9.gender);

		Wallet wallet10 = new Wallet();
		wallet10.id = 10;
		wallet10.brand = "Baggit";
		wallet10.price = 880;
		wallet10.colour = "Grey";
		wallet10.material = "PU";
		wallet10.compartments = 6;
		wallet10.type = "Zip";
		wallet10.gender = "Women";
		System.out.println("wallet id is " + wallet10.id);
		System.out.println("brand is " + wallet10.brand);
		System.out.println("price is " + wallet10.price);
		System.out.println("colour is " + wallet10.colour);
		System.out.println("material is " + wallet10.material);
		System.out.println("compartments are " + wallet10.compartments);
		System.out.println("type is " + wallet10.type);
		System.out.println("gender is " + wallet10.gender);

		Wallet wallet11 = new Wallet();
		wallet11.id = 11;
		wallet11.brand = "Wildcraft";
		wallet11.price = 810;
		wallet11.colour = "Green";
		wallet11.material = "Fabric";
		wallet11.compartments = 5;
		wallet11.type = "BiFold";
		wallet11.gender = "Men";
		System.out.println("wallet id is " + wallet11.id);
		System.out.println("brand is " + wallet11.brand);
		System.out.println("price is " + wallet11.price);
		System.out.println("colour is " + wallet11.colour);
		System.out.println("material is " + wallet11.material);
		System.out.println("compartments are " + wallet11.compartments);
		System.out.println("type is " + wallet11.type);
		System.out.println("gender is " + wallet11.gender);

		Wallet wallet12 = new Wallet();
		wallet12.id = 12;
		wallet12.brand = "Fastrack";
		wallet12.price = 720;
		wallet12.colour = "Brown";
		wallet12.material = "Leather";
		wallet12.compartments = 4;
		wallet12.type = "BiFold";
		wallet12.gender = "Men";
		System.out.println("wallet id is " + wallet12.id);
		System.out.println("brand is " + wallet12.brand);
		System.out.println("price is " + wallet12.price);
		System.out.println("colour is " + wallet12.colour);
		System.out.println("material is " + wallet12.material);
		System.out.println("compartments are " + wallet12.compartments);
		System.out.println("type is " + wallet12.type);
		System.out.println("gender is " + wallet12.gender);

		Wallet wallet13 = new Wallet();
		wallet13.id = 13;
		wallet13.brand = "Woodland";
		wallet13.price = 1100;
		wallet13.colour = "Tan";
		wallet13.material = "Leather";
		wallet13.compartments = 6;
		wallet13.type = "TriFold";
		wallet13.gender = "Men";
		System.out.println("wallet id is " + wallet13.id);
		System.out.println("brand is " + wallet13.brand);
		System.out.println("price is " + wallet13.price);
		System.out.println("colour is " + wallet13.colour);
		System.out.println("material is " + wallet13.material);
		System.out.println("compartments are " + wallet13.compartments);
		System.out.println("type is " + wallet13.type);
		System.out.println("gender is " + wallet13.gender);

		Wallet wallet14 = new Wallet();
		wallet14.id = 14;
		wallet14.brand = "Lavie";
		wallet14.price = 970;
		wallet14.colour = "Pink";
		wallet14.material = "PU";
		wallet14.compartments = 8;
		wallet14.type = "Zip";
		wallet14.gender = "Women";
		System.out.println("wallet id is " + wallet14.id);
		System.out.println("brand is " + wallet14.brand);
		System.out.println("price is " + wallet14.price);
		System.out.println("colour is " + wallet14.colour);
		System.out.println("material is " + wallet14.material);
		System.out.println("compartments are " + wallet14.compartments);
		System.out.println("type is " + wallet14.type);
		System.out.println("gender is " + wallet14.gender);

		Wallet wallet15 = new Wallet();
		wallet15.id = 15;
		wallet15.brand = "Baggit";
		wallet15.price = 930;
		wallet15.colour = "Red";
		wallet15.material = "PU";
		wallet15.compartments = 6;
		wallet15.type = "Zip";
		wallet15.gender = "Women";
		System.out.println("wallet id is " + wallet15.id);
		System.out.println("brand is " + wallet15.brand);
		System.out.println("price is " + wallet15.price);
		System.out.println("colour is " + wallet15.colour);
		System.out.println("material is " + wallet15.material);
		System.out.println("compartments are " + wallet15.compartments);
		System.out.println("type is " + wallet15.type);
		System.out.println("gender is " + wallet15.gender);

		Wallet wallet16 = new Wallet();
		wallet16.id = 16;
		wallet16.brand = "Wildcraft";
		wallet16.price = 820;
		wallet16.colour = "Black";
		wallet16.material = "Fabric";
		wallet16.compartments = 5;
		wallet16.type = "BiFold";
		wallet16.gender = "Men";
		System.out.println("wallet id is " + wallet16.id);
		System.out.println("brand is " + wallet16.brand);
		System.out.println("price is " + wallet16.price);
		System.out.println("colour is " + wallet16.colour);
		System.out.println("material is " + wallet16.material);
		System.out.println("compartments are " + wallet16.compartments);
		System.out.println("type is " + wallet16.type);
		System.out.println("gender is " + wallet16.gender);

		Wallet wallet17 = new Wallet();
		wallet17.id = 17;
		wallet17.brand = "Fastrack";
		wallet17.price = 760;
		wallet17.colour = "Blue";
		wallet17.material = "Leather";
		wallet17.compartments = 4;
		wallet17.type = "BiFold";
		wallet17.gender = "Men";
		System.out.println("wallet id is " + wallet17.id);
		System.out.println("brand is " + wallet17.brand);
		System.out.println("price is " + wallet17.price);
		System.out.println("colour is " + wallet17.colour);
		System.out.println("material is " + wallet17.material);
		System.out.println("compartments are " + wallet17.compartments);
		System.out.println("type is " + wallet17.type);
		System.out.println("gender is " + wallet17.gender);

		Wallet wallet18 = new Wallet();
		wallet18.id = 18;
		wallet18.brand = "Woodland";
		wallet18.price = 1150;
		wallet18.colour = "Brown";
		wallet18.material = "Leather";
		wallet18.compartments = 7;
		wallet18.type = "TriFold";
		wallet18.gender = "Men";
		System.out.println("wallet id is " + wallet18.id);
		System.out.println("brand is " + wallet18.brand);
		System.out.println("price is " + wallet18.price);
		System.out.println("colour is " + wallet18.colour);
		System.out.println("material is " + wallet18.material);
		System.out.println("compartments are " + wallet18.compartments);
		System.out.println("type is " + wallet18.type);
		System.out.println("gender is " + wallet18.gender);

		Wallet wallet19 = new Wallet();
		wallet19.id = 19;
		wallet19.brand = "Lavie";
		wallet19.price = 990;
		wallet19.colour = "Purple";
		wallet19.material = "PU";
		wallet19.compartments = 8;
		wallet19.type = "Zip";
		wallet19.gender = "Women";
		System.out.println("wallet id is " + wallet19.id);
		System.out.println("brand is " + wallet19.brand);
		System.out.println("price is " + wallet19.price);
		System.out.println("colour is " + wallet19.colour);
		System.out.println("material is " + wallet19.material);
		System.out.println("compartments are " + wallet19.compartments);
		System.out.println("type is " + wallet19.type);
		System.out.println("gender is " + wallet19.gender);

		Wallet wallet20 = new Wallet();
		wallet20.id = 20;
		wallet20.brand = "Baggit";
		wallet20.price = 950;
		wallet20.colour = "Grey";
		wallet20.material = "PU";
		wallet20.compartments = 6;
		wallet20.type = "Zip";
		wallet20.gender = "Women";
		System.out.println("wallet id is " + wallet20.id);
		System.out.println("brand is " + wallet20.brand);
		System.out.println("price is " + wallet20.price);
		System.out.println("colour is " + wallet20.colour);
		System.out.println("material is " + wallet20.material);
		System.out.println("compartments are " + wallet20.compartments);
		System.out.println("type is " + wallet20.type);
		System.out.println("gender is " + wallet20.gender);

		Wallet wallet21 = new Wallet();
		wallet21.id = 21;
		wallet21.brand = "Wildcraft";
		wallet21.price = 830;
		wallet21.colour = "Green";
		wallet21.material = "Fabric";
		wallet21.compartments = 5;
		wallet21.type = "BiFold";
		wallet21.gender = "Men";
		System.out.println("wallet id is " + wallet21.id);
		System.out.println("brand is " + wallet21.brand);
		System.out.println("price is " + wallet21.price);
		System.out.println("colour is " + wallet21.colour);
		System.out.println("material is " + wallet21.material);
		System.out.println("compartments are " + wallet21.compartments);
		System.out.println("type is " + wallet21.type);
		System.out.println("gender is " + wallet21.gender);

		Wallet wallet22 = new Wallet();
		wallet22.id = 22;
		wallet22.brand = "Fastrack";
		wallet22.price = 780;
		wallet22.colour = "Black";
		wallet22.material = "Leather";
		wallet22.compartments = 4;
		wallet22.type = "BiFold";
		wallet22.gender = "Men";
		System.out.println("wallet id is " + wallet22.id);
		System.out.println("brand is " + wallet22.brand);
		System.out.println("price is " + wallet22.price);
		System.out.println("colour is " + wallet22.colour);
		System.out.println("material is " + wallet22.material);
		System.out.println("compartments are " + wallet22.compartments);
		System.out.println("type is " + wallet22.type);
		System.out.println("gender is " + wallet22.gender);

		Wallet wallet23 = new Wallet();
		wallet23.id = 23;
		wallet23.brand = "Woodland";
		wallet23.price = 1200;
		wallet23.colour = "Tan";
		wallet23.material = "Leather";
		wallet23.compartments = 6;
		wallet23.type = "TriFold";
		wallet23.gender = "Men";
		System.out.println("wallet id is " + wallet23.id);
		System.out.println("brand is " + wallet23.brand);
		System.out.println("price is " + wallet23.price);
		System.out.println("colour is " + wallet23.colour);
		System.out.println("material is " + wallet23.material);
		System.out.println("compartments are " + wallet23.compartments);
		System.out.println("type is " + wallet23.type);
		System.out.println("gender is " + wallet23.gender);

		Wallet wallet24 = new Wallet();
		wallet24.id = 24;
		wallet24.brand = "Lavie";
		wallet24.price = 1020;
		wallet24.colour = "Pink";
		wallet24.material = "PU";
		wallet24.compartments = 7;
		wallet24.type = "Zip";
		wallet24.gender = "Women";
		System.out.println("wallet id is " + wallet24.id);
		System.out.println("brand is " + wallet24.brand);
		System.out.println("price is " + wallet24.price);
		System.out.println("colour is " + wallet24.colour);
		System.out.println("material is " + wallet24.material);
		System.out.println("compartments are " + wallet24.compartments);
		System.out.println("type is " + wallet24.type);
		System.out.println("gender is " + wallet24.gender);

		Wallet wallet25 = new Wallet();
		wallet25.id = 25;
		wallet25.brand = "Baggit";
		wallet25.price = 970;
		wallet25.colour = "Red";
		wallet25.material = "PU";
		wallet25.compartments = 6;
		wallet25.type = "Zip";
		wallet25.gender = "Women";
		System.out.println("wallet id is " + wallet25.id);
		System.out.println("brand is " + wallet25.brand);
		System.out.println("price is " + wallet25.price);
		System.out.println("colour is " + wallet25.colour);
		System.out.println("material is " + wallet25.material);
		System.out.println("compartments are " + wallet25.compartments);
		System.out.println("type is " + wallet25.type);
		System.out.println("gender is " + wallet25.gender);

		Wallet wallet26 = new Wallet();
		wallet26.id = 26;
		wallet26.brand = "Wildcraft";
		wallet26.price = 850;
		wallet26.colour = "Blue";
		wallet26.material = "Fabric";
		wallet26.compartments = 5;
		wallet26.type = "BiFold";
		wallet26.gender = "Men";
		System.out.println("wallet id is " + wallet26.id);
		System.out.println("brand is " + wallet26.brand);
		System.out.println("price is " + wallet26.price);
		System.out.println("colour is " + wallet26.colour);
		System.out.println("material is " + wallet26.material);
		System.out.println("compartments are " + wallet26.compartments);
		System.out.println("type is " + wallet26.type);
		System.out.println("gender is " + wallet26.gender);

		Wallet wallet27 = new Wallet();
		wallet27.id = 27;
		wallet27.brand = "Fastrack";
		wallet27.price = 800;
		wallet27.colour = "Brown";
		wallet27.material = "Leather";
		wallet27.compartments = 4;
		wallet27.type = "BiFold";
		wallet27.gender = "Men";
		System.out.println("wallet id is " + wallet27.id);
		System.out.println("brand is " + wallet27.brand);
		System.out.println("price is " + wallet27.price);
		System.out.println("colour is " + wallet27.colour);
		System.out.println("material is " + wallet27.material);
		System.out.println("compartments are " + wallet27.compartments);
		System.out.println("type is " + wallet27.type);
		System.out.println("gender is " + wallet27.gender);

		Wallet wallet28 = new Wallet();
		wallet28.id = 28;
		wallet28.brand = "Woodland";
		wallet28.price = 1250;
		wallet28.colour = "Tan";
		wallet28.material = "Leather";
		wallet28.compartments = 6;
		wallet28.type = "TriFold";
		wallet28.gender = "Men";
		System.out.println("wallet id is " + wallet28.id);
		System.out.println("brand is " + wallet28.brand);
		System.out.println("price is " + wallet28.price);
		System.out.println("colour is " + wallet28.colour);
		System.out.println("material is " + wallet28.material);
		System.out.println("compartments are " + wallet28.compartments);
		System.out.println("type is " + wallet28.type);
		System.out.println("gender is " + wallet28.gender);

		Wallet wallet29 = new Wallet();
		wallet29.id = 29;
		wallet29.brand = "Lavie";
		wallet29.price = 1050;
		wallet29.colour = "Purple";
		wallet29.material = "PU";
		wallet29.compartments = 7;
		wallet29.type = "Zip";
		wallet29.gender = "Women";
		System.out.println("wallet id is " + wallet29.id);
		System.out.println("brand is " + wallet29.brand);
		System.out.println("price is " + wallet29.price);
		System.out.println("colour is " + wallet29.colour);
		System.out.println("material is " + wallet29.material);
		System.out.println("compartments are " + wallet29.compartments);
		System.out.println("type is " + wallet29.type);
		System.out.println("gender is " + wallet29.gender);

		Wallet wallet30 = new Wallet();
		wallet30.id = 30;
		wallet30.brand = "Baggit";
		wallet30.price = 990;
		wallet30.colour = "Grey";
		wallet30.material = "PU";
		wallet30.compartments = 6;
		wallet30.type = "Zip";
		wallet30.gender = "Women";
		System.out.println("wallet id is " + wallet30.id);
		System.out.println("brand is " + wallet30.brand);
		System.out.println("price is " + wallet30.price);
		System.out.println("colour is " + wallet30.colour);
		System.out.println("material is " + wallet30.material);
		System.out.println("compartments are " + wallet30.compartments);
		System.out.println("type is " + wallet30.type);
		System.out.println("gender is " + wallet30.gender);
	}
}