class WatchExecuter{

	public static void main(String[] args){

		Watch watch1 = new Watch();
		watch1.id = 1;
		watch1.brand = "Titan";
		watch1.price = 2500;
		watch1.colour = "Black";
		watch1.type = "Analog";
		watch1.display = "Round";
		watch1.material = "Leather";
		watch1.gender = "Men";
		System.out.println("watch id is " + watch1.id);
		System.out.println("brand is " + watch1.brand);
		System.out.println("price is " + watch1.price);
		System.out.println("colour is " + watch1.colour);
		System.out.println("type is " + watch1.type);
		System.out.println("display is " + watch1.display);
		System.out.println("material is " + watch1.material);
		System.out.println("gender is " + watch1.gender);

		Watch watch2 = new Watch();
		watch2.id = 2;
		watch2.brand = "Fastrack";
		watch2.price = 1800;
		watch2.colour = "Blue";
		watch2.type = "Digital";
		watch2.display = "Square";
		watch2.material = "Rubber";
		watch2.gender = "Men";
		System.out.println("watch id is " + watch2.id);
		System.out.println("brand is " + watch2.brand);
		System.out.println("price is " + watch2.price);
		System.out.println("colour is " + watch2.colour);
		System.out.println("type is " + watch2.type);
		System.out.println("display is " + watch2.display);
		System.out.println("material is " + watch2.material);
		System.out.println("gender is " + watch2.gender);

		Watch watch3 = new Watch();
		watch3.id = 3;
		watch3.brand = "Casio";
		watch3.price = 2200;
		watch3.colour = "Black";
		watch3.type = "Digital";
		watch3.display = "Square";
		watch3.material = "Resin";
		watch3.gender = "Unisex";
		System.out.println("watch id is " + watch3.id);
		System.out.println("brand is " + watch3.brand);
		System.out.println("price is " + watch3.price);
		System.out.println("colour is " + watch3.colour);
		System.out.println("type is " + watch3.type);
		System.out.println("display is " + watch3.display);
		System.out.println("material is " + watch3.material);
		System.out.println("gender is " + watch3.gender);

		Watch watch4 = new Watch();
		watch4.id = 4;
		watch4.brand = "Sonata";
		watch4.price = 1500;
		watch4.colour = "Brown";
		watch4.type = "Analog";
		watch4.display = "Round";
		watch4.material = "Leather";
		watch4.gender = "Men";
		System.out.println("watch id is " + watch4.id);
		System.out.println("brand is " + watch4.brand);
		System.out.println("price is " + watch4.price);
		System.out.println("colour is " + watch4.colour);
		System.out.println("type is " + watch4.type);
		System.out.println("display is " + watch4.display);
		System.out.println("material is " + watch4.material);
		System.out.println("gender is " + watch4.gender);

		Watch watch5 = new Watch();
		watch5.id = 5;
		watch5.brand = "Titan";
		watch5.price = 3200;
		watch5.colour = "Gold";
		watch5.type = "Analog";
		watch5.display = "Round";
		watch5.material = "Metal";
		watch5.gender = "Women";
		System.out.println("watch id is " + watch5.id);
		System.out.println("brand is " + watch5.brand);
		System.out.println("price is " + watch5.price);
		System.out.println("colour is " + watch5.colour);
		System.out.println("type is " + watch5.type);
		System.out.println("display is " + watch5.display);
		System.out.println("material is " + watch5.material);
		System.out.println("gender is " + watch5.gender);

		Watch watch6 = new Watch();
		watch6.id = 6;
		watch6.brand = "Fastrack";
		watch6.price = 2100;
		watch6.colour = "Black";
		watch6.type = "Analog";
		watch6.display = "Round";
		watch6.material = "Metal";
		watch6.gender = "Men";
		System.out.println("watch id is " + watch6.id);
		System.out.println("brand is " + watch6.brand);
		System.out.println("price is " + watch6.price);
		System.out.println("colour is " + watch6.colour);
		System.out.println("type is " + watch6.type);
		System.out.println("display is " + watch6.display);
		System.out.println("material is " + watch6.material);
		System.out.println("gender is " + watch6.gender);

		Watch watch7 = new Watch();
		watch7.id = 7;
		watch7.brand = "Casio";
		watch7.price = 2600;
		watch7.colour = "Grey";
		watch7.type = "Digital";
		watch7.display = "Square";
		watch7.material = "Resin";
		watch7.gender = "Unisex";
		System.out.println("watch id is " + watch7.id);
		System.out.println("brand is " + watch7.brand);
		System.out.println("price is " + watch7.price);
		System.out.println("colour is " + watch7.colour);
		System.out.println("type is " + watch7.type);
		System.out.println("display is " + watch7.display);
		System.out.println("material is " + watch7.material);
		System.out.println("gender is " + watch7.gender);

		Watch watch8 = new Watch();
		watch8.id = 8;
		watch8.brand = "Sonata";
		watch8.price = 1700;
		watch8.colour = "Blue";
		watch8.type = "Analog";
		watch8.display = "Round";
		watch8.material = "Leather";
		watch8.gender = "Women";
		System.out.println("watch id is " + watch8.id);
		System.out.println("brand is " + watch8.brand);
		System.out.println("price is " + watch8.price);
		System.out.println("colour is " + watch8.colour);
		System.out.println("type is " + watch8.type);
		System.out.println("display is " + watch8.display);
		System.out.println("material is " + watch8.material);
		System.out.println("gender is " + watch8.gender);

		Watch watch9 = new Watch();
		watch9.id = 9;
		watch9.brand = "Titan";
		watch9.price = 3400;
		watch9.colour = "RoseGold";
		watch9.type = "Analog";
		watch9.display = "Round";
		watch9.material = "Metal";
		watch9.gender = "Women";
		System.out.println("watch id is " + watch9.id);
		System.out.println("brand is " + watch9.brand);
		System.out.println("price is " + watch9.price);
		System.out.println("colour is " + watch9.colour);
		System.out.println("type is " + watch9.type);
		System.out.println("display is " + watch9.display);
		System.out.println("material is " + watch9.material);
		System.out.println("gender is " + watch9.gender);

		Watch watch10 = new Watch();
		watch10.id = 10;
		watch10.brand = "Fastrack";
		watch10.price = 2300;
		watch10.colour = "Black";
		watch10.type = "Digital";
		watch10.display = "Square";
		watch10.material = "Rubber";
		watch10.gender = "Men";
		System.out.println("watch id is " + watch10.id);
		System.out.println("brand is " + watch10.brand);
		System.out.println("price is " + watch10.price);
		System.out.println("colour is " + watch10.colour);
		System.out.println("type is " + watch10.type);
		System.out.println("display is " + watch10.display);
		System.out.println("material is " + watch10.material);
		System.out.println("gender is " + watch10.gender);
		
		Watch watch10 = new Watch();
		watch10.id = 10;
		watch10.brand = "Fastrack";
		watch10.price = 2300;
		watch10.colour = "Black";
		watch10.type = "Digital";
		watch10.display = "Square";
		watch10.material = "Rubber";
		watch10.gender = "Men";
		System.out.println("watch id is " + watch10.id);
		System.out.println("brand is " + watch10.brand);
		System.out.println("price is " + watch10.price);
		System.out.println("colour is " + watch10.colour);
		System.out.println("type is " + watch10.type);
		System.out.println("display is " + watch10.display);
		System.out.println("material is " + watch10.material);
		System.out.println("gender is " + watch10.gender);

		Watch watch11 = new Watch();
		watch11.id = 11;
		watch11.brand = "Titan";
		watch11.price = 3600;
		watch11.colour = "Silver";
		watch11.type = "Analog";
		watch11.display = "Round";
		watch11.material = "Metal";
		watch11.gender = "Men";
		System.out.println("watch id is " + watch11.id);
		System.out.println("brand is " + watch11.brand);
		System.out.println("price is " + watch11.price);
		System.out.println("colour is " + watch11.colour);
		System.out.println("type is " + watch11.type);
		System.out.println("display is " + watch11.display);
		System.out.println("material is " + watch11.material);
		System.out.println("gender is " + watch11.gender);

		Watch watch12 = new Watch();
		watch12.id = 12;
		watch12.brand = "Casio";
		watch12.price = 2800;
		watch12.colour = "Black";
		watch12.type = "Digital";
		watch12.display = "Square";
		watch12.material = "Resin";
		watch12.gender = "Unisex";
		System.out.println("watch id is " + watch12.id);
		System.out.println("brand is " + watch12.brand);
		System.out.println("price is " + watch12.price);
		System.out.println("colour is " + watch12.colour);
		System.out.println("type is " + watch12.type);
		System.out.println("display is " + watch12.display);
		System.out.println("material is " + watch12.material);
		System.out.println("gender is " + watch12.gender);

		Watch watch13 = new Watch();
		watch13.id = 13;
		watch13.brand = "Sonata";
		watch13.price = 1900;
		watch13.colour = "Brown";
		watch13.type = "Analog";
		watch13.display = "Round";
		watch13.material = "Leather";
		watch13.gender = "Men";
		System.out.println("watch id is " + watch13.id);
		System.out.println("brand is " + watch13.brand);
		System.out.println("price is " + watch13.price);
		System.out.println("colour is " + watch13.colour);
		System.out.println("type is " + watch13.type);
		System.out.println("display is " + watch13.display);
		System.out.println("material is " + watch13.material);
		System.out.println("gender is " + watch13.gender);


		Watch watch14 = new Watch();
		watch14.id = 14;
		watch14.brand = "Titan";
		watch14.price = 4100;
		watch14.colour = "Gold";
		watch14.type = "Analog";
		watch14.display = "Round";
		watch14.material = "Metal";
		watch14.gender = "Women";
		System.out.println("watch id is " + watch14.id);
		System.out.println("brand is " + watch14.brand);
		System.out.println("price is " + watch14.price);
		System.out.println("colour is " + watch14.colour);
		System.out.println("type is " + watch14.type);
		System.out.println("display is " + watch14.display);
		System.out.println("material is " + watch14.material);
		System.out.println("gender is " + watch14.gender);

		Watch watch15 = new Watch();
		watch15.id = 15;
		watch15.brand = "Fastrack";
		watch15.price = 2400;
		watch15.colour = "Blue";
		watch15.type = "Digital";
		watch15.display = "Square";
		watch15.material = "Rubber";
		watch15.gender = "Men";
		System.out.println("watch id is " + watch15.id);
		System.out.println("brand is " + watch15.brand);
		System.out.println("price is " + watch15.price);
		System.out.println("colour is " + watch15.colour);
		System.out.println("type is " + watch15.type);
		System.out.println("display is " + watch15.display);
		System.out.println("material is " + watch15.material);
		System.out.println("gender is " + watch15.gender);

		Watch watch16 = new Watch();
		watch16.id = 16;
		watch16.brand = "Casio";
		watch16.price = 3000;
		watch16.colour = "Grey";
		watch16.type = "Digital";
		watch16.display = "Square";
		watch16.material = "Resin";
		watch16.gender = "Unisex";
		System.out.println("watch id is " + watch16.id);
		System.out.println("brand is " + watch16.brand);
		System.out.println("price is " + watch16.price);
		System.out.println("colour is " + watch16.colour);
		System.out.println("type is " + watch16.type);
		System.out.println("display is " + watch16.display);
		System.out.println("material is " + watch16.material);
		System.out.println("gender is " + watch16.gender);

		Watch watch17 = new Watch();
		watch17.id = 17;
		watch17.brand = "Sonata";
		watch17.price = 2000;
		watch17.colour = "Blue";
		watch17.type = "Analog";
		watch17.display = "Round";
		watch17.material = "Leather";
		watch17.gender = "Women";
		System.out.println("watch id is " + watch17.id);
		System.out.println("brand is " + watch17.brand);
		System.out.println("price is " + watch17.price);
		System.out.println("colour is " + watch17.colour);
		System.out.println("type is " + watch17.type);
		System.out.println("display is " + watch17.display);
		System.out.println("material is " + watch17.material);
		System.out.println("gender is " + watch17.gender);

		Watch watch18 = new Watch();
		watch18.id = 18;
		watch18.brand = "Titan";
		watch18.price = 4500;
		watch18.colour = "RoseGold";
		watch18.type = "Analog";
		watch18.display = "Round";
		watch18.material = "Metal";
		watch18.gender = "Women";
		System.out.println("watch id is " + watch18.id);
		System.out.println("brand is " + watch18.brand);
		System.out.println("price is " + watch18.price);
		System.out.println("colour is " + watch18.colour);
		System.out.println("type is " + watch18.type);
		System.out.println("display is " + watch18.display);
		System.out.println("material is " + watch18.material);
		System.out.println("gender is " + watch18.gender);

		Watch watch19 = new Watch();
		watch19.id = 19;
		watch19.brand = "Fastrack";
		watch19.price = 2600;
		watch19.colour = "Black";
		watch19.type = "Digital";
		watch19.display = "Square";
		watch19.material = "Rubber";
		watch19.gender = "Men";
		System.out.println("watch id is " + watch19.id);
		System.out.println("brand is " + watch19.brand);
		System.out.println("price is " + watch19.price);
		System.out.println("colour is " + watch19.colour);
		System.out.println("type is " + watch19.type);
		System.out.println("display is " + watch19.display);
		System.out.println("material is " + watch19.material);
		System.out.println("gender is " + watch19.gender);

		Watch watch20 = new Watch();
		watch20.id = 20;
		watch20.brand = "Casio";
		watch20.price = 3200;
		watch20.colour = "Grey";
		watch20.type = "Digital";
		watch20.display = "Square";
		watch20.material = "Resin";
		watch20.gender = "Unisex";
		System.out.println("watch id is " + watch20.id);
		System.out.println("brand is " + watch20.brand);
		System.out.println("price is " + watch20.price);
		System.out.println("colour is " + watch20.colour);
		System.out.println("type is " + watch20.type);
		System.out.println("display is " + watch20.display);
		System.out.println("material is " + watch20.material);
		System.out.println("gender is " + watch20.gender);

		Watch watch21 = new Watch();
		watch21.id = 21;
		watch21.brand = "Sonata";
		watch21.price = 2100;
		watch21.colour = "Brown";
		watch21.type = "Analog";
		watch21.display = "Round";
		watch21.material = "Leather";
		watch21.gender = "Men";
		System.out.println("watch id is " + watch21.id);
		System.out.println("brand is " + watch21.brand);
		System.out.println("price is " + watch21.price);
		System.out.println("colour is " + watch21.colour);
		System.out.println("type is " + watch21.type);
		System.out.println("display is " + watch21.display);
		System.out.println("material is " + watch21.material);
		System.out.println("gender is " + watch21.gender);

		Watch watch22 = new Watch();
		watch22.id = 22;
		watch22.brand = "Titan";
		watch22.price = 4700;
		watch22.colour = "Gold";
		watch22.type = "Analog";
		watch22.display = "Round";
		watch22.material = "Metal";
		watch22.gender = "Women";
		System.out.println("watch id is " + watch22.id);
		System.out.println("brand is " + watch22.brand);
		System.out.println("price is " + watch22.price);
		System.out.println("colour is " + watch22.colour);
		System.out.println("type is " + watch22.type);
		System.out.println("display is " + watch22.display);
		System.out.println("material is " + watch22.material);
		System.out.println("gender is " + watch22.gender);

		Watch watch23 = new Watch();
		watch23.id = 23;
		watch23.brand = "Fastrack";
		watch23.price = 2700;
		watch23.colour = "Blue";
		watch23.type = "Digital";
		watch23.display = "Square";
		watch23.material = "Rubber";
		watch23.gender = "Men";
		System.out.println("watch id is " + watch23.id);
		System.out.println("brand is " + watch23.brand);
		System.out.println("price is " + watch23.price);
		System.out.println("colour is " + watch23.colour);
		System.out.println("type is " + watch23.type);
		System.out.println("display is " + watch23.display);
		System.out.println("material is " + watch23.material);
		System.out.println("gender is " + watch23.gender);

		Watch watch24 = new Watch();
		watch24.id = 24;
		watch24.brand = "Casio";
		watch24.price = 3400;
		watch24.colour = "Black";
		watch24.type = "Digital";
		watch24.display = "Square";
		watch24.material = "Resin";
		watch24.gender = "Unisex";
		System.out.println("watch id is " + watch24.id);
		System.out.println("brand is " + watch24.brand);
		System.out.println("price is " + watch24.price);
		System.out.println("colour is " + watch24.colour);
		System.out.println("type is " + watch24.type);
		System.out.println("display is " + watch24.display);
		System.out.println("material is " + watch24.material);
		System.out.println("gender is " + watch24.gender);

		Watch watch25 = new Watch();
		watch25.id = 25;
		watch25.brand = "Sonata";
		watch25.price = 2200;
		watch25.colour = "Blue";
		watch25.type = "Analog";
		watch25.display = "Round";
		watch25.material = "Leather";
		watch25.gender = "Women";
		System.out.println("watch id is " + watch25.id);
		System.out.println("brand is " + watch25.brand);
		System.out.println("price is " + watch25.price);
		System.out.println("colour is " + watch25.colour);
		System.out.println("type is " + watch25.type);
		System.out.println("display is " + watch25.display);
		System.out.println("material is " + watch25.material);
		System.out.println("gender is " + watch25.gender);

		Watch watch26 = new Watch();
		watch26.id = 26;
		watch26.brand = "Titan";
		watch26.price = 4800;
		watch26.colour = "RoseGold";
		watch26.type = "Analog";
		watch26.display = "Round";
		watch26.material = "Metal";
		watch26.gender = "Women";
		System.out.println("watch id is " + watch26.id);
		System.out.println("brand is " + watch26.brand);
		System.out.println("price is " + watch26.price);
		System.out.println("colour is " + watch26.colour);
		System.out.println("type is " + watch26.type);
		System.out.println("display is " + watch26.display);
		System.out.println("material is " + watch26.material);
		System.out.println("gender is " + watch26.gender);

		Watch watch27 = new Watch();
		watch27.id = 27;
		watch27.brand = "Fastrack";
		watch27.price = 2900;
		watch27.colour = "Black";
		watch27.type = "Digital";
		watch27.display = "Square";
		watch27.material = "Rubber";
		watch27.gender = "Men";
		System.out.println("watch id is " + watch27.id);
		System.out.println("brand is " + watch27.brand);
		System.out.println("price is " + watch27.price);
		System.out.println("colour is " + watch27.colour);
		System.out.println("type is " + watch27.type);
		System.out.println("display is " + watch27.display);
		System.out.println("material is " + watch27.material);
		System.out.println("gender is " + watch27.gender);

		Watch watch28 = new Watch();
		watch28.id = 28;
		watch28.brand = "Casio";
		watch28.price = 3600;
		watch28.colour = "Grey";
		watch28.type = "Digital";
		watch28.display = "Square";
		watch28.material = "Resin";
		watch28.gender = "Unisex";
		System.out.println("watch id is " + watch28.id);
		System.out.println("brand is " + watch28.brand);
		System.out.println("price is " + watch28.price);
		System.out.println("colour is " + watch28.colour);
		System.out.println("type is " + watch28.type);
		System.out.println("display is " + watch28.display);
		System.out.println("material is " + watch28.material);
		System.out.println("gender is " + watch28.gender);

		Watch watch29 = new Watch();
		watch29.id = 29;
		watch29.brand = "Sonata";
		watch29.price = 2300;
		watch29.colour = "Brown";
		watch29.type = "Analog";
		watch29.display = "Round";
		watch29.material = "Leather";
		watch29.gender = "Men";
		System.out.println("watch id is " + watch29.id);
		System.out.println("brand is " + watch29.brand);
		System.out.println("price is " + watch29.price);
		System.out.println("colour is " + watch29.colour);
		System.out.println("type is " + watch29.type);
		System.out.println("display is " + watch29.display);
		System.out.println("material is " + watch29.material);
		System.out.println("gender is " + watch29.gender);

		Watch watch30 = new Watch();
		watch30.id = 30;
		watch30.brand = "Titan";
		watch30.price = 5000;
		watch30.colour = "Gold";
		watch30.type = "Analog";
		watch30.display = "Round";
		watch30.material = "Metal";
		watch30.gender = "Women";
		System.out.println("watch id is " + watch30.id);
		System.out.println("brand is " + watch30.brand);
		System.out.println("price is " + watch30.price);
		System.out.println("colour is " + watch30.colour);
		System.out.println("type is " + watch30.type);
		System.out.println("display is " + watch30.display);
		System.out.println("material is " + watch30.material);
		System.out.println("gender is " + watch30.gender);
		
	}
}

